package uk.gov.hmcts.reform.prl.ccd.event;
import uk.gov.hmcts.reform.prl.models.Organisation;
import uk.gov.hmcts.reform.prl.models.dto.barrister.AllocatedBarrister;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code adminAddBarrister} for case type {@code PRLAPPS}.
 */
@Component
public class AdminAddBarrister implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_ADD_BARRISTER = "adminAddBarrister";

    /**
     * Registers event {@code adminAddBarrister}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADMIN_ADD_BARRISTER)
            .forStates(State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Add barrister")
            .description("Caseworker add barrister")
            .displayOrder(200)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getAllocatedBarrister)
                    .mandatory(AllocatedBarrister::getPartyList)
                    .eventLabel("For which party do you want to add a barrister?")
                    .mandatory(AllocatedBarrister::getBarristerFirstName)
                    .eventLabel("First names of the barrister")
                    .mandatory(AllocatedBarrister::getBarristerLastName)
                    .eventLabel("Last name of the barrister")
                    .mandatory(AllocatedBarrister::getBarristerEmail)
                    .eventLabel("Email address of the barrister")
                    .mandatory(AllocatedBarrister::getBarristerOrg)
                    .complex(AllocatedBarrister::getBarristerOrg)
                    .mandatory(Organisation::getOrganisationID)
                    .eventLabel("Barrister organisation Id").done()
                    .complex(AllocatedBarrister::getBarristerOrg)
                    .mandatory(Organisation::getOrganisationName)
                    .eventLabel("Barrister organisation name").done().done();
    }
}
