package uk.gov.hmcts.reform.prl.ccd.event;
import uk.gov.hmcts.reform.prl.models.dto.barrister.AllocatedBarrister;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code adminRemoveBarrister} for case type {@code PRLAPPS}.
 */
@Component
public class AdminRemoveBarrister implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_REMOVE_BARRISTER = "adminRemoveBarrister";

    /**
     * Registers event {@code adminRemoveBarrister}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADMIN_REMOVE_BARRISTER)
            .forStates(State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_WITHDRAWN)
            .name("Remove barrister")
            .description("Caseworker remove barrister")
            .displayOrder(201)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getAllocatedBarrister)
                    .mandatory(AllocatedBarrister::getPartyList)
                    .eventLabel("Select a party to remove a Barrister").done();
    }
}
