package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage21;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage22;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage23;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminEditAndApproveAnOrderPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code adminEditAndApproveAnOrder} for case type {@code PRLAPPS}.
 */
@Component
public class AdminEditAndApproveAnOrder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_EDIT_AND_APPROVE_AN_ORDER = "adminEditAndApproveAnOrder";

    /**
     * Registers event {@code adminEditAndApproveAnOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADMIN_EDIT_AND_APPROVE_AN_ORDER)
            .forStateTransition(EnumSet.of(State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION), State.ALL_FINAL_ORDERS_ISSUED)
            .name("Edit and serve an order")
            .displayOrder(31)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .fields();
        AdminEditAndApproveAnOrderPage1.apply(fields);
        AdminEditAndApproveAnOrderPage10.apply(fields);
        AdminEditAndApproveAnOrderPage11.apply(fields);
        AdminEditAndApproveAnOrderPage13.apply(fields);
        AdminEditAndApproveAnOrderPage14.apply(fields);
        AdminEditAndApproveAnOrderPage15.apply(fields);
        AdminEditAndApproveAnOrderPage16.apply(fields);
        AdminEditAndApproveAnOrderPage17.apply(fields);
        AdminEditAndApproveAnOrderPage2.apply(fields);
        AdminEditAndApproveAnOrderPage20.apply(fields);
        AdminEditAndApproveAnOrderPage21.apply(fields);
        AdminEditAndApproveAnOrderPage22.apply(fields);
        AdminEditAndApproveAnOrderPage23.apply(fields);
        AdminEditAndApproveAnOrderPage4.apply(fields);
        AdminEditAndApproveAnOrderPage5.apply(fields);
        AdminEditAndApproveAnOrderPage6.apply(fields);
        AdminEditAndApproveAnOrderPage7.apply(fields);
        AdminEditAndApproveAnOrderPage8.apply(fields);
        AdminEditAndApproveAnOrderPage9.apply(fields);
    }
}
