package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code adminAddLocalAuthority} for case type {@code PRLAPPS}.
 */
@Component
public class AdminAddLocalAuthority implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_ADD_LOCAL_AUTHORITY = "adminAddLocalAuthority";

    /**
     * Registers event {@code adminAddLocalAuthority}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ADMIN_ADD_LOCAL_AUTHORITY)
            .forStates(State.CASE_ISSUED, State.AWAITING_RESUBMISSION_TO_HMCTS, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Add local authority")
            .description("Caseworker add local authority")
            .displayOrder(200)
            .showCondition("caseTypeOfApplication=\"C100\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getLocalAuthoritySolicitorOrganisationPolicy).done();
    }
}
