package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminCreateNonprodPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminCreateNonprodPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminCreateNonprodPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminCreateNonprodPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.AdminCreateNonprodPage6;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code adminCreate} for case type {@code PRLAPPS}.
 */
@Component
public class AdminCreateNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_CREATE = "adminCreate";

    /**
     * Registers overlay event {@code adminCreate} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(ADMIN_CREATE)
            .initialState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("Court admin application")
            .description("Apply for a court order to make arrangements for a child or resolve a dispute about their upbringing")
            .displayOrder(1)
            .showSummary()
            .ttlIncrement(28)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN_CASECREATOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN)
            .fields();
        AdminCreateNonprodPage2.apply(fields);
        AdminCreateNonprodPage3.apply(fields);
        AdminCreateNonprodPage6.apply(fields);
        AdminCreateNonprodPage4.apply(fields);
        AdminCreateNonprodPage5.apply(fields);
    }
}
