package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code allAwPInReview} for case type {@code PRLAPPS}.
 */
@Component
public class AllAwPInReview implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ALL_AW_PIN_REVIEW = "allAwPInReview";

    /**
     * Registers event {@code allAwPInReview}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(ALL_AW_PIN_REVIEW)
            .forAllStates()
            .name("Complete AWP Task")
            .description("Complete AWP Task event")
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
    }
}
