package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmPage4;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code allegationsOfHarm} for case type {@code PRLAPPS}.
 */
@Component
public class AllegationsOfHarm implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ALLEGATIONS_OF_HARM = "allegationsOfHarm";

    /**
     * Registers event {@code allegationsOfHarm}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ALLEGATIONS_OF_HARM)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Allegations of harm")
            .displayOrder(9)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"v2\" AND taskListVersion!=\"v3\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        AllegationsOfHarmPage1.apply(fields);
        AllegationsOfHarmPage2.apply(fields);
        AllegationsOfHarmPage3.apply(fields);
        AllegationsOfHarmPage4.apply(fields);
    }
}
