package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.AllegationsOfHarmRevisedPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.ChildAbuse;
import uk.gov.hmcts.reform.prl.models.complextypes.DomesticAbuseBehaviours;
import uk.gov.hmcts.reform.prl.models.dto.ccd.AllegationOfHarmRevised;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ChildPassportDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code allegationsOfHarmRevised} for case type {@code PRLAPPS}.
 */
@Component
public class AllegationsOfHarmRevised implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ALLEGATIONS_OF_HARM_REVISED = "allegationsOfHarmRevised";

    /**
     * Registers event {@code allegationsOfHarmRevised}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ALLEGATIONS_OF_HARM_REVISED)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Allegations of harm")
            .displayOrder(9)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        AllegationsOfHarmRevisedPage1.apply(fields);
        AllegationsOfHarmRevisedPage2.apply(fields);
        AllegationsOfHarmRevisedPage3.apply(fields);
        AllegationsOfHarmRevisedPage4.apply(fields);
        AllegationsOfHarmRevisedPage5.apply(fields);
        AllegationsOfHarmRevisedPage6.apply(fields);
        AllegationsOfHarmRevisedPage7.apply(fields);
        AllegationsOfHarmRevisedPage8.apply(fields);
        AllegationsOfHarmRevisedPage9.apply(fields);
        AllegationsOfHarmRevisedPage10.apply(fields);
        AllegationsOfHarmRevisedPage11.apply(fields);
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complex(AllegationOfHarmRevised::getDomesticBehaviours, DomesticAbuseBehaviours.class)
                    .optional(DomesticAbuseBehaviours::getTypeOfAbuse)
                    .optional(DomesticAbuseBehaviours::getNewAbuseNatureDescription)
                    .optional(DomesticAbuseBehaviours::getNewBehavioursStartDateAndLength)
                    .optional(DomesticAbuseBehaviours::getNewBehavioursApplicantSoughtHelp)
                    .optional(DomesticAbuseBehaviours::getNewBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("domesticBehaviours.newBehavioursApplicantSoughtHelp=\"Yes\"").done().done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complexScope(AllegationOfHarmRevised::getChildPassportDetails)
                    .mandatory(ChildPassportDetails::getNewChildHasMultiplePassports)
                    .mandatory(ChildPassportDetails::getNewChildPassportPossession)
                    .mandatory(ChildPassportDetails::getNewChildPassportPossessionOtherDetails)
                    .fieldShowCondition("childPassportDetails.newChildPassportPossession CONTAINS \"otherPerson\"").done().done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complexScope(AllegationOfHarmRevised::getChildPhysicalAbuse)
                    .optional(ChildAbuse::getTypeOfAbuse)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .optional(ChildAbuse::getAbuseNatureDescription)
                    .optional(ChildAbuse::getBehavioursStartDateAndLength)
                    .optional(ChildAbuse::getBehavioursApplicantSoughtHelp)
                    .optional(ChildAbuse::getBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("childPhysicalAbuse.behavioursApplicantSoughtHelp=\"Yes\"").done().done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complexScope(AllegationOfHarmRevised::getChildPsychologicalAbuse)
                    .optional(ChildAbuse::getTypeOfAbuse)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .optional(ChildAbuse::getAbuseNatureDescription)
                    .optional(ChildAbuse::getBehavioursStartDateAndLength)
                    .optional(ChildAbuse::getBehavioursApplicantSoughtHelp)
                    .optional(ChildAbuse::getBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("childPsychologicalAbuse.behavioursApplicantSoughtHelp=\"Yes\"").done().done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complexScope(AllegationOfHarmRevised::getChildSexualAbuse)
                    .optional(ChildAbuse::getTypeOfAbuse)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .optional(ChildAbuse::getAbuseNatureDescription)
                    .optional(ChildAbuse::getBehavioursStartDateAndLength)
                    .optional(ChildAbuse::getBehavioursApplicantSoughtHelp)
                    .optional(ChildAbuse::getBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("childSexualAbuse.behavioursApplicantSoughtHelp=\"Yes\"").done().done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complexScope(AllegationOfHarmRevised::getChildEmotionalAbuse)
                    .optional(ChildAbuse::getTypeOfAbuse)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .optional(ChildAbuse::getAbuseNatureDescription)
                    .optional(ChildAbuse::getBehavioursStartDateAndLength)
                    .optional(ChildAbuse::getBehavioursApplicantSoughtHelp)
                    .optional(ChildAbuse::getBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("childEmotionalAbuse.behavioursApplicantSoughtHelp=\"Yes\"").done().done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .complexScope(AllegationOfHarmRevised::getChildFinancialAbuse)
                    .optional(ChildAbuse::getTypeOfAbuse)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .optional(ChildAbuse::getAbuseNatureDescription)
                    .optional(ChildAbuse::getBehavioursStartDateAndLength)
                    .optional(ChildAbuse::getBehavioursApplicantSoughtHelp)
                    .optional(ChildAbuse::getBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("childFinancialAbuse.behavioursApplicantSoughtHelp=\"Yes\"").done().done();
    }
}
