package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code allocatedJudge} for case type {@code PRLAPPS}.
 */
@Component
public class AllocatedJudge implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ALLOCATED_JUDGE = "allocatedJudge";

    /**
     * Registers event {@code allocatedJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ALLOCATED_JUDGE)
            .forStates(State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Allocated judge")
            .displayOrder(4)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAllocatedJudeLabel)
                    .publish(false)
                    .readonlyNoSummary(CaseDataExtra::getAllocatedJudgeInfo)
                    .publish(false)
                    .mandatory(CaseDataExtra::getIsSpecificJudgeOrLegalAdviserNeeded)
                    .publish(false)
                    .mandatory(CaseDataExtra::getIsJudgeOrLegalAdviser)
                    .fieldShowCondition("isSpecificJudgeOrLegalAdviserNeeded=\"Yes\"")
                    .publish(false)
                    .mandatory(CaseDataExtra::getJudgeNameAndEmail)
                    .fieldShowCondition("isSpecificJudgeOrLegalAdviserNeeded=\"Yes\" AND isJudgeOrLegalAdviser=\"judge\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getLegalAdviserList)
                    .fieldShowCondition("isSpecificJudgeOrLegalAdviserNeeded=\"Yes\" AND isJudgeOrLegalAdviser=\"legalAdviser\"")
                    .publish(false);
        fields.complex(CaseData::getCaseDataExtra)
                    .mandatory(CaseDataExtra::getTierOfJudiciary)
                    .fieldShowCondition("isSpecificJudgeOrLegalAdviserNeeded=\"No\"")
                    .publish(false).done();
    }
}
