package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.AttendHearing;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendAttendingTheHearing} for case type {@code PRLAPPS}.
 */
@Component
public class AmendAttendingTheHearing implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_ATTENDING_THE_HEARING = "amendAttendingTheHearing";

    /**
     * Registers event {@code amendAttendingTheHearing}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_ATTENDING_THE_HEARING)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Amend attending the hearing")
            .description("Attending the hearing")
            .displayOrder(8)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSubmissionRequiredFieldsInfo1)
                    .publish(false)
                    .readonly(CaseDataExtra::getLabelLanguageRequirements)
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getIsWelshNeeded)
                    .publish(false)
                    .optional(AttendHearing::getWelshNeeds)
                    .fieldShowCondition("caseTypeOfApplication=\"C100\" AND isWelshNeeded=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optional(CaseDataExtra::getFl401WelshNeeds)
                    .fieldShowCondition("caseTypeOfApplication=\"FL401\" AND isWelshNeeded=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getIsInterpreterNeeded)
                    .publish(false)
                    .optional(AttendHearing::getInterpreterNeeds)
                    .fieldShowCondition("isInterpreterNeeded=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getLabelAccessibility)
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getIsDisabilityPresent)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getLabelAdjustmentsRequired)
                    .fieldShowCondition("isDisabilityPresent=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getAdjustmentsRequired)
                    .fieldShowCondition("isDisabilityPresent=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getLabelSpecialArrangements)
                    .publish(false)
                    .readonly(CaseDataExtra::getLabelSpecialArrangementsDescription)
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getIsSpecialArrangementsRequired)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getLabelSpecialArrangementsRequired)
                    .fieldShowCondition("isSpecialArrangementsRequired=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getSpecialArrangementsRequired)
                    .fieldShowCondition("isSpecialArrangementsRequired=\"Yes\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getLabelIntermediaryDescription)
                    .publish(false).done();
        fields.complex(CaseData::getAttendHearing)
                    .mandatory(AttendHearing::getIsIntermediaryNeeded)
                    .publish(false)
                    .mandatory(AttendHearing::getReasonsForIntermediary)
                    .fieldShowCondition("isIntermediaryNeeded=\"Yes\"")
                    .publish(false).done();
        fields.mandatoryNoSummary(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("labelLanguageRequirements=\"DO_NOT_SHOW\"");
    }
}
