package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendCourtDetails} for case type {@code PRLAPPS}.
 */
@Component
public class AmendCourtDetailsProd implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_COURT_DETAILS = "amendCourtDetails";

    /**
     * Registers overlay event {@code amendCourtDetails} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(AMEND_COURT_DETAILS)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.AWAITING_RESUBMISSION_TO_HMCTS, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Amend court details")
            .displayOrder(10)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .fields();
        fields.page("1");
        fields.mandatory(CaseData::getCourtList);
        fields.mandatory(CaseData::getCourtId)
                    .fieldShowCondition("courtList=\"DONTSHOW\"");
        fields.mandatory(CaseData::getReasonForAmendCourtDetails)
                    .publish(false);
        fields.optional(CaseData::getCourtEmailAddress)
                    .publish(false);
    }
}
