package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.Relations;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendChildrenAndOtherPeople} for case type {@code PRLAPPS}.
 */
@Component
public class AmendChildrenAndOtherPeople implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_CHILDREN_AND_OTHER_PEOPLE = "amendChildrenAndOtherPeople";

    /**
     * Registers event {@code amendChildrenAndOtherPeople}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_CHILDREN_AND_OTHER_PEOPLE)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Amend children/other people")
            .description("Amend a relation between Children and Other People")
            .displayOrder(10)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getChildAndOtherPeopleRelationsLabel)
                    .readonlyNoSummary(CaseDataExtra::getChildAndOtherPeopleRelationsSubLabel).done();
        fields.complex(CaseData::getRelations)
                    .optional(Relations::getBuffChildAndOtherPeopleRelations).done();
    }
}
