package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmRevisedPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendAllegationsOfHarmRevised} for case type {@code PRLAPPS}.
 */
@Component
public class AmendAllegationsOfHarmRevised implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_ALLEGATIONS_OF_HARM_REVISED = "amendAllegationsOfHarmRevised";

    /**
     * Registers event {@code amendAllegationsOfHarmRevised}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_ALLEGATIONS_OF_HARM_REVISED)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.AWAITING_INFORMATION)
            .name("Amend Allegations of harm")
            .description("Allegations of harm")
            .displayOrder(9)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CITIZEN)
            .fields();
        AmendAllegationsOfHarmRevisedPage1.apply(fields);
        AmendAllegationsOfHarmRevisedPage2.apply(fields);
        AmendAllegationsOfHarmRevisedPage3.apply(fields);
        AmendAllegationsOfHarmRevisedPage4.apply(fields);
        AmendAllegationsOfHarmRevisedPage5.apply(fields);
        AmendAllegationsOfHarmRevisedPage6.apply(fields);
        AmendAllegationsOfHarmRevisedPage7.apply(fields);
        AmendAllegationsOfHarmRevisedPage8.apply(fields);
        AmendAllegationsOfHarmRevisedPage9.apply(fields);
        AmendAllegationsOfHarmRevisedPage10.apply(fields);
        AmendAllegationsOfHarmRevisedPage11.apply(fields);
    }
}
