package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.AmendAllegationsOfHarmPage4;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendAllegationsOfHarm} for case type {@code PRLAPPS}.
 */
@Component
public class AmendAllegationsOfHarm implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_ALLEGATIONS_OF_HARM = "amendAllegationsOfHarm";

    /**
     * Registers event {@code amendAllegationsOfHarm}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_ALLEGATIONS_OF_HARM)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Amend Allegations of harm")
            .description("Allegations of harm")
            .displayOrder(5)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"v2\" AND taskListVersion!=\"v3\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        AmendAllegationsOfHarmPage1.apply(fields);
        AmendAllegationsOfHarmPage2.apply(fields);
        AmendAllegationsOfHarmPage3.apply(fields);
        AmendAllegationsOfHarmPage4.apply(fields);
    }
}
