package uk.gov.hmcts.reform.prl.ccd.event;
import uk.gov.hmcts.reform.prl.models.complextypes.ProceedingDetails;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendOtherProceedings} for case type {@code PRLAPPS}.
 */
@Component
public class AmendOtherProceedings implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_OTHER_PROCEEDINGS = "amendOtherProceedings";

    /**
     * Registers event {@code amendOtherProceedings}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_OTHER_PROCEEDINGS)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Amend Other proceedings")
            .description("Details of other preceedings")
            .displayOrder(16)
            .showCondition("caseTypeOfApplication=\"C100\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSubmissionRequiredFieldsInfo1)
                    .readonly(CaseDataExtra::getOtherProceedingsLabel).done();
        fields.optional(CaseData::getPreviousOrOngoingProceedingsForChildren);
        fields.complex(CaseData::getExistingProceedings).done()
                    .fieldShowCondition("previousOrOngoingProceedingsForChildren=\"yes\"");
        fields.complex(CaseData::getExistingProceedings, ProceedingDetails.class)
                    .optional(ProceedingDetails::getPreviousOrOngoingProceedings)
                    .optional(ProceedingDetails::getCaseNumber)
                    .optional(ProceedingDetails::getDateStarted)
                    .eventLabel("Date started")
                    .optional(ProceedingDetails::getDateEnded)
                    .optional(ProceedingDetails::getTypeOfOrder)
                    .optional(ProceedingDetails::getOtherTypeOfOrder)
                    .fieldShowCondition("existingProceedings.typeOfOrder CONTAINS \"otherOrder\"")
                    .optional(ProceedingDetails::getNameOfJudge)
                    .optional(ProceedingDetails::getNameOfCourt)
                    .optional(ProceedingDetails::getNameOfChildrenInvolved)
                    .optional(ProceedingDetails::getNameOfGuardian)
                    .optional(ProceedingDetails::getNameAndOffice)
                    .optional(ProceedingDetails::getUploadRelevantOrder).done();
    }
}
