package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code amendInternationalElement} for case type {@code PRLAPPS}.
 */
@Component
public class AmendInternationalElement implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_INTERNATIONAL_ELEMENT = "amendInternationalElement";

    /**
     * Registers event {@code amendInternationalElement}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(AMEND_INTERNATIONAL_ELEMENT)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Amend International element")
            .description("Amend international element of the case")
            .displayOrder(12)
            .showCondition("caseTypeOfApplication=\"C100\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSubmissionRequiredFieldsInfo1).done();
        fields.optional(CaseData::getHabitualResidentInOtherState);
        fields.optional(CaseData::getHabitualResidentInOtherStateGiveReason)
                    .fieldShowCondition("habitualResidentInOtherState=\"Yes\"");
        fields.optional(CaseData::getJurisdictionIssue);
        fields.optional(CaseData::getJurisdictionIssueGiveReason)
                    .fieldShowCondition("jurisdictionIssue=\"Yes\"");
        fields.optional(CaseData::getRequestToForeignAuthority);
        fields.optional(CaseData::getRequestToForeignAuthorityGiveReason)
                    .fieldShowCondition("requestToForeignAuthority=\"Yes\"");
    }
}
