package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmCPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code c100ResSolAllegationsOfHarmC} for case type {@code PRLAPPS}.
 */
@Component
public class C100ResSolAllegationsOfHarmC implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String C100_RES_SOL_ALLEGATIONS_OF_HARM_C = "c100ResSolAllegationsOfHarmC";

    /**
     * Registers event {@code c100ResSolAllegationsOfHarmC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(C100_RES_SOL_ALLEGATIONS_OF_HARM_C)
            .forAllStates()
            .name("Allegations of harm")
            .description("Respondent allegations of harm details")
            .displayOrder(7)
            .showCondition("caseTypeOfApplication=\"never_show\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.C100_RESPONDENTSOLICITOR3)
            .fields();
        C100ResSolAllegationsOfHarmCPage1.apply(fields);
        C100ResSolAllegationsOfHarmCPage2.apply(fields);
        C100ResSolAllegationsOfHarmCPage3.apply(fields);
        C100ResSolAllegationsOfHarmCPage4.apply(fields);
        C100ResSolAllegationsOfHarmCPage5.apply(fields);
        C100ResSolAllegationsOfHarmCPage6.apply(fields);
        C100ResSolAllegationsOfHarmCPage7.apply(fields);
        C100ResSolAllegationsOfHarmCPage8.apply(fields);
        C100ResSolAllegationsOfHarmCPage9.apply(fields);
        C100ResSolAllegationsOfHarmCPage10.apply(fields);
        C100ResSolAllegationsOfHarmCPage11.apply(fields);
    }
}
