package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmBPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code c100ResSolAllegationsOfHarmB} for case type {@code PRLAPPS}.
 */
@Component
public class C100ResSolAllegationsOfHarmB implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String C100_RES_SOL_ALLEGATIONS_OF_HARM_B = "c100ResSolAllegationsOfHarmB";

    /**
     * Registers event {@code c100ResSolAllegationsOfHarmB}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(C100_RES_SOL_ALLEGATIONS_OF_HARM_B)
            .forAllStates()
            .name("Allegations of harm")
            .description("Respondent allegations of harm details")
            .displayOrder(7)
            .showCondition("caseTypeOfApplication=\"never_show\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.C100_RESPONDENTSOLICITOR2)
            .fields();
        C100ResSolAllegationsOfHarmBPage1.apply(fields);
        C100ResSolAllegationsOfHarmBPage2.apply(fields);
        C100ResSolAllegationsOfHarmBPage3.apply(fields);
        C100ResSolAllegationsOfHarmBPage4.apply(fields);
        C100ResSolAllegationsOfHarmBPage5.apply(fields);
        C100ResSolAllegationsOfHarmBPage6.apply(fields);
        C100ResSolAllegationsOfHarmBPage7.apply(fields);
        C100ResSolAllegationsOfHarmBPage8.apply(fields);
        C100ResSolAllegationsOfHarmBPage9.apply(fields);
        C100ResSolAllegationsOfHarmBPage10.apply(fields);
        C100ResSolAllegationsOfHarmBPage11.apply(fields);
    }
}
