package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolAllegationsOfHarmDPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.RespChildAbuse;
import uk.gov.hmcts.reform.prl.models.complextypes.RespDomesticAbuseBehaviours;
import uk.gov.hmcts.reform.prl.models.complextypes.solicitorresponse.RespondentAllegationsOfHarmData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.RespChildPassportDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code c100ResSolAllegationsOfHarmD} for case type {@code PRLAPPS}.
 */
@Component
public class C100ResSolAllegationsOfHarmD implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String C100_RES_SOL_ALLEGATIONS_OF_HARM_D = "c100ResSolAllegationsOfHarmD";

    /**
     * Registers event {@code c100ResSolAllegationsOfHarmD}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(C100_RES_SOL_ALLEGATIONS_OF_HARM_D)
            .forAllStates()
            .name("Allegations of harm")
            .description("Respondent allegations of harm details")
            .displayOrder(7)
            .showCondition("caseTypeOfApplication=\"never_show\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.C100_RESPONDENTSOLICITOR4)
            .fields();
        C100ResSolAllegationsOfHarmDPage1.apply(fields);
        C100ResSolAllegationsOfHarmDPage2.apply(fields);
        C100ResSolAllegationsOfHarmDPage3.apply(fields);
        C100ResSolAllegationsOfHarmDPage4.apply(fields);
        C100ResSolAllegationsOfHarmDPage5.apply(fields);
        C100ResSolAllegationsOfHarmDPage6.apply(fields);
        C100ResSolAllegationsOfHarmDPage7.apply(fields);
        C100ResSolAllegationsOfHarmDPage8.apply(fields);
        C100ResSolAllegationsOfHarmDPage9.apply(fields);
        C100ResSolAllegationsOfHarmDPage10.apply(fields);
        C100ResSolAllegationsOfHarmDPage11.apply(fields);
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complex(RespondentAllegationsOfHarmData::getRespDomesticBehaviours, RespDomesticAbuseBehaviours.class)
                    .optional(RespDomesticAbuseBehaviours::getRespTypeOfAbuse)
                    .optional(RespDomesticAbuseBehaviours::getRespAbuseNatureDescription)
                    .optional(RespDomesticAbuseBehaviours::getRespBehavioursStartDateAndLength)
                    .optional(RespDomesticAbuseBehaviours::getRespBehavioursApplicantSoughtHelp)
                    .optional(RespDomesticAbuseBehaviours::getRespBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("respDomesticBehaviours.respBehavioursApplicantSoughtHelp=\"Yes\"").done().done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complexScope(RespondentAllegationsOfHarmData::getRespChildPassportDetails)
                    .mandatory(RespChildPassportDetails::getRespChildHasMultiplePassports)
                    .mandatory(RespChildPassportDetails::getRespChildPassportPossession)
                    .mandatory(RespChildPassportDetails::getRespChildPassportPossessionOtherDetails)
                    .fieldShowCondition("respChildPassportDetails.respChildPassportPossession CONTAINS \"otherPerson\"").done().done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complexScope(RespondentAllegationsOfHarmData::getRespChildPhysicalAbuse)
                    .optional(RespChildAbuse::getRespAbuseNatureDescription)
                    .optional(RespChildAbuse::getRespBehavioursStartDateAndLength)
                    .optional(RespChildAbuse::getRespBehavioursApplicantSoughtHelp)
                    .optional(RespChildAbuse::getRespBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("respChildPhysicalAbuse.respBehavioursApplicantSoughtHelp=\"Yes\"").done().done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complexScope(RespondentAllegationsOfHarmData::getRespChildPsychologicalAbuse)
                    .optional(RespChildAbuse::getRespAbuseNatureDescription)
                    .optional(RespChildAbuse::getRespBehavioursStartDateAndLength)
                    .optional(RespChildAbuse::getRespBehavioursApplicantSoughtHelp)
                    .optional(RespChildAbuse::getRespBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("respChildPsychologicalAbuse.respBehavioursApplicantSoughtHelp=\"Yes\"").done().done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complexScope(RespondentAllegationsOfHarmData::getRespChildFinancialAbuse)
                    .optional(RespChildAbuse::getRespAbuseNatureDescription)
                    .optional(RespChildAbuse::getRespBehavioursStartDateAndLength)
                    .optional(RespChildAbuse::getRespBehavioursApplicantSoughtHelp)
                    .optional(RespChildAbuse::getRespBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("respChildFinancialAbuse.respBehavioursApplicantSoughtHelp=\"Yes\"").done().done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complexScope(RespondentAllegationsOfHarmData::getRespChildSexualAbuse)
                    .optional(RespChildAbuse::getRespAbuseNatureDescription)
                    .optional(RespChildAbuse::getRespBehavioursStartDateAndLength)
                    .optional(RespChildAbuse::getRespBehavioursApplicantSoughtHelp)
                    .optional(RespChildAbuse::getRespBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("respChildSexualAbuse.respBehavioursApplicantSoughtHelp=\"Yes\"").done().done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .complexScope(RespondentAllegationsOfHarmData::getRespChildEmotionalAbuse)
                    .optional(RespChildAbuse::getRespAbuseNatureDescription)
                    .optional(RespChildAbuse::getRespBehavioursStartDateAndLength)
                    .optional(RespChildAbuse::getRespBehavioursApplicantSoughtHelp)
                    .optional(RespChildAbuse::getRespBehavioursApplicantHelpSoughtWho)
                    .fieldShowCondition("respChildEmotionalAbuse.respBehavioursApplicantSoughtHelp=\"Yes\"").done().done().done();
    }
}
