package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolMiamAPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.C100ResSolMiamAPage2;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code c100ResSolMiamA} for case type {@code PRLAPPS}.
 */
@Component
public class C100ResSolMiamA implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String C100_RES_SOL_MIAM_A = "c100ResSolMiamA";

    /**
     * Registers event {@code c100ResSolMiamA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(C100_RES_SOL_MIAM_A)
            .forAllStates()
            .name("MIAM")
            .description("C100 Respondent Solicitor providing MIAM information")
            .displayOrder(5)
            .showCondition("caseTypeOfApplication=\"never_show\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.C100_RESPONDENTSOLICITOR1)
            .fields();
        C100ResSolMiamAPage1.apply(fields);
        C100ResSolMiamAPage2.apply(fields);
    }
}
