package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.ChildDetailsRevisedPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.ChildDetailsRevisedPage2;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code childDetailsRevised} for case type {@code PRLAPPS}.
 */
@Component
public class ChildDetailsRevised implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CHILD_DETAILS_REVISED = "childDetailsRevised";

    /**
     * Registers event {@code childDetailsRevised}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(CHILD_DETAILS_REVISED)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Child details")
            .description("Details of the children in the case")
            .displayOrder(6)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        ChildDetailsRevisedPage1.apply(fields);
        ChildDetailsRevisedPage2.apply(fields);
    }
}
