package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code citizenSaveC100DraftInternal} for case type {@code PRLAPPS}.
 */
@Component
public class CitizenSaveC100DraftInternal implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CITIZEN_SAVE_C100_DRAFT_INTERNAL = "citizenSaveC100DraftInternal";

    /**
     * Registers event {@code citizenSaveC100DraftInternal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(CITIZEN_SAVE_C100_DRAFT_INTERNAL)
            .forState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("Citizen saving C100 draft")
            .description("Citizen saving draft internally while drafting")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
    }
}
