package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage12;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code draftAnOrder} for case type {@code PRLAPPS}.
 */
@Component
public class DraftAnOrder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DRAFT_AN_ORDER = "draftAnOrder";

    /**
     * Registers event {@code draftAnOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DRAFT_AN_ORDER)
            .forStateTransition(EnumSet.of(State.AWAITING_SUBMISSION_TO_HMCTS, State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_WITHDRAWN, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION), State.ALL_FINAL_ORDERS_ISSUED)
            .name("Create/upload draft order")
            .displayOrder(28)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.C100_APPLICANTBARRISTER1, UserRole.C100_APPLICANTBARRISTER2, UserRole.C100_APPLICANTBARRISTER3, UserRole.C100_APPLICANTBARRISTER4, UserRole.C100_APPLICANTBARRISTER5, UserRole.C100_RESPONDENTBARRISTER1, UserRole.C100_RESPONDENTBARRISTER2, UserRole.C100_RESPONDENTBARRISTER3, UserRole.C100_RESPONDENTBARRISTER4, UserRole.C100_RESPONDENTBARRISTER5, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.FL401_APPLICANTBARRISTER, UserRole.FL401_RESPONDENTBARRISTER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .fields();
        DraftAnOrderPage1.apply(fields);
        DraftAnOrderPage10.apply(fields);
        DraftAnOrderPage11.apply(fields);
        DraftAnOrderPage12.apply(fields);
        DraftAnOrderPage13.apply(fields);
        DraftAnOrderPage14.apply(fields);
        DraftAnOrderPage15.apply(fields);
        DraftAnOrderPage16.apply(fields);
        DraftAnOrderPage17.apply(fields);
        DraftAnOrderPage2.apply(fields);
        DraftAnOrderPage20.apply(fields);
        DraftAnOrderPage3.apply(fields);
        DraftAnOrderPage4.apply(fields);
        DraftAnOrderPage5.apply(fields);
        DraftAnOrderPage6.apply(fields);
        DraftAnOrderPage7.apply(fields);
        DraftAnOrderPage8.apply(fields);
        DraftAnOrderPage9.apply(fields);
    }
}
