package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage12;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.DraftAnOrderPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.Address;
import uk.gov.hmcts.reform.prl.models.complextypes.MiamAttendingPersonName;
import uk.gov.hmcts.reform.prl.models.complextypes.draftorder.dio.DioApplicationToApplyPermission;
import uk.gov.hmcts.reform.prl.models.complextypes.draftorder.sdo.PartyNameDA;
import uk.gov.hmcts.reform.prl.models.complextypes.draftorder.sdo.SdoDisclosureOfPapersCaseNumber;
import uk.gov.hmcts.reform.prl.models.complextypes.draftorder.sdo.SdoLanguageDialect;
import uk.gov.hmcts.reform.prl.models.complextypes.manageorders.DirectionDetails;
import uk.gov.hmcts.reform.prl.models.complextypes.manageorders.FL404;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.DirectionOnIssue;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.SchoolDirectionsDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.StandardDirectionOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code draftAnOrder} for case type {@code PRLAPPS}.
 */
@Component
public class DraftAnOrder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DRAFT_AN_ORDER = "draftAnOrder";

    /**
     * Registers event {@code draftAnOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(DRAFT_AN_ORDER)
            .forStateTransition(EnumSet.of(State.AWAITING_SUBMISSION_TO_HMCTS, State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_WITHDRAWN, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION), State.ALL_FINAL_ORDERS_ISSUED)
            .name("Create/upload draft order")
            .displayOrder(28)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.C100_APPLICANTBARRISTER1, UserRole.C100_APPLICANTBARRISTER2, UserRole.C100_APPLICANTBARRISTER3, UserRole.C100_APPLICANTBARRISTER4, UserRole.C100_APPLICANTBARRISTER5, UserRole.C100_RESPONDENTBARRISTER1, UserRole.C100_RESPONDENTBARRISTER2, UserRole.C100_RESPONDENTBARRISTER3, UserRole.C100_RESPONDENTBARRISTER4, UserRole.C100_RESPONDENTBARRISTER5, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.FL401_APPLICANTBARRISTER, UserRole.FL401_RESPONDENTBARRISTER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .fields();
        DraftAnOrderPage1.apply(fields);
        DraftAnOrderPage10.apply(fields);
        DraftAnOrderPage11.apply(fields);
        DraftAnOrderPage12.apply(fields);
        DraftAnOrderPage13.apply(fields);
        DraftAnOrderPage14.apply(fields);
        DraftAnOrderPage15.apply(fields);
        DraftAnOrderPage16.apply(fields);
        DraftAnOrderPage17.apply(fields);
        DraftAnOrderPage2.apply(fields);
        DraftAnOrderPage20.apply(fields);
        DraftAnOrderPage3.apply(fields);
        DraftAnOrderPage4.apply(fields);
        DraftAnOrderPage5.apply(fields);
        DraftAnOrderPage6.apply(fields);
        DraftAnOrderPage7.apply(fields);
        DraftAnOrderPage8.apply(fields);
        DraftAnOrderPage9.apply(fields);
        fields.complex(CaseData::getDirectionOnIssue)
                    .complex(DirectionOnIssue::getDioPartiesRaisedAbuseCollection, PartyNameDA.class)
                    .mandatory(PartyNameDA::getPartyName).done().done();
        fields.complex(CaseData::getDirectionOnIssue)
                    .complex(DirectionOnIssue::getDioInterpreterDialectRequired, SdoLanguageDialect.class)
                    .mandatory(SdoLanguageDialect::getLanguageOrDialect).done().done();
        fields.complex(CaseData::getDirectionOnIssue)
                    .complex(DirectionOnIssue::getDioDisclosureOfPapersCaseNumbers, SdoDisclosureOfPapersCaseNumber.class)
                    .mandatory(SdoDisclosureOfPapersCaseNumber::getCaseNumber).done().done();
        fields.complex(CaseData::getDirectionOnIssue)
                    .complex(DirectionOnIssue::getDioApplicationToApplyPermission, DioApplicationToApplyPermission.class)
                    .mandatory(DioApplicationToApplyPermission::getApplyPermissionToEditSection).done().done();
        fields.complex(CaseData::getManageOrders)
                    .complexScope(ManageOrders::getFl404CustomFields)
                    .mandatory(FL404::getFl404bCourtName)
                    .fieldShowCondition("fl404CustomFields.fl404bCourtName=\"DO_NOT_SHOW\"")
                    .eventLabel("Court name")
                    .mandatory(FL404::getFl404bCourtAddress)
                    .eventLabel(" ")
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getAddressLine1).done()
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getPostTown).done()
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getCounty).done()
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getPostCode).done()
                    .complex(FL404::getFl404bCourtAddress)
                    .optional(Address::getCountry).done()
                    .mandatory(FL404::getFl404bCaseNumber)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Case number")
                    .mandatory(FL404::getFl404bApplicantName)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Applicant name")
                    .optional(FL404::getFl404bApplicantReference)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Applicant reference")
                    .mandatory(FL404::getFl404bRespondentName)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Respondent name")
                    .optional(FL404::getFl404bRespondentReference)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Respondent reference")
                    .mandatory(FL404::getFl404bRespondentDob)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Respondent date of birth")
                    .mandatory(FL404::getFl404bRespondentAddress)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Respondent address")
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getAddressLine1)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getAddressLine2)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getAddressLine3)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getPostTown)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getCounty)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getPostCode)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bRespondentAddress)
                    .optional(Address::getCountry)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .mandatory(FL404::getFl404bAddressAppliedFor)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel("Address the order applies to")
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .mandatory(Address::getAddressLine1)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .optional(Address::getAddressLine2)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .optional(Address::getAddressLine3)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .optional(Address::getPostTown)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .optional(Address::getCounty)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .mandatory(Address::getPostCode)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .complex(FL404::getFl404bAddressAppliedFor)
                    .optional(Address::getCountry)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"").done()
                    .optional(FL404::getFl404bHearingOutcome)
                    .fieldShowCondition("createSelectOrderOptions=\"blank\" OR createSelectOrderOptions=\"amendDischargedVaried\"")
                    .eventLabel("Hearing outcome")
                    .mandatory(FL404::getFl404bPowerOfArrestParagraph)
                    .fieldShowCondition("createSelectOrderOptions=\"powerOfArrest\"")
                    .eventLabel("Paragraphs of the order to which the power of arrest applies")
                    .mandatory(FL404::getFl404bRiskOfSignificantHarm)
                    .fieldShowCondition("createSelectOrderOptions=\"powerOfArrest\"")
                    .eventLabel("Is there risk of significant harm to the applicant or children if ther power of arrest is not attached immediately?")
                    .mandatory(FL404::getFl404bMentionedProperty)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel("Does the order mention a property?")
                    .mandatory(FL404::getFl404bAddressOfProperty)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" AND fl404CustomFields.fl404bMentionedProperty=\"Yes\"")
                    .eventLabel("Add the address of the property")
                    .optional(FL404::getFl404bRespondentNotToThreat)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel("Select any that apply")
                    .optional(FL404::getFl404bRespondentNotIntimidate)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToTelephone)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bAddMoreDetailsTelephone)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" AND fl404CustomFields.fl404bRespondentNotToTelephone=\"respondentMustNotTelephone\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToDamageOrThreat)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToDamage)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToEnterProperty)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bAddMoreDetailsProperty)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentNotToEnterProperty=\"respondentMustNotEnter\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToThreatChild)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotHarassOrIntimidate)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToTelephoneChild)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bAddMoreDetailsPhoneChild)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" AND fl404CustomFields.fl404bRespondentNotToTelephoneChild=\"respondentMustNotTelephoneChild\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentNotToEnterSchool)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bAddSchool)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" AND fl404CustomFields.fl404bRespondentNotToEnterSchool=\"respondentMustNotEnterSchool\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bAddMoreDetailsSchool)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" AND fl404CustomFields.fl404bRespondentNotToEnterSchool=\"respondentMustNotEnterSchool\"")
                    .eventLabel(" ")
                    .optional(FL404::getAddDirections)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .complex(FL404::getAddDirections, DirectionDetails.class)
                    .mandatory(DirectionDetails::getDirectionText)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"").done()
                    .complex(FL404::getAddDirections, DirectionDetails.class)
                    .optional(DirectionDetails::getIsBold)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"").done()
                    .mandatory(FL404::getOrderEndDateAndTimeOptions)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ")
                    .optional(FL404::getOrderSpecifiedDateTime)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" AND fl404CustomFields.orderEndDateAndTimeOptions=\"specifiedDateAndTime\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bApplicantIsEntitledToOccupy)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bApplicantHasHomeRight)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bApplicantHomeInstruction)
                    .fieldShowCondition("fl404CustomFields.fl404bApplicantHasHomeRight=\"rightsInAddress\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bApplicantHasRightToEnter)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bApplicantHasOtherInstruction)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bApplicantOtherInstruction)
                    .fieldShowCondition("fl404CustomFields.fl404bApplicantHasOtherInstruction=\"other1\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bApplicantAllowedToOccupy)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bIsPowerOfArrest1)
                    .fieldShowCondition("fl404CustomFields.fl404bApplicantAllowedToOccupy=\"allowApplicantToOccupy\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentMustNotOccupyAddress)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bOccupationDate1)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotOccupyAddress=\"mustNotOccupyAddress\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bOccupationTime1)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotOccupyAddress=\"DO_NOT_SHOW\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bOccupationDate2)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotOccupyAddress=\"mustNotOccupyAddress\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bOccupationTime2)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotOccupyAddress=\"DO_NOT_SHOW\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bIsPowerOfArrest2)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotOccupyAddress=\"mustNotOccupyAddress\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentShallLeaveAddress)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bWhenRespondentShallLeave)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentShallLeaveAddress=\"shallLeaveAddress\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bIsPowerOfArrest3)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentShallLeaveAddress=\"shallLeaveAddress\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentMustNotEnterAddress)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bAddMoreDetails)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotEnterAddress=\"attemptToEnterAddress\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bIsPowerOfArrest4)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentMustNotEnterAddress=\"attemptToEnterAddress\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentObstructOrHarass)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bIsPowerOfArrest5)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentObstructOrHarass=\"obstructHarassOrInterfere\"")
                    .eventLabel(" ")
                    .optional(FL404::getFl404bRespondentOtherInstructions)
                    .fieldShowCondition("createSelectOrderOptions=\"occupation\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bAddAnotherInstructions)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentOtherInstructions=\"other2\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bIsPowerOfArrest6)
                    .fieldShowCondition("fl404CustomFields.fl404bRespondentOtherInstructions=\"other2\"")
                    .eventLabel(" ")
                    .mandatory(FL404::getFl404bDateOrderMade)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Date order made")
                    .mandatory(FL404::getFl404bDateOrderEnd)
                    .fieldShowCondition("createSelectOrderOptions=\"powerOfArrest\" OR createSelectOrderOptions=\"occupation\"")
                    .eventLabel("Date order ends and time")
                    .mandatory(FL404::getFl404bDateOrderEndTime)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Time")
                    .optional(FL404::getFl404bTimeEstimate)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Time estimate")
                    .optional(FL404::getFl404bCourtName1)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Court name for hearing")
                    .optional(FL404::getFl404bOtherCourtAddress)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"")
                    .eventLabel("Court address for hearing")
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getAddressLine1)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getAddressLine2)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getAddressLine3)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getPostTown)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getCounty)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getPostCode)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .complex(FL404::getFl404bOtherCourtAddress)
                    .optional(Address::getCountry)
                    .fieldShowCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"").done()
                    .optional(FL404::getFl404bCostOfApplication)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" OR createSelectOrderOptions=\"occupation\"")
                    .eventLabel("Costs of this application")
                    .mandatory(FL404::getFl404bIsNoticeGiven)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\" OR createSelectOrderOptions=\"occupation\"")
                    .eventLabel("Is this order made with or without notice?").done().done();
        fields.complex(CaseData::getFl404SchoolDirections_Details, SchoolDirectionsDetails.class)
                    .optional(SchoolDirectionsDetails::getFl404SchoolDirections_DetailsComplex)
                    .fieldShowCondition("createSelectOrderOptions=\"nonMolestation\"")
                    .eventLabel(" ").done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .complex(StandardDirectionOrder::getSdoPartiesRaisedAbuseCollection, PartyNameDA.class)
                    .mandatory(PartyNameDA::getPartyName).done().done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .complex(StandardDirectionOrder::getSdoInterpreterDialectRequired, SdoLanguageDialect.class)
                    .mandatory(SdoLanguageDialect::getInterpreterNeedFor)
                    .mandatory(SdoLanguageDialect::getLanguageOrDialect).done().done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .complex(StandardDirectionOrder::getSdoDisclosureOfPapersCaseNumbers, SdoDisclosureOfPapersCaseNumber.class)
                    .mandatory(SdoDisclosureOfPapersCaseNumber::getCaseNumber).done().done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .complex(StandardDirectionOrder::getSdoMiamAttendingPerson, MiamAttendingPersonName.class)
                    .mandatory(MiamAttendingPersonName::getMiamAttendingPersonName).done().done();
    }
}
