package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage21;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditAndApproveAnOrderPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code editAndApproveAnOrder} for case type {@code PRLAPPS}.
 */
@Component
public class EditAndApproveAnOrder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EDIT_AND_APPROVE_AN_ORDER = "editAndApproveAnOrder";

    /**
     * Registers event {@code editAndApproveAnOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(EDIT_AND_APPROVE_AN_ORDER)
            .forAllStates()
            .name("Edit and approve a draft order")
            .displayOrder(30)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.HEARING_CENTRE_TEAM_LEADER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .fields();
        EditAndApproveAnOrderPage10.apply(fields);
        EditAndApproveAnOrderPage11.apply(fields);
        EditAndApproveAnOrderPage13.apply(fields);
        EditAndApproveAnOrderPage14.apply(fields);
        EditAndApproveAnOrderPage15.apply(fields);
        EditAndApproveAnOrderPage16.apply(fields);
        EditAndApproveAnOrderPage17.apply(fields);
        EditAndApproveAnOrderPage2.apply(fields);
        EditAndApproveAnOrderPage20.apply(fields);
        EditAndApproveAnOrderPage21.apply(fields);
        EditAndApproveAnOrderPage5.apply(fields);
        EditAndApproveAnOrderPage6.apply(fields);
        EditAndApproveAnOrderPage7.apply(fields);
        EditAndApproveAnOrderPage8.apply(fields);
        EditAndApproveAnOrderPage9.apply(fields);
    }
}
