package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage12;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.EditReturnedOrderNonprodPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code editReturnedOrder} for case type {@code PRLAPPS}.
 */
@Component
public class EditReturnedOrderNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EDIT_RETURNED_ORDER = "editReturnedOrder";

    /**
     * Registers overlay event {@code editReturnedOrder} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(EDIT_RETURNED_ORDER)
            .forStates(State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Edit a returned order")
            .description("Event to edit order returned by Judge or manager")
            .displayOrder(50)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.C100_APPLICANTBARRISTER1, UserRole.C100_APPLICANTBARRISTER2, UserRole.C100_APPLICANTBARRISTER3, UserRole.C100_APPLICANTBARRISTER4, UserRole.C100_APPLICANTBARRISTER5, UserRole.C100_APPLICANTSOLICITOR1, UserRole.C100_APPLICANTSOLICITOR2, UserRole.C100_APPLICANTSOLICITOR3, UserRole.C100_APPLICANTSOLICITOR4, UserRole.C100_APPLICANTSOLICITOR5, UserRole.C100_RESPONDENTBARRISTER1, UserRole.C100_RESPONDENTBARRISTER2, UserRole.C100_RESPONDENTBARRISTER3, UserRole.C100_RESPONDENTBARRISTER4, UserRole.C100_RESPONDENTBARRISTER5, UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CREATOR, UserRole.FL401_APPLICANTBARRISTER, UserRole.FL401_APPLICANTSOLICITOR, UserRole.FL401_RESPONDENTBARRISTER, UserRole.FL401_RESPONDENTSOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .fields();
        EditReturnedOrderNonprodPage1.apply(fields);
        EditReturnedOrderNonprodPage10.apply(fields);
        EditReturnedOrderNonprodPage11.apply(fields);
        EditReturnedOrderNonprodPage12.apply(fields);
        EditReturnedOrderNonprodPage13.apply(fields);
        EditReturnedOrderNonprodPage2.apply(fields);
        EditReturnedOrderNonprodPage3.apply(fields);
        EditReturnedOrderNonprodPage5.apply(fields);
        EditReturnedOrderNonprodPage6.apply(fields);
        EditReturnedOrderNonprodPage7.apply(fields);
        EditReturnedOrderNonprodPage8.apply(fields);
        EditReturnedOrderNonprodPage9.apply(fields);
    }
}
