package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code enableUpdateHearingActualTask} for case type {@code PRLAPPS}.
 */
@Component
public class EnableUpdateHearingActualTask implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENABLE_UPDATE_HEARING_ACTUAL_TASK = "enableUpdateHearingActualTask";

    /**
     * Registers event {@code enableUpdateHearingActualTask}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(ENABLE_UPDATE_HEARING_ACTUAL_TASK)
            .forAllStates()
            .name("WA update hearing actual task")
            .description("WA Event trigger for update hearing actual task")
            .displayOrder(38)
            .showCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        fields.page("1");
        fields.optionalNoSummary(CaseData::getNextHearingDate)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("nextHearingDate=\"DO_NOT_SHOW\"");
    }
}
