package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code exitAwaitingInformation} for case type {@code PRLAPPS}.
 */
@Component
public class ExitAwaitingInformation implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EXIT_AWAITING_INFORMATION = "exitAwaitingInformation";

    /**
     * Registers event {@code exitAwaitingInformation}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(EXIT_AWAITING_INFORMATION)
            .forState(State.AWAITING_INFORMATION)
            .name("Exit Awaiting Information")
            .description("Move case out of Awaiting Information state")
            .displayOrder(52)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CTSC_TEAM_LEADER)
            .grant(Set.of(Permission.R), UserRole.APPLICANTSOLICITOR, UserRole.C100_APPLICANTSOLICITOR1, UserRole.C100_APPLICANTSOLICITOR2, UserRole.C100_APPLICANTSOLICITOR3, UserRole.C100_APPLICANTSOLICITOR4, UserRole.C100_APPLICANTSOLICITOR5, UserRole.C100_RESPONDENTBARRISTER1, UserRole.C100_RESPONDENTBARRISTER2, UserRole.C100_RESPONDENTBARRISTER3, UserRole.C100_RESPONDENTBARRISTER4, UserRole.C100_RESPONDENTBARRISTER5, UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.CASEWORKER_PRIVATELAW_CAFCASS, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.FL401_APPLICANTBARRISTER, UserRole.FL401_APPLICANTSOLICITOR, UserRole.FL401_RESPONDENTBARRISTER, UserRole.FL401_RESPONDENTSOLICITOR, UserRole.HEARING_CENTRE_TEAM_LEADER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .optional(CaseDataExtra::getExitAwaitingInformationDetails)
                    .publish(false).done();
    }
}
