package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.Fl401StatementOfTruthAndSubmitPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.Fl401StatementOfTruthAndSubmitPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.Fl401StatementOfTruthAndSubmitPage3;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code fl401StatementOfTruthAndSubmit} for case type {@code PRLAPPS}.
 */
@Component
public class Fl401StatementOfTruthAndSubmit implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FL401_STATEMENT_OF_TRUTH_AND_SUBMIT = "fl401StatementOfTruthAndSubmit";

    /**
     * Registers event {@code fl401StatementOfTruthAndSubmit}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FL401_STATEMENT_OF_TRUTH_AND_SUBMIT)
            .forStateTransition(State.AWAITING_SUBMISSION_TO_HMCTS, State.PROCEEDS_IN_HERITAGE_SYSTEM)
            .name("Statement of Truth and submit")
            .displayOrder(106)
            .showCondition("caseTypeOfApplication=\"FL401\"")
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .ttlIncrement(36524)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        Fl401StatementOfTruthAndSubmitPage1.apply(fields);
        Fl401StatementOfTruthAndSubmitPage2.apply(fields);
        Fl401StatementOfTruthAndSubmitPage3.apply(fields);
    }
}
