package uk.gov.hmcts.reform.prl.ccd.event;
import uk.gov.hmcts.reform.prl.models.complextypes.ApplicantFamilyDetails;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.FL401ApplicantChildDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code fl401AmendApplicantFamilyDetails} for case type {@code PRLAPPS}.
 */
@Component
public class Fl401AmendApplicantFamilyDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FL401_AMEND_APPLICANT_FAMILY_DETAILS = "fl401AmendApplicantFamilyDetails";

    /**
     * Registers event {@code fl401AmendApplicantFamilyDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FL401_AMEND_APPLICANT_FAMILY_DETAILS)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Amend applicant’s family")
            .description("Amend Details of the Applicant’s family")
            .displayOrder(7)
            .showCondition("caseTypeOfApplication=\"FL401\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSubmissionRequiredFieldsInfo1).done();
        fields.complex(CaseData::getApplicantFamilyDetails)
                    .mandatory(ApplicantFamilyDetails::getDoesApplicantHaveChildren).done();
        fields.complex(CaseData::getApplicantChildDetails).done()
                    .fieldShowCondition("applicantFamilyDetails.doesApplicantHaveChildren = \"Yes\"");
        fields.complex(CaseData::getApplicantChildDetails, FL401ApplicantChildDetails.class)
                    .optional(FL401ApplicantChildDetails::getFullName)
                    .optional(FL401ApplicantChildDetails::getDateOfBirth)
                    .optional(FL401ApplicantChildDetails::getApplicantChildRelationship)
                    .optional(FL401ApplicantChildDetails::getApplicantRespondentShareParental)
                    .optional(FL401ApplicantChildDetails::getRespondentChildRelationship).done();
    }
}
