package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.Address;
import uk.gov.hmcts.reform.prl.models.complextypes.ChildrenLiveAtAddress;
import uk.gov.hmcts.reform.prl.models.complextypes.Home;
import uk.gov.hmcts.reform.prl.models.complextypes.Landlord;
import uk.gov.hmcts.reform.prl.models.complextypes.Mortgage;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code fl401Home} for case type {@code PRLAPPS}.
 */
@Component
public class Fl401Home implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FL401_HOME = "fl401Home";

    /**
     * Registers event {@code fl401Home}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FL401_HOME)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("The home")
            .description("Home situation")
            .displayOrder(12)
            .showCondition("caseTypeOfApplication=\"FL401\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.readonlyNoSummary(CaseData::getSubmissionRequiredFieldsInfo1);
        fields.complex(CaseData::getHome)
                    .optional(Home::getAddressLabel)
                    .optional(Home::getAddress)
                    .complex(Home::getAddress)
                    .optional(Address::getAddressLine1).done()
                    .complex(Home::getAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(Home::getAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(Home::getAddress)
                    .optional(Address::getPostTown).done()
                    .complex(Home::getAddress)
                    .optional(Address::getCounty).done()
                    .complex(Home::getAddress)
                    .optional(Address::getPostCode).done()
                    .complex(Home::getAddress)
                    .optional(Address::getCountry).done()
                    .optional(Home::getPeopleLivingAtThisAddress)
                    .optional(Home::getTextAreaSomethingElse)
                    .optional(Home::getEverLivedAtTheAddress)
                    .optional(Home::getIntendToLiveAtTheAddress)
                    .optional(Home::getDoAnyChildrenLiveAtAddress)
                    .complexMember(Home::getChildren)
                    .complex(Home::getChildren, ChildrenLiveAtAddress.class)
                    .optional(ChildrenLiveAtAddress::getKeepChildrenInfoConfidential).done()
                    .complex(Home::getChildren, ChildrenLiveAtAddress.class)
                    .optional(ChildrenLiveAtAddress::getChildFullName).done()
                    .complex(Home::getChildren, ChildrenLiveAtAddress.class)
                    .optional(ChildrenLiveAtAddress::getChildsAge).done()
                    .complex(Home::getChildren, ChildrenLiveAtAddress.class)
                    .optional(ChildrenLiveAtAddress::getIsRespondentResponsibleForChild).done()
                    .optional(Home::getIsPropertyAdapted)
                    .optional(Home::getHowIsThePropertyAdapted)
                    .optional(Home::getIsThereMortgageOnProperty)
                    .complexMember(Home::getMortgages)
                    .complex(Home::getMortgages)
                    .optional(Mortgage::getMortgageNamedAfter).done()
                    .complex(Home::getMortgages)
                    .optional(Mortgage::getTextAreaSomethingElse).done()
                    .complex(Home::getMortgages)
                    .optional(Mortgage::getMortgageNumber).done()
                    .complex(Home::getMortgages)
                    .optional(Mortgage::getMortgageLenderName).done()
                    .complex(Home::getMortgages)
                    .optional(Mortgage::getAddress).done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getAddressLine1).done().done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getAddressLine2).done().done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getAddressLine3).done().done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getPostTown).done().done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getCounty).done().done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getPostCode).done().done()
                    .complex(Home::getMortgages)
                    .complex(Mortgage::getAddress)
                    .optional(Address::getCountry).done().done()
                    .optional(Home::getIsPropertyRented)
                    .complexMember(Home::getLandlords)
                    .complex(Home::getLandlords)
                    .optional(Landlord::getMortgageNamedAfterList).done()
                    .complex(Home::getLandlords)
                    .optional(Landlord::getTextAreaSomethingElse).done()
                    .complex(Home::getLandlords)
                    .optional(Landlord::getLandlordName).done()
                    .complex(Home::getLandlords)
                    .optional(Landlord::getAddress).done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getAddressLine1).done().done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getAddressLine2).done().done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getAddressLine3).done().done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getPostTown).done().done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getCounty).done().done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getPostCode).done().done()
                    .complex(Home::getLandlords)
                    .complex(Landlord::getAddress)
                    .optional(Address::getCountry).done().done()
                    .optional(Home::getDoesApplicantHaveHomeRights)
                    .optional(Home::getLivingSituation)
                    .optional(Home::getFamilyHome)
                    .optional(Home::getFurtherInformation).done();
    }
}
