package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.caseflags.AllPartyFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ReviewRaRequestWrapper;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code fl401CreateFlags} for case type {@code PRLAPPS}.
 */
@Component
public class Fl401CreateFlags implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FL401_CREATE_FLAGS = "fl401CreateFlags";

    /**
     * Registers event {@code fl401CreateFlags}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(FL401_CREATE_FLAGS)
            .forAllStates()
            .name("Create case flag")
            .displayOrder(27)
            .showCondition("caseTypeOfApplication=\"FL401\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .mandatory(CaseDataExtra::getFlagLauncherInternal)
                    .displayContextParameter("#ARGUMENT(CREATE,VERSION2.1)").done();
        fields.optional(CaseData::getCaseFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getAllPartyFlags)
                    .optional(AllPartyFlags::getDaApplicantInternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaApplicantSolicitorInternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaApplicantBarristerInternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaRespondentInternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaRespondentSolicitorInternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaRespondentBarristerInternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaRespondentBarristerExternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaApplicantExternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaApplicantSolicitorExternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaApplicantBarristerExternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaRespondentExternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue()
                    .optional(AllPartyFlags::getDaRespondentSolicitorExternalFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue().done();
        fields.complex(CaseData::getReviewRaRequestWrapper)
                    .optional(ReviewRaRequestWrapper::getSelectedFlags)
                    .fieldShowCondition("flagLauncherInternal=\"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .retainHiddenValue().done();
    }
}
