package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage21;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage22;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage23;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.HearingEditAndApproveAnOrderPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code hearingEditAndApproveAnOrder} for case type {@code PRLAPPS}.
 */
@Component
public class HearingEditAndApproveAnOrder implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HEARING_EDIT_AND_APPROVE_AN_ORDER = "hearingEditAndApproveAnOrder";

    /**
     * Registers event {@code hearingEditAndApproveAnOrder}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(HEARING_EDIT_AND_APPROVE_AN_ORDER)
            .forStateTransition(EnumSet.of(State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION), State.ALL_FINAL_ORDERS_ISSUED)
            .name("Edit and serve an order")
            .displayOrder(31)
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .fields();
        HearingEditAndApproveAnOrderPage1.apply(fields);
        HearingEditAndApproveAnOrderPage10.apply(fields);
        HearingEditAndApproveAnOrderPage11.apply(fields);
        HearingEditAndApproveAnOrderPage13.apply(fields);
        HearingEditAndApproveAnOrderPage14.apply(fields);
        HearingEditAndApproveAnOrderPage15.apply(fields);
        HearingEditAndApproveAnOrderPage16.apply(fields);
        HearingEditAndApproveAnOrderPage17.apply(fields);
        HearingEditAndApproveAnOrderPage2.apply(fields);
        HearingEditAndApproveAnOrderPage20.apply(fields);
        HearingEditAndApproveAnOrderPage21.apply(fields);
        HearingEditAndApproveAnOrderPage22.apply(fields);
        HearingEditAndApproveAnOrderPage23.apply(fields);
        HearingEditAndApproveAnOrderPage4.apply(fields);
        HearingEditAndApproveAnOrderPage5.apply(fields);
        HearingEditAndApproveAnOrderPage6.apply(fields);
        HearingEditAndApproveAnOrderPage7.apply(fields);
        HearingEditAndApproveAnOrderPage8.apply(fields);
        HearingEditAndApproveAnOrderPage9.apply(fields);
    }
}
