package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code hmcHearingCompleted} for case type {@code PRLAPPS}.
 */
@Component
public class HmcHearingCompleted implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HMC_HEARING_COMPLETED = "hmcHearingCompleted";

    /**
     * Registers event {@code hmcHearingCompleted}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(HMC_HEARING_COMPLETED)
            .forAllStates()
            .name("WA complete hearing actuals")
            .description("WA Event trigger for completing update hearing actuals task")
            .displayOrder(38)
            .showCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
    }
}
