package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code hwfProcessCaseUpdate} for case type {@code PRLAPPS}.
 */
@Component
public class HwfProcessCaseUpdate implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HWF_PROCESS_CASE_UPDATE = "hwfProcessCaseUpdate";

    /**
     * Registers event {@code hwfProcessCaseUpdate}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(HWF_PROCESS_CASE_UPDATE)
            .forStateTransition(EnumSet.of(State.SUBMITTED_NOT_PAID, State.AWAITING_INFORMATION), State.SUBMITTED_PAID)
            .name("Process HWF for Citizen case")
            .showCondition("caseTypeOfApplication=\"C100\"")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
    }
}
