package uk.gov.hmcts.reform.prl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code internal-custom-order-submit} for case type {@code PRLAPPS}.
 */
@Component
public class InternalCustomOrderSubmit implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INTERNAL_CUSTOM_ORDER_SUBMIT = "internal-custom-order-submit";

    /**
     * Registers event {@code internal-custom-order-submit}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(INTERNAL_CUSTOM_ORDER_SUBMIT)
            .forAllStates()
            .name("Internal Custom Order Submit")
            .description("Internal event for submitting custom orders without callbacks")
            .displayOrder(200)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
    }
}
