package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code internal-update-all-tabs} for case type {@code PRLAPPS}.
 */
@Component
public class InternalUpdateAllTabs implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INTERNAL_UPDATE_ALL_TABS = "internal-update-all-tabs";

    /**
     * Registers event {@code internal-update-all-tabs}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(INTERNAL_UPDATE_ALL_TABS)
            .forAllStates()
            .name("Update All tabs")
            .displayOrder(56)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
    }
}
