package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code keepYourDetailsPrivate} for case type {@code PRLAPPS}.
 */
@Component
public class KeepYourDetailsPrivate implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String KEEP_YOUR_DETAILS_PRIVATE = "keepYourDetailsPrivate";

    /**
     * Registers event {@code keepYourDetailsPrivate}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(KEEP_YOUR_DETAILS_PRIVATE)
            .forAllStates()
            .name("Keep your details Private")
            .description("Citizen confirming confidentiality")
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .mandatory(CaseDataExtra::getOtherPeopleKnowYourContactDetails)
                    .mandatory(CaseDataExtra::getConfidentiality)
                    .mandatoryNoSummary(CaseDataExtra::getConfidentialityList).done();
    }
}
