package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.ListOnNoticePage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.ListOnNoticePage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.ListOnNoticePage3;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code listOnNotice} for case type {@code PRLAPPS}.
 */
@Component
public class ListOnNotice implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String LIST_ON_NOTICE = "listOnNotice";

    /**
     * Registers event {@code listOnNotice}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(LIST_ON_NOTICE)
            .forState(State.JUDICIAL_REVIEW)
            .name("List on notice")
            .displayOrder(35)
            .showCondition("caseTypeOfApplication=\"C100\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION)
            .fields();
        ListOnNoticePage1.apply(fields);
        ListOnNoticePage2.apply(fields);
        ListOnNoticePage3.apply(fields);
    }
}
