package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage102;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage12;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage18;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage19;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage21;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage22;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage23;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage24;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage25;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage26;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage27;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage28;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage30;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.ManageOrdersPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code manageOrders} for case type {@code PRLAPPS}.
 */
@Component
public class ManageOrders implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_ORDERS = "manageOrders";

    /**
     * Registers event {@code manageOrders}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_ORDERS)
            .forStateTransition(EnumSet.of(State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.ALL_FINAL_ORDERS_ISSUED, State.CASE_WITHDRAWN, State.DECISION_OUTCOME, State.AWAITING_INFORMATION), State.ALL_FINAL_ORDERS_ISSUED)
            .name("Manage orders")
            .displayOrder(40)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .fields();
        ManageOrdersPage1.apply(fields);
        ManageOrdersPage10.apply(fields);
        ManageOrdersPage11.apply(fields);
        ManageOrdersPage12.apply(fields);
        ManageOrdersPage13.apply(fields);
        ManageOrdersPage14.apply(fields);
        ManageOrdersPage2.apply(fields);
        ManageOrdersPage102.apply(fields);
        ManageOrdersPage20.apply(fields);
        ManageOrdersPage21.apply(fields);
        ManageOrdersPage22.apply(fields);
        ManageOrdersPage23.apply(fields);
        ManageOrdersPage24.apply(fields);
        ManageOrdersPage25.apply(fields);
        ManageOrdersPage26.apply(fields);
        ManageOrdersPage27.apply(fields);
        ManageOrdersPage28.apply(fields);
        ManageOrdersPage3.apply(fields);
        ManageOrdersPage30.apply(fields);
        ManageOrdersPage4.apply(fields);
        ManageOrdersPage5.apply(fields);
        ManageOrdersPage6.apply(fields);
        ManageOrdersPage7.apply(fields);
        ManageOrdersPage8.apply(fields);
        ManageOrdersPage9.apply(fields);
        ManageOrdersPage15.apply(fields);
        ManageOrdersPage16.apply(fields);
        ManageOrdersPage17.apply(fields);
        ManageOrdersPage18.apply(fields);
        ManageOrdersPage19.apply(fields);
    }
}
