package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ChildrenNotInTheCase;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code otherChildNotInTheCase} for case type {@code PRLAPPS}.
 */
@Component
public class OtherChildNotInTheCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String OTHER_CHILD_NOT_IN_THE_CASE = "otherChildNotInTheCase";

    /**
     * Registers event {@code otherChildNotInTheCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(OTHER_CHILD_NOT_IN_THE_CASE)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Other children not in the case")
            .description("Other children not part of this application but related to the case")
            .displayOrder(11)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSubmissionRequiredFieldsInfo1).done();
        fields.mandatory(CaseData::getChildrenNotPartInTheCaseYesNo);
        fields.complex(CaseData::getChildrenNotInTheCase).done()
                    .fieldShowCondition("childrenNotPartInTheCaseYesNo=\"Yes\"");
        fields.complex(CaseData::getChildrenNotInTheCase, ChildrenNotInTheCase.class)
                    .mandatory(ChildrenNotInTheCase::getFirstName)
                    .mandatory(ChildrenNotInTheCase::getLastName)
                    .mandatory(ChildrenNotInTheCase::getGender)
                    .optional(ChildrenNotInTheCase::getOtherGender)
                    .fieldShowCondition("childrenNotInTheCase.gender=\"other\"")
                    .mandatory(ChildrenNotInTheCase::getIsDateOfBirthKnown)
                    .mandatory(ChildrenNotInTheCase::getDateOfBirth)
                    .fieldShowCondition("childrenNotInTheCase.isDateOfBirthKnown=\"Yes\"")
                    .noHintText().done();
    }
}
