package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code otherPeopleInTheCase} for case type {@code PRLAPPS}.
 */
@Component
public class OtherPeopleInTheCase implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String OTHER_PEOPLE_IN_THE_CASE = "otherPeopleInTheCase";

    /**
     * Registers event {@code otherPeopleInTheCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(OTHER_PEOPLE_IN_THE_CASE)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Other people in the case")
            .displayOrder(10)
            .showCondition("caseTypeOfApplication=\"C100\" AND taskListVersion!=\"v2\" AND taskListVersion!=\"v3\"")
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSubmissionRequiredFieldsInfo1).done();
        fields.complex(CaseData::getOthersToNotify).done();
    }
}
