package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code pcqUpdateForCitizen} for case type {@code PRLAPPS}.
 */
@Component
public class PcqUpdateForCitizen implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PCQ_UPDATE_FOR_CITIZEN = "pcqUpdateForCitizen";

    /**
     * Registers event {@code pcqUpdateForCitizen}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.event(PCQ_UPDATE_FOR_CITIZEN)
            .forAllStates()
            .name("Update pcq for citizen")
            .description("Event to update pcq id of citizen in case data")
            .displayOrder(143)
            .showCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
    }
}
