package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.ProcessUrgentHelpWithFeesPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.ProcessUrgentHelpWithFeesPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.ProcessUrgentHelpWithFeesPage3;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code processUrgentHelpWithFees} for case type {@code PRLAPPS}.
 */
@Component
public class ProcessUrgentHelpWithFees implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PROCESS_URGENT_HELP_WITH_FEES = "processUrgentHelpWithFees";

    /**
     * Registers event {@code processUrgentHelpWithFees}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(PROCESS_URGENT_HELP_WITH_FEES)
            .forStateTransition(EnumSet.of(State.SUBMITTED_NOT_PAID, State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.CASE_WITHDRAWN, State.ALL_FINAL_ORDERS_ISSUED, State.AWAITING_RESUBMISSION_TO_HMCTS, State.AWAITING_INFORMATION), State.SUBMITTED_PAID)
            .name("Process urgent help with fees")
            .displayOrder(144)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .ttlIncrement(36524)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.CITIZEN)
            .fields();
        ProcessUrgentHelpWithFeesPage1.apply(fields);
        ProcessUrgentHelpWithFeesPage2.apply(fields);
        ProcessUrgentHelpWithFeesPage3.apply(fields);
    }
}
