package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code respondentBehaviour} for case type {@code PRLAPPS}.
 */
@Component
public class RespondentBehaviour implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RESPONDENT_BEHAVIOUR = "respondentBehaviour";

    /**
     * Registers event {@code respondentBehaviour}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(RESPONDENT_BEHAVIOUR)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Respondent's behaviour")
            .displayOrder(11)
            .showCondition("caseTypeOfApplication=\"FL401\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSubmissionRequiredFieldsInfo1).done();
        fields.complex(CaseData::getRespondentBehaviourData)
                    .optional(uk.gov.hmcts.reform.prl.models.complextypes.RespondentBehaviour::getApplicantWantToStopFromRespondentDoing)
                    .optional(uk.gov.hmcts.reform.prl.models.complextypes.RespondentBehaviour::getApplicantWantToStopFromRespondentDoingToChild)
                    .optional(uk.gov.hmcts.reform.prl.models.complextypes.RespondentBehaviour::getOtherReasonApplicantWantToStopFromRespondentDoing).done();
    }
}
