package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.ServiceOfDocumentsProdPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.ServiceOfDocumentsProdPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.ServiceOfDocumentsProdPage3;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code serviceOfDocuments} for case type {@code PRLAPPS}.
 */
@Component
public class ServiceOfDocumentsProd implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SERVICE_OF_DOCUMENTS = "serviceOfDocuments";

    /**
     * Registers overlay event {@code serviceOfDocuments} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(SERVICE_OF_DOCUMENTS)
            .forStates(State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Service of documents")
            .description("Event to serve the documents to the parties")
            .displayOrder(50)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .fields();
        ServiceOfDocumentsProdPage1.apply(fields);
        ServiceOfDocumentsProdPage2.apply(fields);
        ServiceOfDocumentsProdPage3.apply(fields);
    }
}
