package uk.gov.hmcts.reform.prl.ccd.event;
import uk.gov.hmcts.reform.prl.models.Organisation;
import uk.gov.hmcts.reform.prl.models.dto.barrister.AllocatedBarrister;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code solicitorAddBarrister} for case type {@code PRLAPPS}.
 */
@Component
public class SolicitorAddBarrister implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SOLICITOR_ADD_BARRISTER = "solicitorAddBarrister";

    /**
     * Registers event {@code solicitorAddBarrister}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(SOLICITOR_ADD_BARRISTER)
            .forStates(State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.ALL_FINAL_ORDERS_ISSUED, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Add barrister")
            .description("Solicitor add barrister")
            .displayOrder(201)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.C100_APPLICANTSOLICITOR1, UserRole.C100_APPLICANTSOLICITOR2, UserRole.C100_APPLICANTSOLICITOR3, UserRole.C100_APPLICANTSOLICITOR4, UserRole.C100_APPLICANTSOLICITOR5, UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.FL401_APPLICANTSOLICITOR, UserRole.FL401_RESPONDENTSOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.HEARING_CENTRE_TEAM_LEADER)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getAllocatedBarrister)
                    .mandatory(AllocatedBarrister::getPartyList)
                    .eventLabel("For which party do you want to add a barrister?")
                    .mandatory(AllocatedBarrister::getBarristerFirstName)
                    .eventLabel("First names of the barrister")
                    .mandatory(AllocatedBarrister::getBarristerLastName)
                    .eventLabel("Last name of the barrister")
                    .mandatory(AllocatedBarrister::getBarristerEmail)
                    .eventLabel("Email address of the barrister")
                    .mandatory(AllocatedBarrister::getBarristerOrg)
                    .complex(AllocatedBarrister::getBarristerOrg)
                    .mandatory(Organisation::getOrganisationID)
                    .eventLabel("Barrister organisation Id").done()
                    .complex(AllocatedBarrister::getBarristerOrg)
                    .mandatory(Organisation::getOrganisationName)
                    .eventLabel("Barrister organisation name").done().done();
    }
}
