package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code statementOfService} for case type {@code PRLAPPS}.
 */
@Component
public class StatementOfService implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String STATEMENT_OF_SERVICE = "statementOfService";

    /**
     * Registers event {@code statementOfService}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(STATEMENT_OF_SERVICE)
            .forStates(State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME)
            .name("Statement of service")
            .description("Event to provide personal service to the parties")
            .displayOrder(63)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.C100_APPLICANTSOLICITOR1, UserRole.C100_APPLICANTSOLICITOR2, UserRole.C100_APPLICANTSOLICITOR3, UserRole.C100_APPLICANTSOLICITOR4, UserRole.C100_APPLICANTSOLICITOR5, UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CREATOR, UserRole.FL401_APPLICANTSOLICITOR, UserRole.FL401_RESPONDENTSOLICITOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getStatementOfService)
                    .mandatory(uk.gov.hmcts.reform.prl.models.serviceofapplication.StatementOfService::getStmtOfServiceWhatWasServed)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getStmtOfServiceAddRecipientLabel)
                    .publish(false).done();
        fields.complex(CaseData::getStatementOfService)
                    .optional(uk.gov.hmcts.reform.prl.models.serviceofapplication.StatementOfService::getStmtOfServiceAddRecipient)
                    .publish(false).done();
    }
}
