package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code testingSupportPaymentSuccessCallback} for case type {@code PRLAPPS}.
 */
@Component
public class TestingSupportPaymentSuccessCallbackNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TESTING_SUPPORT_PAYMENT_SUCCESS_CALLBACK = "testingSupportPaymentSuccessCallback";

    /**
     * Registers overlay event {@code testingSupportPaymentSuccessCallback} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(TESTING_SUPPORT_PAYMENT_SUCCESS_CALLBACK)
            .forState(State.SUBMITTED_NOT_PAID)
            .name("Dummy Payment confirmation")
            .displayOrder(29)
            .showCondition("caseTypeOfApplication=\"C100\"")
            .endButtonLabel("Make the payment")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN);
    }
}
