package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.TestingSupportDummySolicitorCreateNonprodPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.TestingSupportDummySolicitorCreateNonprodPage3;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code testingSupportDummySolicitorCreate} for case type {@code PRLAPPS}.
 */
@Component
public class TestingSupportDummySolicitorCreateNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TESTING_SUPPORT_DUMMY_SOLICITOR_CREATE = "testingSupportDummySolicitorCreate";

    /**
     * Registers overlay event {@code testingSupportDummySolicitorCreate} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(TESTING_SUPPORT_DUMMY_SOLICITOR_CREATE)
            .initialState(State.AWAITING_SUBMISSION_TO_HMCTS)
            .name("TS-Solicitor application")
            .description("Create an application via testing support")
            .displayOrder(108)
            .showSummary()
            .endButtonLabel("Create my dummy case")
            .ttlIncrement(28)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CITIZEN)
            .fields();
        TestingSupportDummySolicitorCreateNonprodPage2.apply(fields);
        TestingSupportDummySolicitorCreateNonprodPage3.apply(fields);
    }
}
