package uk.gov.hmcts.reform.prl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.EnvironmentFlags;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code testingSupportDummyCase} for case type {@code PRLAPPS}.
 */
@Component
public class TestingSupportDummyCaseNonprod implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TESTING_SUPPORT_DUMMY_CASE = "testingSupportDummyCase";

    /**
     * Registers overlay event {@code testingSupportDummyCase} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(TESTING_SUPPORT_DUMMY_CASE)
            .initialState(State.JUDICIAL_REVIEW)
            .name("Case created by Test support")
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .ttlIncrement(28)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
    }
}
