package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage4;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.uploadadditionalapplication.C2DocumentBundle;
import uk.gov.hmcts.reform.prl.models.complextypes.uploadadditionalapplication.OtherApplicationsBundle;
import uk.gov.hmcts.reform.prl.models.complextypes.uploadadditionalapplication.Supplement;
import uk.gov.hmcts.reform.prl.models.complextypes.uploadadditionalapplication.SupportingEvidenceBundle;
import uk.gov.hmcts.reform.prl.models.complextypes.uploadadditionalapplication.UploadApplicationDraftOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UploadAdditionalApplicationData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code uploadAdditionalApplications} for case type {@code PRLAPPS}.
 */
@Component
public class UploadAdditionalApplications implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_ADDITIONAL_APPLICATIONS = "uploadAdditionalApplications";

    /**
     * Registers event {@code uploadAdditionalApplications}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_ADDITIONAL_APPLICATIONS)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.CASE_WITHDRAWN, State.ALL_FINAL_ORDERS_ISSUED, State.AWAITING_RESUBMISSION_TO_HMCTS, State.AWAITING_INFORMATION)
            .name("Upload additional applications")
            .displayOrder(63)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.CITIZEN)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.C100_APPLICANTSOLICITOR1, UserRole.C100_APPLICANTSOLICITOR2, UserRole.C100_APPLICANTSOLICITOR3, UserRole.C100_APPLICANTSOLICITOR4, UserRole.C100_APPLICANTSOLICITOR5, UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.FL401_APPLICANTSOLICITOR, UserRole.FL401_RESPONDENTSOLICITOR)
            .fields();
        UploadAdditionalApplicationsPage1.apply(fields);
        UploadAdditionalApplicationsPage2.apply(fields);
        UploadAdditionalApplicationsPage3.apply(fields);
        UploadAdditionalApplicationsPage4.apply(fields);
        fields.complex(CaseData::getUploadAdditionalApplicationData)
                    .complexScope(UploadAdditionalApplicationData::getTemporaryC2Document)
                    .mandatory(C2DocumentBundle::getDocument)
                    .eventLabel("Upload C2 application")
                    .readonly(C2DocumentBundle::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>")
                    .mandatory(C2DocumentBundle::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case")
                    .mandatory(C2DocumentBundle::getCaReasonsForC2Application)
                    .fieldShowCondition("caseTypeOfApplication=\"C100\"")
                    .eventLabel("Are you using the C2 to apply for any of the below?")
                    .mandatory(C2DocumentBundle::getDaReasonsForC2Application)
                    .fieldShowCondition("caseTypeOfApplication=\"FL401\"")
                    .eventLabel("Are you using the C2 to apply for any of the below?")
                    .mandatory(C2DocumentBundle::getParentalResponsibilityType)
                    .fieldShowCondition("temporaryC2Document.caReasonsForC2Application CONTAINS \"PARENTAL_RESPONSIBILITY\"")
                    .eventLabel("Who's seeking parental responsibility?")
                    .optional(C2DocumentBundle::getHearingList)
                    .fieldShowCondition("temporaryC2Document.caReasonsForC2Application CONTAINS \"REQUESTING_ADJOURNMENT\" OR temporaryC2Document.daReasonsForC2Application CONTAINS \"REQUESTING_ADJOURNMENT\"")
                    .eventLabel("Which hearing are you requesting to be adjourned?")
                    .mandatory(C2DocumentBundle::getOtherReasonsFoC2Application)
                    .fieldShowCondition("temporaryC2Document.caReasonsForC2Application CONTAINS \"OTHER\" OR temporaryC2Document.daReasonsForC2Application CONTAINS \"OTHER\"")
                    .eventLabel("Other reasons for C2 Application")
                    .optional(C2DocumentBundle::getUrgencyTimeFrameType)
                    .eventLabel("Please state how soon you want the judge to consider your application?")
                    .optional(C2DocumentBundle::getSupplementsBundle)
                    .fieldShowCondition("caseTypeOfApplication=\"C100\"")
                    .eventLabel("Supplements")
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getName)
                    .eventLabel("Select supplement").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getSecureAccommodationType)
                    .fieldShowCondition("temporaryC2Document.supplementsBundle.name=\"C20_SECURE_ACCOMMODATION\"")
                    .eventLabel("Which jurisdiction?").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .optional(Supplement::getNotes).done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .readonly(Supplement::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>").done()
                    .complex(C2DocumentBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done()
                    .optional(C2DocumentBundle::getAdditionalDraftOrdersBundle)
                    .eventLabel("Draft Orders")
                    .complex(C2DocumentBundle::getAdditionalDraftOrdersBundle, UploadApplicationDraftOrder.class)
                    .mandatory(UploadApplicationDraftOrder::getTitle)
                    .eventLabel("File name").done()
                    .complex(C2DocumentBundle::getAdditionalDraftOrdersBundle, UploadApplicationDraftOrder.class)
                    .mandatory(UploadApplicationDraftOrder::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(C2DocumentBundle::getAdditionalDraftOrdersBundle, UploadApplicationDraftOrder.class)
                    .readonly(UploadApplicationDraftOrder::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>").done()
                    .complex(C2DocumentBundle::getAdditionalDraftOrdersBundle, UploadApplicationDraftOrder.class)
                    .mandatory(UploadApplicationDraftOrder::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done()
                    .optional(C2DocumentBundle::getSupportingEvidenceBundle)
                    .eventLabel("Supporting Documents")
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getName)
                    .eventLabel("File name").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .optional(SupportingEvidenceBundle::getNotes).done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .readonly(SupportingEvidenceBundle::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>").done()
                    .complex(C2DocumentBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done().done().done();
        fields.complex(CaseData::getUploadAdditionalApplicationData)
                    .complexScope(UploadAdditionalApplicationData::getTemporaryOtherApplicationsBundle)
                    .mandatory(OtherApplicationsBundle::getCaApplicantApplicationType)
                    .fieldShowCondition("representedPartyType=\"CAAPPLICANT\"")
                    .eventLabel("Select application")
                    .mandatory(OtherApplicationsBundle::getCaRespondentApplicationType)
                    .fieldShowCondition("representedPartyType=\"CARESPONDENT\"")
                    .eventLabel("Select application")
                    .mandatory(OtherApplicationsBundle::getDaApplicantApplicationType)
                    .fieldShowCondition("representedPartyType=\"DAAPPLICANT\"")
                    .eventLabel("Select application")
                    .mandatory(OtherApplicationsBundle::getDaRespondentApplicationType)
                    .fieldShowCondition("representedPartyType=\"DARESPONDENT\"")
                    .eventLabel("Select application")
                    .mandatory(OtherApplicationsBundle::getDocument)
                    .eventLabel("Upload application")
                    .readonly(OtherApplicationsBundle::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>")
                    .mandatory(OtherApplicationsBundle::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case")
                    .optional(OtherApplicationsBundle::getUrgencyTimeFrameType)
                    .eventLabel("Please state how soon you want the judge to consider your application?")
                    .optional(OtherApplicationsBundle::getSupplementsBundle)
                    .fieldShowCondition("caseTypeOfApplication=\"C100\"")
                    .eventLabel("Supplements")
                    .complex(OtherApplicationsBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getName).done()
                    .complex(OtherApplicationsBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getSecureAccommodationType)
                    .fieldShowCondition("temporaryOtherApplicationsBundle.supplementsBundle.name=\"C20_SECURE_ACCOMMODATION\"")
                    .eventLabel("Which jurisdiction?").done()
                    .complex(OtherApplicationsBundle::getSupplementsBundle, Supplement.class)
                    .optional(Supplement::getNotes).done()
                    .complex(OtherApplicationsBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(OtherApplicationsBundle::getSupplementsBundle, Supplement.class)
                    .readonly(Supplement::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>").done()
                    .complex(OtherApplicationsBundle::getSupplementsBundle, Supplement.class)
                    .mandatory(Supplement::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done()
                    .optional(OtherApplicationsBundle::getSupportingEvidenceBundle)
                    .eventLabel("Supporting Documents")
                    .complex(OtherApplicationsBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getName)
                    .eventLabel("File name").done()
                    .complex(OtherApplicationsBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .optional(SupportingEvidenceBundle::getNotes).done()
                    .complex(OtherApplicationsBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocument)
                    .eventLabel("Upload document").done()
                    .complex(OtherApplicationsBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .readonly(SupportingEvidenceBundle::getDocumentAcknowledgeLabel)
                    .eventLabel("<br /><div class='govuk-warning-text'><span class='govuk-warning-text__icon' aria-hidden='true'>!</span><strong class='govuk-warning-text__text'>Check if this document is related to ${applicantCaseName}</strong></div><br>").done()
                    .complex(OtherApplicationsBundle::getSupportingEvidenceBundle, SupportingEvidenceBundle.class)
                    .mandatory(SupportingEvidenceBundle::getDocumentAcknowledge)
                    .eventLabel("Tick to confirm this document is related to this case").done().done().done();
    }
}
