package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.UploadAdditionalApplicationsPage4;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code uploadAdditionalApplications} for case type {@code PRLAPPS}.
 */
@Component
public class UploadAdditionalApplications implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_ADDITIONAL_APPLICATIONS = "uploadAdditionalApplications";

    /**
     * Registers event {@code uploadAdditionalApplications}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_ADDITIONAL_APPLICATIONS)
            .forStates(State.SUBMITTED_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.DECISION_OUTCOME, State.CASE_WITHDRAWN, State.ALL_FINAL_ORDERS_ISSUED, State.AWAITING_RESUBMISSION_TO_HMCTS, State.AWAITING_INFORMATION)
            .name("Upload additional applications")
            .displayOrder(63)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, UserRole.CASEWORKER_WA_TASK_CONFIGURATION, UserRole.CITIZEN)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.C100_APPLICANTSOLICITOR1, UserRole.C100_APPLICANTSOLICITOR2, UserRole.C100_APPLICANTSOLICITOR3, UserRole.C100_APPLICANTSOLICITOR4, UserRole.C100_APPLICANTSOLICITOR5, UserRole.C100_RESPONDENTSOLICITOR1, UserRole.C100_RESPONDENTSOLICITOR2, UserRole.C100_RESPONDENTSOLICITOR3, UserRole.C100_RESPONDENTSOLICITOR4, UserRole.C100_RESPONDENTSOLICITOR5, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.FL401_APPLICANTSOLICITOR, UserRole.FL401_RESPONDENTSOLICITOR)
            .fields();
        UploadAdditionalApplicationsPage1.apply(fields);
        UploadAdditionalApplicationsPage2.apply(fields);
        UploadAdditionalApplicationsPage3.apply(fields);
        UploadAdditionalApplicationsPage4.apply(fields);
    }
}
