package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code uploadDocuments} for case type {@code PRLAPPS}.
 */
@Component
public class UploadDocuments implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_DOCUMENTS = "uploadDocuments";

    /**
     * Registers event {@code uploadDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_DOCUMENTS)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Upload documents")
            .displayOrder(49)
            .showCondition("caseTypeOfApplication=\"C100\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY)
            .fields();
        fields.page("1");
        fields.readonly(CaseData::getLabelPleaseUploadDocuments)
                    .publish(false);
        fields.readonly(CaseData::getLabelDocumentsRequired)
                    .publish(false);
        fields.readonly(CaseData::getLabelContactOrResidenceOrder)
                    .publish(false);
        fields.optional(CaseData::getContactOrderDocumentsUploaded)
                    .publish(false);
        fields.readonly(CaseData::getLabelC8FormForConfidentiality)
                    .publish(false);
        fields.optional(CaseData::getC8FormDocumentsUploaded)
                    .publish(false);
        fields.readonly(CaseData::getLabelUploadOtherDocuments)
                    .publish(false);
        fields.optional(CaseData::getOtherDocumentsUploaded)
                    .publish(false);
    }
}
