package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.AllegationOfHarmRevised;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code viewPdfDocument} for case type {@code PRLAPPS}.
 */
@Component
public class ViewPdfDocument implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String VIEW_PDF_DOCUMENT = "viewPdfDocument";

    /**
     * Registers event {@code viewPdfDocument}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(VIEW_PDF_DOCUMENT)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("View PDF application")
            .description("View pdf document of the application submitted by solicitor")
            .displayOrder(105)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getDownloadApplicationLabel)
                    .readonlyNoSummary(CaseDataExtra::getLinkToDownloadApplicationLabel).done();
        fields.readonly(CaseData::getIsEngDocGen)
                    .fieldShowCondition("linkToDownloadApplicationLabel=\"DO NOT SHOW\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getViewPDFlinkLabel).done();
        fields.readonly(CaseData::getSubmitAndPayDownloadApplicationLink)
                    .fieldShowCondition("isEngDocGen=\"Yes\"");
        fields.readonly(CaseData::getIsWelshDocGen)
                    .fieldShowCondition("linkToDownloadApplicationLabel=\"DO_NOT_SHOW\"");
        fields.readonly(CaseData::getSubmitAndPayDownloadApplicationWelshLink)
                    .fieldShowCondition("isWelshDocGen=\"Yes\"");
        fields.readonly(CaseData::getC1ADraftDocument)
                    .fieldShowCondition("isEngDocGen=\"Yes\" AND newAllegationsOfHarmYesNo= \"Yes\"");
        fields.readonly(CaseData::getC1AWelshDraftDocument)
                    .fieldShowCondition("isWelshDocGen=\"Yes\" AND newAllegationsOfHarmYesNo= \"Yes\"");
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .readonly(AllegationOfHarmRevised::getNewAllegationsOfHarmYesNo)
                    .fieldShowCondition("linkToDownloadApplicationLabel=\"DO_NOT_SHOW\"").done();
    }
}
