package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage10;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage102;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage11;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage12;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage13;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage14;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage15;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage16;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage17;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage18;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage19;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage20;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage21;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage22;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage23;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage24;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage25;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage26;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage27;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage28;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage30;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage5;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage6;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage7;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage8;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaManageOrdersPage9;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code waManageOrders} for case type {@code PRLAPPS}.
 */
@Component
public class WaManageOrders implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String WA_MANAGE_ORDERS = "waManageOrders";

    /**
     * Registers event {@code waManageOrders}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(WA_MANAGE_ORDERS)
            .forStateTransition(EnumSet.of(State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.ALL_FINAL_ORDERS_ISSUED, State.CASE_WITHDRAWN, State.DECISION_OUTCOME), State.ALL_FINAL_ORDERS_ISSUED)
            .name("Manage orders")
            .displayOrder(40)
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CITIZEN, UserRole.CREATOR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .fields();
        WaManageOrdersPage1.apply(fields);
        WaManageOrdersPage10.apply(fields);
        WaManageOrdersPage11.apply(fields);
        WaManageOrdersPage12.apply(fields);
        WaManageOrdersPage13.apply(fields);
        WaManageOrdersPage14.apply(fields);
        WaManageOrdersPage2.apply(fields);
        WaManageOrdersPage102.apply(fields);
        WaManageOrdersPage20.apply(fields);
        WaManageOrdersPage21.apply(fields);
        WaManageOrdersPage22.apply(fields);
        WaManageOrdersPage23.apply(fields);
        WaManageOrdersPage24.apply(fields);
        WaManageOrdersPage25.apply(fields);
        WaManageOrdersPage26.apply(fields);
        WaManageOrdersPage27.apply(fields);
        WaManageOrdersPage28.apply(fields);
        WaManageOrdersPage3.apply(fields);
        WaManageOrdersPage30.apply(fields);
        WaManageOrdersPage4.apply(fields);
        WaManageOrdersPage5.apply(fields);
        WaManageOrdersPage6.apply(fields);
        WaManageOrdersPage7.apply(fields);
        WaManageOrdersPage8.apply(fields);
        WaManageOrdersPage9.apply(fields);
        WaManageOrdersPage15.apply(fields);
        WaManageOrdersPage16.apply(fields);
        WaManageOrdersPage17.apply(fields);
        WaManageOrdersPage18.apply(fields);
        WaManageOrdersPage19.apply(fields);
    }
}
