package uk.gov.hmcts.reform.prl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage5;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code waSendOrReplyToMessages} for case type {@code PRLAPPS}.
 */
@Component
public class WaSendOrReplyToMessages implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String WA_SEND_OR_REPLY_TO_MESSAGES = "waSendOrReplyToMessages";

    /**
     * Registers event {@code waSendOrReplyToMessages}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(WA_SEND_OR_REPLY_TO_MESSAGES)
            .forStates(State.SUBMITTED_PAID, State.SUBMITTED_NOT_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_WITHDRAWN, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.ALL_FINAL_ORDERS_ISSUED, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Send and reply to messages")
            .displayOrder(48)
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .fields();
        WaSendOrReplyToMessagesPage1.apply(fields);
        WaSendOrReplyToMessagesPage2.apply(fields);
        WaSendOrReplyToMessagesPage3.apply(fields);
        WaSendOrReplyToMessagesPage4.apply(fields);
        WaSendOrReplyToMessagesPage5.apply(fields);
    }
}
