package uk.gov.hmcts.reform.prl.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage4;
import uk.gov.hmcts.reform.prl.ccd.event.page.WaSendOrReplyToMessagesPage5;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.common.judicial.JudicialUser;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.sendandreply.Message;
import uk.gov.hmcts.reform.prl.models.sendandreply.SendAndReplyDynamicDoc;
import uk.gov.hmcts.reform.prl.models.sendandreply.SendOrReplyMessage;
import uk.gov.hmcts.reform.prl.models.sendandreply.SendReplyTempDoc;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code waSendOrReplyToMessages} for case type {@code PRLAPPS}.
 */
@Component
public class WaSendOrReplyToMessages implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String WA_SEND_OR_REPLY_TO_MESSAGES = "waSendOrReplyToMessages";

    /**
     * Registers event {@code waSendOrReplyToMessages}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(WA_SEND_OR_REPLY_TO_MESSAGES)
            .forStates(State.SUBMITTED_PAID, State.SUBMITTED_NOT_PAID, State.CASE_ISSUED, State.JUDICIAL_REVIEW, State.AWAITING_RESUBMISSION_TO_HMCTS, State.CASE_WITHDRAWN, State.PREPARE_FOR_HEARING_CONDUCT_HEARING, State.ALL_FINAL_ORDERS_ISSUED, State.DECISION_OUTCOME, State.AWAITING_INFORMATION)
            .name("Send and reply to messages")
            .displayOrder(48)
            .showCondition("caseTypeOfApplication=\"NEVER_SHOW\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA)
            .fields();
        WaSendOrReplyToMessagesPage1.apply(fields);
        WaSendOrReplyToMessagesPage2.apply(fields);
        WaSendOrReplyToMessagesPage3.apply(fields);
        WaSendOrReplyToMessagesPage4.apply(fields);
        WaSendOrReplyToMessagesPage5.apply(fields);
        fields.complex(CaseData::getSendOrReplyMessage)
                    .complex(SendOrReplyMessage::getInternalMessageAttachDocsList, SendReplyTempDoc.class)
                    .readonly(SendReplyTempDoc::getAttachedTime)
                    .eventLabel("Attached date time")
                    .readonly(SendReplyTempDoc::getDocument)
                    .eventLabel("Document").done().done();
        fields.complex(CaseData::getSendOrReplyMessage)
                    .complexScope(SendOrReplyMessage::getReplyMessageObject)
                    .mandatory(Message::getInternalMessageReplyTo)
                    .eventLabel("Who are you sending the message to?")
                    .optional(Message::getJudicialOrMagistrateTierList)
                    .fieldShowCondition("replyMessageObject.internalMessageReplyTo=\"JUDICIARY\"")
                    .eventLabel("Select a judicial tier or enter a judge's name manually")
                    .eventHint("Select Judicial tier")
                    .optional(Message::getSendReplyJudgeName)
                    .fieldShowCondition("replyMessageObject.internalMessageReplyTo=\"JUDICIARY\"")
                    .eventLabel("Enter name of Judge")
                    .optional(Message::getLegalAdviserList)
                    .fieldShowCondition("replyMessageObject.internalMessageReplyTo=\"LEGAL_ADVISER\"")
                    .eventLabel("Select a legal adviser")
                    .eventHint("Select a legal adviser")
                    .mandatory(Message::getInternalMessageUrgent)
                    .eventLabel("Is this urgent?")
                    .readonly(Message::getYourMessageLabel)
                    .eventLabel("**Your message**")
                    .mandatory(Message::getMessageContent)
                    .eventLabel("Enter your message")
                    .eventHint("Explain what you're requesting and why. Include answers and decisions you need.")
                    .complex(Message::getSendReplyJudgeName)
                    .optional(JudicialUser::getIdamId)
                    .fieldShowCondition("replyMessageObject.internalMessageReplyTo=\"JUDICIARY\"")
                    .eventLabel("Enter name of Judge").done()
                    .complex(Message::getSendReplyJudgeName)
                    .optional(JudicialUser::getPersonalCode)
                    .fieldShowCondition("replyMessageObject.internalMessageReplyTo=\"JUDICIARY\"")
                    .eventLabel("Enter name of Judge").done().done().done();
        fields.complex(CaseData::getSendOrReplyMessage)
                    .complexScope(SendOrReplyMessage::getSendMessageObject)
                    .mandatory(Message::getInternalOrExternalMessage)
                    .eventLabel("Who are you sending the message to?")
                    .mandatory(Message::getInternalMessageWhoToSendTo)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"INTERNAL\"")
                    .eventLabel("Select who to send to")
                    .optional(Message::getExternalMessageWhoToSendTo)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"EXTERNAL\"")
                    .eventLabel("Select who to send the message to")
                    .mandatory(Message::getSendMessageToCafcass)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"EXTERNAL\"")
                    .eventLabel("Do you want to send a message to Cafcass?")
                    .mandatory(Message::getCafcassEmailAddress)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"EXTERNAL\" AND sendMessageObject.sendMessageToCafcass=\"Yes\"")
                    .eventLabel("Cafcass email address")
                    .mandatory(Message::getSendMessageToOtherParties)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"EXTERNAL\"")
                    .eventLabel("Do you want to send a message to any other parties/organisations?")
                    .mandatory(Message::getOtherPartiesEmailAddress)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"EXTERNAL\" AND sendMessageObject.sendMessageToOtherParties=\"Yes\"")
                    .eventLabel("Enter email address")
                    .eventHint("Enter the email address separated by commas to send to multiple recipients")
                    .mandatory(Message::getJudicialOrMagistrateTierList)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"JUDICIARY\"")
                    .eventLabel("Select a judicial tier or enter a judge's name manually")
                    .eventHint("Select Judicial tier")
                    .optional(Message::getSendReplyJudgeName)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"JUDICIARY\"")
                    .eventLabel("Enter name of Judge")
                    .optional(Message::getLegalAdviserList)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"LEGAL_ADVISER\"")
                    .eventLabel("Select a legal adviser")
                    .eventHint("Select a legal adviser")
                    .mandatory(Message::getCtscEmailList)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"OTHER\"")
                    .eventLabel("Select where you're sending it from")
                    .eventHint("Depending on your selection, the email template will change")
                    .mandatory(Message::getRecipientEmailAddresses)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"OTHER\"")
                    .eventLabel("Enter email address")
                    .eventHint("Enter the email address separated by commas to send to multiple recipients.")
                    .mandatory(Message::getInternalMessageUrgent)
                    .fieldShowCondition("sendMessageObject.internalOrExternalMessage=\"INTERNAL\"")
                    .eventLabel("Is this urgent?")
                    .mandatory(Message::getMessageAbout)
                    .eventLabel("What is this message about?")
                    .mandatory(Message::getMessageSubject)
                    .fieldShowCondition("sendMessageObject.messageAbout!=\"\"")
                    .eventLabel("Enter the message subject")
                    .optional(Message::getApplicationsList)
                    .fieldShowCondition("sendMessageObject.messageAbout=\"APPLICATION\"")
                    .eventLabel("Select the application")
                    .mandatory(Message::getFutureHearingsList)
                    .fieldShowCondition("sendMessageObject.messageAbout=\"HEARING\"")
                    .eventLabel("Select hearing")
                    .mandatory(Message::getSubmittedDocumentsList)
                    .fieldShowCondition("sendMessageObject.messageAbout=\"REVIEW_SUBMITTED_DOCUMENTS\"")
                    .eventLabel("Select file")
                    .mandatory(Message::getSelectedDocument)
                    .fieldShowCondition("selectedDocument=\"DO_NOT_SHOW\"")
                    .eventLabel("Document")
                    .complex(Message::getSendReplyJudgeName)
                    .optional(JudicialUser::getIdamId)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"JUDICIARY\"")
                    .eventLabel("Enter name of Judge").done()
                    .complex(Message::getSendReplyJudgeName)
                    .optional(JudicialUser::getPersonalCode)
                    .fieldShowCondition("sendMessageObject.internalMessageWhoToSendTo=\"JUDICIARY\"")
                    .eventLabel("Enter name of Judge").done().done().done();
        fields.complex(CaseData::getSendOrReplyMessage)
                    .complex(SendOrReplyMessage::getExternalMessageAttachDocsList, SendAndReplyDynamicDoc.class)
                    .optional(SendAndReplyDynamicDoc::getSubmittedDocsRefList)
                    .eventLabel("Select a document").done().done();
    }
}
