package uk.gov.hmcts.reform.prl.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.ccd.event.page.WithoutNoticeOrderDetailsPage1;
import uk.gov.hmcts.reform.prl.ccd.event.page.WithoutNoticeOrderDetailsPage2;
import uk.gov.hmcts.reform.prl.ccd.event.page.WithoutNoticeOrderDetailsPage3;
import uk.gov.hmcts.reform.prl.ccd.event.page.WithoutNoticeOrderDetailsPage4;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code withoutNoticeOrderDetails} for case type {@code PRLAPPS}.
 */
@Component
public class WithoutNoticeOrderDetails implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String WITHOUT_NOTICE_ORDER_DETAILS = "withoutNoticeOrderDetails";

    /**
     * Registers event {@code withoutNoticeOrderDetails}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(WITHOUT_NOTICE_ORDER_DETAILS)
            .forStates(State.AWAITING_SUBMISSION_TO_HMCTS, State.AWAITING_RESUBMISSION_TO_HMCTS)
            .name("Without notice order")
            .description("Without Notice Order")
            .displayOrder(4)
            .showCondition("caseTypeOfApplication=\"FL401\"")
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SUPERUSER)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, UserRole.CITIZEN, UserRole.CREATOR)
            .fields();
        WithoutNoticeOrderDetailsPage1.apply(fields);
        WithoutNoticeOrderDetailsPage2.apply(fields);
        WithoutNoticeOrderDetailsPage3.apply(fields);
        WithoutNoticeOrderDetailsPage4.apply(fields);
    }
}
