package uk.gov.hmcts.reform.prl.ccd.event;
import uk.gov.hmcts.reform.prl.models.complextypes.WithdrawApplication;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Event {@code WithdrawApplication_Event} for case type {@code PRLAPPS}.
 */
@Component
public class WithdrawApplicationEvent implements CCDConfig<CaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String WITHDRAW_APPLICATION_EVENT = "WithdrawApplication_Event";

    /**
     * Registers event {@code WithdrawApplication_Event}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        var fields = builder.event(WITHDRAW_APPLICATION_EVENT)
            .forStateTransition(EnumSet.of(State.SUBMITTED_PAID, State.SUBMITTED_NOT_PAID, State.AWAITING_RESUBMISSION_TO_HMCTS, State.AWAITING_SUBMISSION_TO_HMCTS), State.CASE_WITHDRAWN)
            .name("Withdraw application")
            .displayOrder(65)
            .showCondition("isWithdrawRequestSent!=\"Pending\" AND isWithdrawRequestSent!=\"Approved\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, UserRole.CASEWORKER_PRIVATELAW_JUDGE, UserRole.CASEWORKER_PRIVATELAW_LA, UserRole.CASEWORKER_PRIVATELAW_READONLY, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE)
            .grant(Permission.CRU, UserRole.APPLICANTSOLICITOR, UserRole.CITIZEN, UserRole.CREATOR)
            .fields();
        fields.page("1");
        fields.complex(CaseData::getWithDrawApplicationData)
                    .mandatory(WithdrawApplication::getWithDrawApplication)
                    .mandatory(WithdrawApplication::getWithDrawApplicationReason)
                    .fieldShowCondition("withDrawApplicationData.withDrawApplication=\"Yes\"").done();
    }
}
