package uk.gov.hmcts.reform.prl.models.email;

public enum EmailTemplateNames {
    EXAMPLE,
    SOLICITOR,
    CASEWORKER,
    RETURNAPPLICATION,
    WITHDRAW,
    SEND_AND_REPLY_NOTIFICATION,
    COURTADMIN,
    GATEKEEPER,
    GATEKEEPER_FL401,
    DA_SOLICITOR,
    DA_LOCALCOURT,
    CASE_INVITE,
    WITHDRAW_AFTER_ISSUED_LOCAL_COURT,
    WITHDRAW_AFTER_ISSUED_SOLICITOR,
    APPLICANT_SOLICITOR,
    RESPONDENT_SOLICITOR,
    RESPONDENT_WITHOUT_SOLICITOR
}
