package uk.gov.hmcts.reform.prl.models.email;

public enum SendgridEmailTemplateNames {

    SERVE_ORDER_ANOTHER_ORGANISATION,
    SERVE_ORDER_PERSONAL_APPLICANT_SOLICITOR,
    SERVE_ORDER_NON_PERSONAL_SOLLICITOR,
    SERVE_ORDER_CAFCASS_CYMRU,
    SERVE_ORDER_APPLICANT_RESPONDENT

}
