package uk.gov.hmcts.reform.prl.models.email;

public enum SendgridEmailTemplateNames {

    SERVE_ORDER_ANOTHER_ORGANISATION,
    SERVE_ORDER_PERSONAL_APPLICANT_SOLICITOR,
    SERVE_ORDER_NON_PERSONAL_SOLLICITOR,
    SOA_SERVE_APPLICANT_SOLICITOR_NONPER_PER_CA_CB
}
