package uk.gov.hmcts.reform.prl.models.email;

public enum SendgridEmailTemplateNames {

    SERVE_ORDER_ANOTHER_ORGANISATION,
    SERVE_ORDER_PERSONAL_APPLICANT_SOLICITOR,
    SERVE_ORDER_NON_PERSONAL_SOLLICITOR,
    SERVE_ORDER_APPLICANT_RESPONDENT,
    SOA_SERVE_APPLICANT_SOLICITOR_NONPER_PER_CA_CB,
    SOA_PERSONAL_CA_DA_APPLICANT_LEGAL_REP,
    SOA_CA_LOCAL_AUTHORITY,
    SERVE_ORDER_CAFCASS_CYMRU,
    SOA_CA_APPLICANT_LIP_PERSONAL,
    SOA_CA_NON_PERSONAL_SERVICE_APPLICANT_LIP,
    SOA_CA_NON_PERSONAL_SERVICE_RESPONDENT_LIP,
    SERVE_ORDER_CA_PERSONAL_APPLICANT_LIP,
    SERVE_ORDER_DA_PERSONAL_APPLICANT_LIP,
    RESPONDENT_RESPONSE_TO_APPLICATION

}
