server:
  port: 4044

runs-locally: ${RUNS_LOCALLY:true}

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Prl cos api
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

logging:
  level:
    org.springframework.web: DEBUG
    uk.gov.hmcts.reform.prl: DEBUG
    au.com.dius.pact: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

pba:
  validation:
    service:
      api:
        baseurl: ${PRD_API_BASEURL:http://localhost:8892}

feature-toggle:
  toggle:
    example: ${FEATURE_EXAMPLE:false}

uk:
  gov:
    notify:
      api:
        key: ${UK_GOV_NOTIFY_API_KEY:xxxxxxxx}
        baseUrl: https://api.notifications.service.gov.uk
      email:
        templates:
          english:
            EXAMPLE: 2e00903c-46f4-46d6-9d94-d419ee30b927
          welsh:
            EXAMPLE: example-template-id-222

notify:
  api-key: fake-key
  baseUrl: https://api.notifications.service.gov.uk

payments:
  api:
    url: ${PAY_URL:}
    callback-url: ${PAY_CALLBACK_URL:}

fees-register:
  api:
    url: http://fees-register-api-demo.service.core-compute-demo.internal
  parameters:
    C100_SUBMISSION_FEE:
      channel: default
      event: miscellaneous
      jurisdiction1: family
      jurisdiction2: family court
      keyword: ChildArrangement
      service: private law

# NEW BELOW THIS LINE


idam:
  s2s-auth:
    url: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    microservice: prl_cos_api
    totp-secret: ${IDAM_S2S_AUTH_TOTP_SECRET:}
  api:
    url: https://idam-api.aat.platform.hmcts.net
  client:
    id: prl-cos-api
    redirect_uri: https://manage-case.aat.platform.hmcts.net/oauth2/callback
    secret: ${IDAM_CLIENT_SECRET:}


core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:}

prl:
  system-update:
    username: ${SYSTEM_UPDATE_USER_USERNAME:}
    password: ${PRL_SYSTEM_UPDATE_PASSWORD:}

security:
  oauth2:
    client:
      provider:
        oidc:
          issuer-uri: ${idam.web.url}/o
      registration:
        oidc:
          client-id: internal
          client-secret: internal


auth:
  idam:
    client:
      baseUrl: ${AUTH_IDAM_CLIENT_BASEURL:}
  provider:
    service:
      client:
        baseUrl: ${AUTH_PROVIDER_SERVICE_CLIENT_BASEURL:}


resources:
  images:
    baseUrl: 'https://raw.githubusercontent.com/hmcts/prl-cos-api/task-list-and-submit-and-pay-combined/resources/'

test:
  secret: ${TEST_SECRET:}
