server:
  port: 4044

runs-locally: ${RUNS_LOCALLY:true}

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

  #If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Prl cos api
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${APP_INSIGHTS_INSTRUMENTATION_KEY:00000000-0000-0000-0000-000000000000}

logging:
  level:
    org.springframework.web: DEBUG
    uk.gov.hmcts.reform.prl: DEBUG
    au.com.dius.pact: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"

pba:
  validation:
    service:
      api:
        baseurl: ${PRD_API_BASEURL:http://localhost:8892}

feature-toggle:
  toggle:
    example: ${FEATURE_EXAMPLE:false}

xui:
  url: ${XUI_URL:https://manage-case.aat.platform.hmcts.net/cases/case-details}

uk:
  gov:
    notify:
      api:
        key: ${UK_GOV_NOTIFY_API_KEY:xxxxxxx}
        baseUrl: https://api.notifications.service.gov.uk
      email:
        templates:
          english:
            SOLICITOR: a080f4ce-a07f-43ec-a3f0-f196d83f7730
            CASEWORKER: 8c1cd107-b76f-4e10-9c44-afb49415cda2
            RETURNAPPLICATION: 41a7ffcd-a5ec-4377-ba50-59619ad0ac8c
            WITHDRAW: 1c2c272a-1514-4d52-a673-393f857da34d
            COURTADMIN: f980e4a8-4eed-4887-9ae9-cb2c6a42fec7
            GATEKEEPER: 52223e2c-1c68-470b-b0bb-66121569adb1
            EXAMPLE: 50c74207-a341-4cd2-a073-71b218ad135e
            SEND_AND_REPLY_NOTIFICATION: 9f30cc9f-25d2-4abf-9568-cb428dff1d3a
          welsh:
            EXAMPLE: 50c74207-a341-4cd2-a073-71b218ad135e
        application:
          email-id: C100applications@justice.gov.uk
          court-name: Court Name


notify:
  api-key: fake-key
  baseUrl: https://api.notifications.service.gov.uk

payments:
  api:
    url: ${PAY_URL:}
    callback-url: ${PAY_CALLBACK_URL:}

fees-register:
  api:
    url: ${FEE_REGISTER_API_URL:http://fees-register-api-aat.service.core-compute-aat.internal}
  parameters:
    C100_SUBMISSION_FEE:
      channel: default
      event: miscellaneous
      jurisdiction1: family
      jurisdiction2: family court
      keyword: ChildArrangement
      service: private law

# NEW BELOW THIS LINE


idam:
  api:
    url: http://localhost:5000
  s2s-auth:
    url: http://localhost:4502
    totp_secret: AABBCCDDEEFFGGHH
    microservice: prl_cos_api
  client:
    id: prl_cos_api
    redirect_uri: https://localhost:9000/oauth2/callback
    secret: OOOOOOOOOOOOOOOO

prl:
  system-update:
    username: ${SYSTEM_UPDATE_USER_USERNAME:privatelaw-system-update@mailnesia.com}
    password: ${PRL_SYSTEM_UPDATE_PASSWORD:Password12!}

security:
  oauth2:
    client:
      provider:
        oidc:
          issuer-uri: ${idam.web.url}/o
      registration:
        oidc:
          client-id: internal
          client-secret: internal
core_case_data:
  api:
    url: http://localhost:4452

auth:
  idam:
    client:
      baseUrl: http://localhost:5000
  provider:
    service:
      client:
        baseUrl: http://localhost:4502

resources:
  images:
    baseUrl: 'https://raw.githubusercontent.com/hmcts/prl-cos-api/master/resources/'


send-letter:
  url: http://rpe-send-letter-service-aat.service.core-compute-aat.internal

case_document_am:
  url: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal

prl-dgs-api:
  url: http://localhost:4007

courtfinder:
  api:
    url: ${FACT_API:http://fact-api-aat.service.core-compute-aat.internal}

rd_professional:
  api:
    url: http://rd-professional-api-aat.service.core-compute-aat.internal

launchdarkly:
  sdk-key: "${LAUNCH_DARKLY_SDK_KEY:}"

