package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 17} of event {@code adminEditAndApproveAnOrder}.
 */
public final class AdminEditAndApproveAnOrderPage17 {
    private AdminEditAndApproveAnOrderPage17() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("17");
        fields.showCondition("doYouWantToEditTheOrder=\"Yes\" AND orderType=\"standardDirectionsOrder\"");
        AdminEditAndApproveAnOrderPage17Fields1.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields2.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields3.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields4.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields5.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields6.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields7.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields8.apply(fields);
        AdminEditAndApproveAnOrderPage17Fields9.apply(fields);
    }
}
