package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.StandardDirectionOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Field placements for page {@code 17} of event {@code adminEditAndApproveAnOrder} (part 5 of 9).
 */
public final class AdminEditAndApproveAnOrderPage17Fields5 {
    private AdminEditAndApproveAnOrderPage17Fields5() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoDraHearingDetails)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSettlementConferenceLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
    }
}
