package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.OrdersHearingPageFieldShowParams;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 4} of event {@code adminEditAndApproveAnOrder}.
 */
public final class AdminEditAndApproveAnOrderPage4 {
    private AdminEditAndApproveAnOrderPage4() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("4");
        fields.showCondition("orderUploadedAsDraftFlag!=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getOrderName)
                    .fieldShowCondition("doYouWantToEditTheOrder=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getJudgeNotesEmptyDraftJourney)
                    .fieldShowCondition("orderName=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getPreviewDraftOrderLabel)
                    .publish(false);
        fields.readonly(CaseData::getPreviewDraftOrderWelsh)
                    .publish(false);
        fields.readonly(CaseData::getPreviewDraftOrder)
                    .publish(false);
        fields.readonly(CaseData::getOrderNameEditScreenLabel)
                    .publish(false);
        fields.mandatory(CaseData::getDoYouWantToEditTheOrder)
                    .publish(false);
        fields.readonly(CaseData::getInstructionsFromJudge)
                    .fieldShowCondition("judgeNotesEmptyDraftJourney!=\"Yes\"")
                    .publish(false);
        fields.readonly(CaseData::getOrderType)
                    .fieldShowCondition("doYouWantToEditTheOrder=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.mandatory(CaseData::getIsOrderCreatedBySolicitor)
                    .fieldShowCondition("doYouWantToEditTheOrder=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getIsHearingPageNeeded)
                    .fieldShowCondition("doYouWantToEditTheOrder=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.complex(CaseData::getOrdersHearingPageFieldShowParams)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsCafcassCymru)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsFL401ApplicantPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsFL401ApplicantSolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsFL401RespondentPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsFL401RespondentSolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant1Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant2Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant3Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant4Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant5Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant1SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant2SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant3SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant4SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsApplicant5SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent1Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent2Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent3Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent4Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent5Present)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent1SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent2SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent3SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent4SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .optionalNoSummary(OrdersHearingPageFieldShowParams::getIsRespondent5SolicitorPresent)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .readonly(ManageOrders::getC21OrderOptions)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .publish(false).done();
    }
}
