package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.AllegationOfHarmRevised;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code allegationsOfHarmRevised}.
 */
public final class AllegationsOfHarmRevisedPage3 {
    private AllegationsOfHarmRevisedPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.showCondition("newAllegationsOfHarmDomesticAbuseYesNo=\"Yes\" AND newAllegationsOfHarmYesNo=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getDomesticAbuseBehavioursLabel)
                    .publish(false)
                    .readonly(CaseDataExtra::getDomesticAbuseBehavioursSubLabel)
                    .publish(false).done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .optional(AllegationOfHarmRevised::getDomesticBehaviours)
                    .publish(false).done();
    }
}
