package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.AllegationOfHarm;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code amendAllegationsOfHarm}.
 */
public final class AmendAllegationsOfHarmPage2 {
    private AmendAllegationsOfHarmPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.showCondition("allegationsOfHarmYesNo=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSubmissionRequiredFieldsInfo2)
                    .readonly(CaseDataExtra::getAllegationsOfHarmLabel).done();
        fields.complex(CaseData::getAllegationOfHarm)
                    .optional(AllegationOfHarm::getAllegationsOfHarmDomesticAbuseYesNo)
                    .optional(AllegationOfHarm::getPhysicalAbuseVictim)
                    .fieldShowCondition("allegationsOfHarmDomesticAbuseYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getEmotionalAbuseVictim)
                    .fieldShowCondition("allegationsOfHarmDomesticAbuseYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getPsychologicalAbuseVictim)
                    .fieldShowCondition("allegationsOfHarmDomesticAbuseYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getSexualAbuseVictim)
                    .fieldShowCondition("allegationsOfHarmDomesticAbuseYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getFinancialAbuseVictim)
                    .fieldShowCondition("allegationsOfHarmDomesticAbuseYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getAllegationsOfHarmChildAbductionYesNo)
                    .optional(AllegationOfHarm::getChildAbductionReasons)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getPreviousAbductionThreats)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getPreviousAbductionThreatsDetails)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\" AND previousAbductionThreats=\"Yes\"")
                    .optional(AllegationOfHarm::getChildrenLocationNow)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getAbductionPassportOfficeNotified)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getAbductionChildHasPassport)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getAbductionChildPassportPosession)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getAbductionChildPassportPosessionOtherDetail)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\" AND abductionChildPassportPosession=\"other\"")
                    .optional(AllegationOfHarm::getAbductionPreviousPoliceInvolvement)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getAbductionPreviousPoliceInvolvementDetails)
                    .fieldShowCondition("allegationsOfHarmChildAbductionYesNo=\"Yes\" AND abductionPreviousPoliceInvolvement=\"Yes\"")
                    .optional(AllegationOfHarm::getAllegationsOfHarmChildAbuseYesNo)
                    .optional(AllegationOfHarm::getAllegationsOfHarmSubstanceAbuseYesNo)
                    .optional(AllegationOfHarm::getAllegationsOfHarmOtherConcernsYesNo).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAllegationOfHarmOrdersLabel)
                    .readonly(CaseDataExtra::getAllegationOfHarmOrdersLabelDetail).done();
        fields.complex(CaseData::getAllegationOfHarm)
                    .optional(AllegationOfHarm::getOrdersNonMolestation)
                    .optional(AllegationOfHarm::getOrdersNonMolestationDateIssued)
                    .fieldShowCondition("ordersNonMolestation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersNonMolestationEndDate)
                    .fieldShowCondition("ordersNonMolestation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersNonMolestationCurrent)
                    .fieldShowCondition("ordersNonMolestation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersNonMolestationCourtName)
                    .fieldShowCondition("ordersNonMolestation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersNonMolestationDocument)
                    .fieldShowCondition("ordersNonMolestation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOccupation)
                    .optional(AllegationOfHarm::getOrdersOccupationDateIssued)
                    .fieldShowCondition("ordersOccupation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOccupationEndDate)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOccupation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOccupationCurrent)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOccupation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOccupationCourtName)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOccupation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOccupationDocument)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOccupation=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersForcedMarriageProtection)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersForcedMarriageProtectionDateIssued)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersForcedMarriageProtection=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersForcedMarriageProtectionEndDate)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersForcedMarriageProtection=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersForcedMarriageProtectionCurrent)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersForcedMarriageProtection=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersForcedMarriageProtectionCourtName)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersForcedMarriageProtection=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersForcedMarriageProtectionDocument)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersForcedMarriageProtection=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersRestraining)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersRestrainingDateIssued)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersRestraining=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersRestrainingEndDate)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersRestraining=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersRestrainingCurrent)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersRestraining=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersRestrainingCourtName)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersRestraining=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersRestrainingDocument)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersRestraining=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOtherInjunctive)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOtherInjunctiveDateIssued)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOtherInjunctive=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOtherInjunctiveEndDate)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOtherInjunctive=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOtherInjunctiveCurrent)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOtherInjunctive=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOtherInjunctiveCourtName)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOtherInjunctive=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersOtherInjunctiveDocument)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersOtherInjunctive=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersUndertakingInPlace)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersUndertakingInPlaceDateIssued)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersUndertakingInPlace=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersUndertakingInPlaceEndDate)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersUndertakingInPlace=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersUndertakingInPlaceCurrent)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersUndertakingInPlace=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersUndertakingInPlaceCourtName)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersUndertakingInPlace=\"Yes\"")
                    .optional(AllegationOfHarm::getOrdersUndertakingInPlaceDocument)
                    .fieldShowCondition("allegationsOfHarmYesNo=\"Yes\" AND ordersUndertakingInPlace=\"Yes\"").done();
    }
}
