package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 4} of event {@code amendSelectApplicationType}.
 */
public final class AmendSelectApplicationTypePage4 {
    private AmendSelectApplicationTypePage4() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("4");
        fields.readonlyNoSummary(CaseData::getSubmissionRequiredFieldsInfo4);
        fields.readonly(CaseData::getParaWhyMakingApplication2);
        fields.readonly(CaseData::getParaApplicationDetails);
        fields.mandatory(CaseData::getApplicationDetails);
    }
}
