package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.AllegationOfHarmRevised;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 10} of event {@code amendAllegationsOfHarmRevised}.
 */
public final class AmendAllegationsOfHarmRevisedPage10 {
    private AmendAllegationsOfHarmRevisedPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("10");
        fields.showCondition("newAllegationsOfHarmChildAbductionYesNo=\"Yes\" AND newAllegationsOfHarmYesNo=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getChildAbductionLabel).done();
        fields.complex(CaseData::getAllegationOfHarmRevised)
                    .mandatory(AllegationOfHarmRevised::getNewChildAbductionReasons)
                    .mandatory(AllegationOfHarmRevised::getNewPreviousAbductionThreats)
                    .mandatory(AllegationOfHarmRevised::getNewPreviousAbductionThreatsDetails)
                    .fieldShowCondition("newPreviousAbductionThreats=\"Yes\"")
                    .mandatory(AllegationOfHarmRevised::getNewChildrenLocationNow)
                    .mandatory(AllegationOfHarmRevised::getNewAbductionPassportOfficeNotified)
                    .mandatory(AllegationOfHarmRevised::getNewAbductionPreviousPoliceInvolvement)
                    .mandatory(AllegationOfHarmRevised::getNewAbductionPreviousPoliceInvolvementDetails)
                    .fieldShowCondition("newAbductionPreviousPoliceInvolvement=\"Yes\"")
                    .mandatory(AllegationOfHarmRevised::getNewAbductionChildHasPassport)
                    .optional(AllegationOfHarmRevised::getChildPassportDetails)
                    .fieldShowCondition("newAbductionChildHasPassport=\"Yes\"").done();
    }
}
