package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.Address;
import uk.gov.hmcts.reform.prl.models.Organisation;
import uk.gov.hmcts.reform.prl.models.complextypes.PartyDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code amendApplicantsDetails}.
 */
public final class AmendApplicantsDetailsPage1 {
    private AmendApplicantsDetailsPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.showCondition("caseTypeOfApplication=\"C100\"");
        fields.readonlyNoSummary(CaseData::getSubmissionRequiredFieldsInfo1)
                    .publish(false);
        fields.complex(CaseData::getApplicants).done();
        fields.complex(CaseData::getApplicants, PartyDetails.class)
                    .mandatory(PartyDetails::getFirstName)
                    .mandatory(PartyDetails::getLastName)
                    .optional(PartyDetails::getPreviousName)
                    .mandatory(PartyDetails::getDateOfBirth)
                    .mandatory(PartyDetails::getGender)
                    .mandatory(PartyDetails::getOtherGender)
                    .fieldShowCondition("applicants.gender=\"other\"")
                    .mandatory(PartyDetails::getPlaceOfBirth)
                    .mandatory(PartyDetails::getLiveInRefuge)
                    .eventLabel("*Does the applicant currently live in a refuge?")
                    .mandatory(PartyDetails::getRefugeConfidentialityC8Form)
                    .fieldShowCondition("applicants.liveInRefuge=\"DO_NOT_SHOW\"")
                    .mandatory(PartyDetails::getAddress)
                    .complex(PartyDetails::getAddress)
                    .mandatory(Address::getAddressLine1).done()
                    .complex(PartyDetails::getAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(PartyDetails::getAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(PartyDetails::getAddress)
                    .optional(Address::getPostTown).done()
                    .complex(PartyDetails::getAddress)
                    .optional(Address::getCounty).done()
                    .complex(PartyDetails::getAddress)
                    .optional(Address::getPostCode).done()
                    .complex(PartyDetails::getAddress)
                    .optional(Address::getCountry).done()
                    .mandatory(PartyDetails::getHintTextForC8Form)
                    .fieldShowCondition("applicants.firstName=\"\" OR applicants.firstName=\"*\"")
                    .eventLabel("If you fill out this section you do not need to send a separate C8 form.")
                    .mandatory(PartyDetails::getIsAddressConfidential)
                    .mandatory(PartyDetails::getIsAtAddressLessThan5Years)
                    .mandatory(PartyDetails::getAddressLivedLessThan5YearsDetails)
                    .fieldShowCondition("applicants.isAtAddressLessThan5Years=\"Yes\"")
                    .mandatory(PartyDetails::getCanYouProvideEmailAddress)
                    .mandatory(PartyDetails::getEmail)
                    .fieldShowCondition("applicants.canYouProvideEmailAddress=\"Yes\"")
                    .mandatory(PartyDetails::getIsEmailAddressConfidential)
                    .fieldShowCondition("applicants.canYouProvideEmailAddress=\"Yes\"")
                    .optional(PartyDetails::getContactPreferences)
                    .fieldShowCondition("applicants.canYouProvideEmailAddress=\"Yes\"")
                    .mandatory(PartyDetails::getPhoneNumber)
                    .mandatory(PartyDetails::getIsPhoneNumberConfidential)
                    .readonly(PartyDetails::getSolicitorDetails)
                    .optional(PartyDetails::getRepresentativeFirstName)
                    .optional(PartyDetails::getRepresentativeLastName)
                    .optional(PartyDetails::getSolicitorEmail)
                    .optional(PartyDetails::getSolicitorReference)
                    .complex(PartyDetails::getSolicitorOrg)
                    .optional(Organisation::getOrganisationID).done()
                    .optional(PartyDetails::getSolicitorOrg)
                    .complex(PartyDetails::getSolicitorOrg)
                    .optional(Organisation::getOrganisationName).done()
                    .optional(PartyDetails::getDxNumber)
                    .optional(PartyDetails::getSolicitorAddress)
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getAddressLine1).done()
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getPostTown).done()
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getCounty).done()
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getPostCode).done()
                    .complex(PartyDetails::getSolicitorAddress)
                    .optional(Address::getCountry).done()
                    .mandatory(PartyDetails::getAddNewApplicantLabel).done();
        fields.mandatory(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("applicantsFL401=\"DO_NOT_SHOW\"");
    }
}
