package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.MiamDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code amendMiam}.
 */
public final class AmendMiamPage1 {
    private AmendMiamPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSubmissionRequiredFieldsInfo1)
                    .readonly(CaseDataExtra::getApplicantAttendedMIAMLabel).done();
        fields.complex(CaseData::getMiamDetails)
                    .mandatory(MiamDetails::getApplicantAttendedMiam).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getClaimingExemptionMIAMLabel)
                    .fieldShowCondition("applicantAttendedMiam=\"No\"").done();
        fields.complex(CaseData::getMiamDetails)
                    .mandatory(MiamDetails::getClaimingExemptionMiam)
                    .fieldShowCondition("applicantAttendedMiam=\"No\"").done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getFamilyMediatorMIAMLabel)
                    .fieldShowCondition("claimingExemptionMiam=\"Yes\" AND applicantAttendedMiam=\"No\"").done();
        fields.complex(CaseData::getMiamDetails)
                    .mandatory(MiamDetails::getFamilyMediatorMiam)
                    .fieldShowCondition("claimingExemptionMiam=\"Yes\" AND applicantAttendedMiam=\"No\"").done();
    }
}
