package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.solicitorresponse.RespondentAllegationsOfHarmData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code c100ResSolAllegationsOfHarmB}.
 */
public final class C100ResSolAllegationsOfHarmBPage3 {
    private C100ResSolAllegationsOfHarmBPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.showCondition("respAohDomesticAbuseYesNo=\"Yes\" AND respAohYesOrNo=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRespondentNameForResponseLabel2)
                    .readonly(CaseDataExtra::getRespDomesticAbuseBehavioursLabel)
                    .readonly(CaseDataExtra::getRespDomesticAbuseBehavioursSubLabel).done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .optional(RespondentAllegationsOfHarmData::getRespDomesticBehaviours).done().done();
    }
}
