package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.solicitorresponse.RespondentAllegationsOfHarmData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 10} of event {@code c100ResSolAllegationsOfHarmE}.
 */
public final class C100ResSolAllegationsOfHarmEPage10 {
    private C100ResSolAllegationsOfHarmEPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("10");
        fields.showCondition("respAohChildAbductionYesNo=\"Yes\" AND respAohYesOrNo=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRespondentNameForResponseLabel9)
                    .readonly(CaseDataExtra::getRespChildAbductionLabel).done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespChildAbductionReasons).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespPreviousAbductionThreats).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespPreviousAbductionThreatsDetails)
                    .fieldShowCondition("respPreviousAbductionThreats=\"Yes\"").done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespChildrenLocationNow).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespAbductionPassportOfficeNotified).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespAbductionPreviousPoliceInvolvement).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespAbductionPreviousPoliceInvolvementDetails)
                    .fieldShowCondition("respAbductionPreviousPoliceInvolvement=\"Yes\"").done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .mandatory(RespondentAllegationsOfHarmData::getRespAbductionChildHasPassport).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .optional(RespondentAllegationsOfHarmData::getRespChildPassportDetails)
                    .fieldShowCondition("respAbductionChildHasPassport=\"Yes\"").done().done();
    }
}
