package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.DocumentManagementDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code c100ResSolSubmitA}.
 */
public final class C100ResSolSubmitAPage2 {
    private C100ResSolSubmitAPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.readonly(CaseData::getSubmitAndPayDeclaration)
                    .publish(false);
        fields.readonly(CaseData::getSubmitAndPayAgreeStmtLabel)
                    .publish(false);
        fields.readonly(CaseData::getRespondentSolicitorName)
                    .fieldShowCondition("submitAndPayAgreeStmtLabel=\"never_show\"")
                    .publish(false);
        fields.readonly(CaseData::getC100ResSolSubmitAndPayAgreeSignStmtLabel)
                    .publish(false);
        fields.complex(CaseData::getRespondentSolicitorData)
                    .mandatory(RespondentSolicitorData::getRespondentAgreeStatement)
                    .publish(false)
                    .readonly(RespondentSolicitorData::getDraftC7ResponseDoc)
                    .fieldShowCondition("respondentAgreeStatement=\"agree\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDraftC7WelshResponseDoc)
                    .fieldShowCondition("respondentAgreeStatement=\"agree\"")
                    .publish(false);
        fields.complex(CaseData::getRespondentSolicitorData)
                    .readonly(RespondentSolicitorData::getDraftC1ADoc)
                    .fieldShowCondition("respondentAgreeStatement=\"agree\"")
                    .publish(false).done();
        fields.complex(CaseData::getDocumentManagementDetails)
                    .readonly(DocumentManagementDetails::getManageDocumentsRestrictedFlag)
                    .fieldShowCondition("draftC7ResponseDoc=\"DO_NOT_SHOW\"")
                    .readonly(DocumentManagementDetails::getManageDocumentsTriggeredBy)
                    .fieldShowCondition("draftC7ResponseDoc=\"DO_NOT_SHOW\"").done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .readonly(RespondentSolicitorData::getDraftC1ADocWelsh)
                    .fieldShowCondition("respondentAgreeStatement=\"agree\"")
                    .publish(false).done();
    }
}
