package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.solicitorresponse.RespondentAllegationsOfHarmData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 8} of event {@code c100ResSolAllegationsOfHarmD}.
 */
public final class C100ResSolAllegationsOfHarmDPage8 {
    private C100ResSolAllegationsOfHarmDPage8() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("8");
        fields.showCondition("respChildAbuses CONTAINS \"emotionalAbuse\" AND respAohYesOrNo=\"Yes\"");
        fields.readonly(CaseData::getRespondentNameForResponseLabel7);
        fields.readonly(CaseData::getRespChildEmotionalAbuseLabel);
        fields.readonly(CaseData::getRespChildEmotionalAbuseSubLabel);
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .optional(RespondentAllegationsOfHarmData::getRespAllChildrenAreRiskEmotionalAbuse).done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .optional(RespondentAllegationsOfHarmData::getRespWhichChildrenAreRiskEmotionalAbuse)
                    .fieldShowCondition("respAllChildrenAreRiskEmotionalAbuse=\"No\"").done().done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .complex(RespondentSolicitorData::getRespondentAllegationsOfHarmData)
                    .optional(RespondentAllegationsOfHarmData::getRespChildEmotionalAbuse).done().done();
    }
}
