package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code c100ResSolKeepDetailsPrivateD}.
 */
public final class C100ResSolKeepDetailsPrivateDPage3 {
    private C100ResSolKeepDetailsPrivateDPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.showCondition("keepContactDetailsPrivate.confidentiality=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getRespondentNameForResponseLabel2)
                    .readonlyNoSummary(CaseDataExtra::getKeepDetailsPrivateSummaryHeading).done();
        fields.complex(CaseData::getRespondentSolicitorData)
                    .readonly(RespondentSolicitorData::getConfidentialListDetails)
                    .fieldShowCondition("keepDetailsPrivateSummary=\"never_show\"").done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getKeepDetailsPrivateSummary)
                    .readonlyNoSummary(CaseDataExtra::getCourtActionHeading)
                    .readonlyNoSummary(CaseDataExtra::getCourtAction).done();
    }
}
