package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.c100respondentsolicitor.RespondentSolicitorData;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3} of event {@code c100ResSolKeepDetailsPrivateB}.
 */
public final class C100ResSolKeepDetailsPrivateBPage3 {
    private C100ResSolKeepDetailsPrivateBPage3() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("3");
        fields.showCondition("keepContactDetailsPrivate.confidentiality=\"Yes\"");
        fields.readonly(CaseData::getRespondentNameForResponseLabel2);
        fields.readonlyNoSummary(CaseData::getKeepDetailsPrivateSummaryHeading);
        fields.complex(CaseData::getRespondentSolicitorData)
                    .readonly(RespondentSolicitorData::getConfidentialListDetails)
                    .fieldShowCondition("keepDetailsPrivateSummary=\"never_show\"").done();
        fields.readonlyNoSummary(CaseData::getKeepDetailsPrivateSummary);
        fields.readonlyNoSummary(CaseData::getCourtActionHeading);
        fields.readonlyNoSummary(CaseData::getCourtAction);
    }
}
