package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.complextypes.ChildDetailsRevised;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code childDetailsRevised}.
 */
public final class ChildDetailsRevisedPage1 {
    private ChildDetailsRevisedPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.readonlyNoSummary(CaseData::getSubmissionRequiredFieldsInfo1);
        fields.complex(CaseData::getNewChildDetails).done();
        fields.complex(CaseData::getNewChildDetails, ChildDetailsRevised.class)
                    .optional(ChildDetailsRevised::getFirstName)
                    .optional(ChildDetailsRevised::getLastName)
                    .optional(ChildDetailsRevised::getDateOfBirth)
                    .optional(ChildDetailsRevised::getGender)
                    .optional(ChildDetailsRevised::getOtherGender)
                    .fieldShowCondition("newChildDetails.gender=\"other\"")
                    .optional(ChildDetailsRevised::getOrderAppliedFor)
                    .readonly(ChildDetailsRevised::getParentalResponsibility)
                    .optional(ChildDetailsRevised::getParentalResponsibilityDetails)
                    .optional(ChildDetailsRevised::getWhoDoesTheChildLiveWith).done();
    }
}
