package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.StandardDirectionOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code draftAnOrder}.
 */
public final class DraftAnOrderPage1 {
    private DraftAnOrderPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.mandatory(CaseData::getDraftOrderOptions)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoPreamblesTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoCafcassOrCymruTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoLocalAuthorityTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoCourtTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoDocumentationAndEvidenceTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoOtherTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoHearingsAndNextStepsTempList)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getListElementsSetToDefaultValue)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optionalNoSummary(CaseDataExtra::getDraftOrderCollectionId)
                    .fieldShowCondition("draftOrderOptions=\"DO_NOT_SHOW\"")
                    .retainHiddenValue().done();
    }
}
