package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 16} of event {@code draftAnOrder}.
 */
public final class DraftAnOrderPage16 {
    private DraftAnOrderPage16() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("16");
        fields.showCondition("createSelectOrderOptions=\"DO_NOT_SHOW\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSelectedOrder4)
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .mandatory(ManageOrders::getManageOrdersFl402CourtName)
                    .publish(false)
                    .mandatory(ManageOrders::getManageOrdersFl402CourtAddress)
                    .publish(false)
                    .mandatory(ManageOrders::getManageOrdersFl402CaseNo)
                    .publish(false)
                    .mandatory(ManageOrders::getManageOrdersFl402Applicant)
                    .publish(false)
                    .mandatory(ManageOrders::getManageOrdersFl402ApplicantRef)
                    .publish(false)
                    .mandatory(ManageOrders::getManageOrdersDateOfhearing)
                    .publish(false)
                    .mandatory(ManageOrders::getDateOfHearingTime)
                    .publish(false)
                    .mandatory(ManageOrders::getDateOfHearingTimeEstimate)
                    .publish(false)
                    .mandatory(ManageOrders::getFl402HearingCourtname)
                    .publish(false)
                    .mandatory(ManageOrders::getFl402HearingCourtAddress)
                    .publish(false).done();
    }
}
