package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.StandardDirectionOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Field placements for page {@code 13} of event {@code draftAnOrder} (part 1 of 2).
 */
public final class DraftAnOrderPage13Fields1 {
    private DraftAnOrderPage13Fields1() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.readonly(CaseData::getSdoSdoLabel)
                    .publish(false);
        fields.readonly(CaseData::getSdoPreamblesLabel)
                    .fieldShowCondition("sdoPreamblesList CONTAINS \"rightToAskCourt\" OR sdoPreamblesList CONTAINS \"partyRaisedDomesticAbuse\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoRightToAskCourtLabel)
                    .fieldShowCondition("sdoPreamblesList CONTAINS \"rightToAskCourt\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoRightToAskCourt)
                    .fieldShowCondition("sdoPreamblesList CONTAINS \"rightToAskCourt\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoPartiesRaisedAbuseLabel)
                    .fieldShowCondition("sdoPreamblesList CONTAINS \"partyRaisedDomesticAbuse\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoPartiesRaisedAbuseCollection)
                    .fieldShowCondition("sdoPreamblesList CONTAINS \"partyRaisedDomesticAbuse\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoHearingsAndNextStepsLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"nextStepsAfterGateKeeping\" OR sdoHearingsAndNextStepsList CONTAINS \"allocationDecision\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoNextStepsAfterSecondGKLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"nextStepsAfterGateKeeping\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoNextStepsAfterSecondGK)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"nextStepsAfterGateKeeping\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoAllocationDecisionLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"allocationDecision\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoNextStepsAllocationTo)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"allocationDecision\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoUrgentHearingLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoUrgentHearingPlaceLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.optional(CaseData::getSdoUrgentHearingDate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.optional(CaseData::getSdoUrgentHearingTimeEstimate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoUrgentHearingCourtDynamicList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoHearingUrgentBecauseLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoHearingUrgentCheckList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getSdoHearingUrgentDetails)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoHearingUrgentCourtConsider)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoHearingUrgentTimeShortened)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoHearingUrgentMustBeServedBy)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getSdoHearingUrgentByWayOf)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoHearingNotNeededLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"hearingNotNeeded\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoHearingNotNeeded)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"hearingNotNeeded\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoFhdraLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"fhdra\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoFhdraHearingDisputeLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"fhdra\"")
                    .publish(false);
        fields.optional(CaseData::getSdoFhdraStartDateTime)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"fhdra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoFhdraCourtDynamicList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"fhdra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoFhdraBeforeAList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"fhdra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoFhdraByWayOf)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"fhdra\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoParticipationDirectionsLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"participationDirections\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoParticipationDirections)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"participationDirections\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoPositionStatementLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"positionStatement\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoPositionStatementDeadlineDate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"positionStatement\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoPositionStatementWritten)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"positionStatement\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoMiamAttendanceLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"miamAttendance\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoMiamAttendingPerson)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"miamAttendance\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoPermissionHearingLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"permissionHearing\"")
                    .publish(false);
        fields.optional(CaseData::getSdoPermissionHearingOn)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"permissionHearing\"")
                    .publish(false);
        fields.optional(CaseData::getSdoPermissionHearingTimeEstimate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"permissionHearing\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoPermissionHearingBeforeAList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"permissionHearing\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoDirectionsForDraLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoDirectionsDraDecideBy)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false);
        fields.optional(CaseData::getSdoDirectionsDraStartDateAndTime)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoDirectionsDraHearing)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoDirectionsDraCourtDynamicList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoDirectionsDraHearingByWayOf)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"directionForDra\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoSettlementConferenceLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoSettlementConferenceList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoSettlementConferenceDateTime)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
        fields.optional(CaseData::getSdoSettlementConferenceTimeEstimate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoSettlementConferenceCourtDynamicList)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoSettlementConferenceByWayOf)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"settlementConference\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoJoiningInstructionsForRHLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"joiningInstructions\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoJoiningInstructionsForRH)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"joiningInstructions\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoDirectionsForFactFindingHearingLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoHearingAllegationsMadeBy)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoHearingCourtHasRequested)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoAllegationsDeadlineDate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoWrittenResponseDeadlineDate)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getSdoHearingReportsSentTo)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoHearingReportsAlsoSentTo)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoHearingMaximumPages)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoHearingHowManyWitnessEvidence)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"factFindingHearing\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoArrangeInterpretersLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"interpreters\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoInterpreterDialectRequired)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"interpreters\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoUpdateContactDetailsLabel)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"updateContactDetails\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoUpdateContactDetails)
                    .fieldShowCondition("sdoHearingsAndNextStepsList CONTAINS \"updateContactDetails\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoCafcassOrCafcassCymruLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassOnly\" OR sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassCymru\" OR sdoCafcassOrCymruList CONTAINS \"partyToProvideDetailsOnly\" OR sdoCafcassOrCymruList CONTAINS \"section7Report\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoSafeGuardingNextStepsLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassOnly\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoCafcassFileAndServe)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassOnly\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoCafcassNextStepEditContent)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassOnly\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSafeGuardingNextStepsCymruLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassCymru\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoCafcassCymruFileAndServe)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassCymru\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoCafcassCymruNextStepEditContent)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"safeguardingCafcassCymru\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSafeGuardingNewPartnerLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"partyToProvideDetailsOnly\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoNewPartnersToCafcass)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"partyToProvideDetailsOnly\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSectionReportOrChildImpactLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoSection7EditContent)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoSection7ImpactAnalysisOptions)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSection7FactsLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\" AND sdoSection7ImpactAnalysisOptions CONTAINS \"interimOrders\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoSection7FactsEditContent)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\" AND sdoSection7ImpactAnalysisOptions CONTAINS \"interimOrders\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSection7daOccuredLabel)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\" AND sdoSection7ImpactAnalysisOptions CONTAINS \"daOccured\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoSection7daOccuredEditContent)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\" AND sdoSection7ImpactAnalysisOptions CONTAINS \"daOccured\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoSection7ChildImpactAnalysis)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoNameOfCouncil)
                    .fieldShowCondition("sdoSection7ChildImpactAnalysis = \"nameOfCouncil\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoCafcassCymruReportSentByDate)
                    .fieldShowCondition("sdoCafcassOrCymruList CONTAINS \"section7Report\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoLocalAuthorityLabel)
                    .fieldShowCondition("sdoLocalAuthorityList CONTAINS \"localAuthorityLetter\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoLocalAuthorityLetterLabel)
                    .fieldShowCondition("sdoLocalAuthorityList CONTAINS \"localAuthorityLetter\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoLocalAuthorityName)
                    .fieldShowCondition("sdoLocalAuthorityList CONTAINS \"localAuthorityLetter\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoLocalAuthorityTextArea)
                    .fieldShowCondition("sdoLocalAuthorityList CONTAINS \"localAuthorityLetter\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoLocalAuthorityReportSubmitByDate)
                    .fieldShowCondition("sdoLocalAuthorityList CONTAINS \"localAuthorityLetter\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoCourtLabel)
                    .fieldShowCondition("sdoCourtList CONTAINS \"transferApplication\" OR sdoCourtList CONTAINS \"crossExaminationProhibition\" OR sdoCourtList CONTAINS \"crossExaminationEx740\" OR sdoCourtList CONTAINS \"crossExaminationQualifiedLegal\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoTransferApplicationLabel)
                    .fieldShowCondition("sdoCourtList CONTAINS \"transferApplication\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoTransferApplicationCourtDynamicList)
                    .fieldShowCondition("sdoCourtList CONTAINS \"transferApplication\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoTransferApplicationReason)
                    .fieldShowCondition("sdoCourtList CONTAINS \"transferApplication\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoTransferApplicationSpecificReason)
                    .fieldShowCondition("sdoTransferApplicationReason CONTAINS \"other\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoCrossExaminationProhibitionLabel)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationProhibition\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoCrossExaminationEditContent)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationProhibition\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getSdoCrossExaminationSittingBeforeOptions)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationProhibition\"")
                    .publish(false);
        fields.mandatory(CaseData::getSdoCrossExaminationCourtDynamicList)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationProhibition\"")
                    .publish(false);
        fields.optional(CaseData::getSdoCrossExaminationStartDateTime)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationProhibition\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoCrossExaminationCourtHavingHeard)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationProhibition\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoCrossExaminationEx740Label)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationEx740\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoCrossExaminationEx740)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationEx740\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoCrossExaminationQualifiedLegalLabel)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationQualifiedLegal\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoCrossExaminationQualifiedLegal)
                    .fieldShowCondition("sdoCourtList CONTAINS \"crossExaminationQualifiedLegal\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoDocumentationAndEvidenceLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\" OR sdoDocumentationAndEvidenceList CONTAINS \"specifiedDocuments\" OR sdoDocumentationAndEvidenceList CONTAINS \"instructionsFiling\" OR sdoDocumentationAndEvidenceList CONTAINS \"spipAttendance\" OR sdoDocumentationAndEvidenceList CONTAINS \"medicalDisclosure\" OR sdoDocumentationAndEvidenceList CONTAINS \"letterFromGP\" OR sdoDocumentationAndEvidenceList CONTAINS \"letterFromSchool\" OR sdoDocumentationAndEvidenceList CONTAINS \"scheduleOfAllegations\"")
                    .publish(false);
        fields.readonly(CaseData::getSdoWitnessStatementsLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoWitnessStatementsDeadlineDate)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoWitnessStatementsSentTo)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoWitnessStatementsCopiesSentTo)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getSdoWitnessStatementsCopiesSentToCafcass)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\"")
                    .publish(false);
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoWitnessStatementsMaximumPages)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"witnessStatements\"")
                    .publish(false).done();
        fields.readonly(CaseData::getSdoSpecifiedDocumentsLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"specifiedDocuments\"")
                    .publish(false);
    }
}
