package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.StandardDirectionOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Field placements for page {@code 13} of event {@code draftAnOrder} (part 2 of 2).
 */
public final class DraftAnOrderPage13Fields2 {
    private DraftAnOrderPage13Fields2() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoSpecifiedDocuments)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"specifiedDocuments\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoInstructionsFilingLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"instructionsFiling\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoInstructionsFilingPartiesDynamicList)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"instructionsFiling\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoSpipAttendanceLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"spipAttendance\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoSpipAttendance)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"spipAttendance\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoMedicalDisclosureLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"medicalDisclosure\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoHospitalRecordsDeadlineDate)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"medicalDisclosure\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoMedicalDisclosureUploadedBy)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"medicalDisclosure\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoLetterFromGpLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"letterFromGP\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoLetterFromGpDeadlineDate)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"letterFromGP\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoLetterFromGpUploadedBy)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"letterFromGP\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoLetterFromSchoolLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"letterFromSchool\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoLetterFromSchoolDeadlineDate)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"letterFromSchool\"")
                    .publish(false)
                    .mandatory(StandardDirectionOrder::getSdoLetterFromSchoolUploadedBy)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"letterFromSchool\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoScheduleOfAllegationsLabel)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"scheduleOfAllegations\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoScheduleOfAllegationsOption)
                    .fieldShowCondition("sdoDocumentationAndEvidenceList CONTAINS \"scheduleOfAllegations\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoOtherLabel)
                    .fieldShowCondition("sdoOtherList CONTAINS \"disclosureOfPapers\" OR sdoOtherList CONTAINS \"parentWithCare\"")
                    .publish(false)
                    .readonly(CaseDataExtra::getSdoDisclosureOfPapersLabel)
                    .fieldShowCondition("sdoOtherList CONTAINS \"disclosureOfPapers\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .optional(StandardDirectionOrder::getSdoDisclosureOfPapersCaseNumbers)
                    .fieldShowCondition("sdoOtherList CONTAINS \"disclosureOfPapers\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getSdoParentWithCareLabel)
                    .fieldShowCondition("sdoOtherList CONTAINS \"parentWithCare\"")
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .mandatory(StandardDirectionOrder::getSdoParentWithCare)
                    .fieldShowCondition("sdoOtherList CONTAINS \"parentWithCare\"")
                    .publish(false).done();
    }
}
