package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 10} of event {@code editAndApproveAnOrder}.
 */
public final class EditAndApproveAnOrderPage10 {
    private EditAndApproveAnOrderPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("10");
        fields.showCondition("orderUploadedAsDraftFlag!=\"Yes\" AND (whatToDoWithOrderSolicitor=\"editTheOrderAndServe\" OR whatToDoWithOrderCourtAdmin=\"editTheOrderAndServe\") AND orderType=\"appointmentOfGuardian\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getOrderNameLabel10)
                    .publish(false)
                    .readonly(CaseDataExtra::getSelectedOrder1)
                    .publish(false)
                    .readonly(CaseDataExtra::getCaffcassOfficeName)
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .mandatory(ManageOrders::getCafcassOfficeDetails)
                    .publish(false).done();
    }
}
