package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.StandardDirectionOrder;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code editReturnedOrder}.
 */
public final class EditReturnedOrderProdPage1 {
    private EditReturnedOrderProdPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.complex(CaseData::getManageOrders)
                    .mandatory(ManageOrders::getRejectedOrdersDynamicList)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optionalNoSummary(CaseDataExtra::getIsHearingPageNeeded)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getStandardDirectionOrder)
                    .readonly(StandardDirectionOrder::getSdoPreamblesTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoCafcassOrCymruTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoLocalAuthorityTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoCourtTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoDocumentationAndEvidenceTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoOtherTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getSdoHearingsAndNextStepsTempList)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getListElementsSetToDefaultValue)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonlyNoSummary(StandardDirectionOrder::getEditedOrderHasDefaultCaseFields)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optionalNoSummary(CaseDataExtra::getDraftOrderCollectionId)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue().done();
    }
}
