package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code editReturnedOrder}.
 */
public final class EditReturnedOrderProdPage2 {
    private EditReturnedOrderProdPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.readonly(CaseData::getOrderType)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getOrderName)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getOrderNameInstructionsFromJudgeLabel)
                    .publish(false);
        fields.readonly(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.complex(CaseData::getManageOrders)
                    .readonly(ManageOrders::getOrderUploadedAsDraftFlag)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .readonly(ManageOrders::getC21OrderOptions)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .mandatory(ManageOrders::getEditOrderTextInstructions)
                    .fieldShowCondition("rejectedOrdersDynamicList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.readonly(CaseData::getEditOrderTextInstructionsLabel)
                    .publish(false);
        fields.complex(CaseData::getManageOrders)
                    .readonly(ManageOrders::getPreviewUploadedOrder)
                    .publish(false).done();
    }
}
