package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.gatekeeping.Fl401ListOnNotice;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code fl401ListOnNotice}.
 */
public final class Fl401ListOnNoticePage1 {
    private Fl401ListOnNoticePage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.showCondition("isFl401CaseCreatedForWithOutNotice=\"Yes\"");
        fields.complex(CaseData::getFl401ListOnNotice)
                    .optional(Fl401ListOnNotice::getIsFl401CaseCreatedForWithOutNotice)
                    .fieldShowCondition("fl401RejectListWithoutNoticeHearingRequestLabel=\"DO_NOT_SHOW\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getFl401RejectListWithoutNoticeHearingRequestLabel)
                    .publish(false)
                    .mandatory(CaseDataExtra::getFl401ReasonsForListWithoutNoticeRequested)
                    .publish(false).done();
    }
}
