package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 15} of event {@code hearingEditAndApproveAnOrder}.
 */
public final class HearingEditAndApproveAnOrderPage15 {
    private HearingEditAndApproveAnOrderPage15() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("15");
        fields.showCondition("doYouWantToEditTheOrder=\"Yes\" AND isHearingPageNeeded=\"Yes\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getOrderNameHearingLabel)
                    .publish(false)
                    .readonlyNoSummary(CaseDataExtra::getCreateHearingRequiredLabel)
                    .fieldShowCondition("orderType=\"DO_NOT_SHOW\"")
                    .publish(false)
                    .readonlyNoSummary(CaseDataExtra::getCreateHearingOptionalLabel)
                    .fieldShowCondition("orderType=\"DO_NOT_SHOW\"")
                    .publish(false)
                    .optional(CaseDataExtra::getOrdersHearingDetails)
                    .publish(false).done();
    }
}
