package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 27} of event {@code manageOrders}.
 */
public final class ManageOrdersPage27 {
    private ManageOrdersPage27() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("27");
        fields.showCondition("(manageOrdersOptions=\"servedSavedOrders\" OR doYouWantToServeOrder=\"Yes\") AND loggedInUserType!=\"JUDGE\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getManageOrderHeaderLabel21)
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .mandatory(ManageOrders::getServeOrderDynamicList)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getServeOrderAdditionalDocumentsLabel)
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .optional(ManageOrders::getServeOrderAdditionalDocuments)
                    .publish(false)
                    .mandatoryNoSummary(ManageOrders::getOrdersNeedToBeServed)
                    .fieldShowCondition("manageOrderHeaderLabel21=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false)
                    .mandatoryNoSummary(ManageOrders::getCurrentOrderCreatedDateTime)
                    .fieldShowCondition("manageOrderHeaderLabel21=\"DO_NOT_SHOW\"")
                    .publish(false).done();
        fields.mandatoryNoSummary(CaseData::getIsCafcass)
                    .fieldShowCondition("manageOrderHeaderLabel21=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.complex(CaseData::getManageOrders)
                    .mandatoryNoSummary(ManageOrders::getOtherPeoplePresentInCaseFlag)
                    .fieldShowCondition("manageOrderHeaderLabel21=\"DO_NOT_SHOW\"")
                    .publish(false)
                    .optionalNoSummary(ManageOrders::getIsOnlyC47aOrderSelectedToServe)
                    .fieldShowCondition("manageOrderHeaderLabel22=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .mandatoryNoSummary(CaseDataExtra::getIsInHearingState)
                    .fieldShowCondition("manageOrderHeaderLabel21=\"DO_NOT_SHOW\"")
                    .publish(false).done();
    }
}
