package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.DirectionOnIssue;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Field placements for page {@code 18} of event {@code manageOrders} (part 2 of 4).
 */
public final class ManageOrdersPage18Fields2 {
    private ManageOrdersPage18Fields2() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.readonly(CaseData::getDioUrgentFirstHearingLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false);
        fields.readonly(CaseData::getDioUrgentFirstHearingPlaceLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonly(CaseData::getDioHearingUrgentBecauseLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioHearingUrgentCheckList)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioFirstHearingUrgencyDetailLabel)
                    .fieldShowCondition("dioHearingUrgentCheckList= \"other\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioFirstHearingUrgencyDetails)
                    .fieldShowCondition("dioHearingUrgentCheckList= \"other\"")
                    .publish(false)
                    .mandatory(DirectionOnIssue::getDioHearingUrgentCourtConsider)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false)
                    .mandatory(DirectionOnIssue::getDioHearingUrgentMustBeServedBy)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioHearingUrgentTimeShortenedLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioHearingUrgentDayShortened)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false)
                    .mandatory(DirectionOnIssue::getDioHearingUrgentTimeShortened)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false)
                    .optional(DirectionOnIssue::getDioUrgentFirstHearingDetails)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentFirstHearing\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioUrgentHearingLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .optional(DirectionOnIssue::getDioUrgentHearingDetails)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentHearing\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioUrgentHearingRefusedLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentHearingRefused\"")
                    .publish(false);
        fields.readonly(CaseData::getDioUrgentHearingRefusedCourtLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentHearingRefused\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioUrgentHearingRefusedCheckList)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"urgentHearingRefused\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioUrgentHearingRefusedAnotherReasonLabel)
                    .fieldShowCondition("dioUrgentHearingRefusedCheckList= \"anotherReason\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioHearingUrgencyRefusedDetails)
                    .fieldShowCondition("dioUrgentHearingRefusedCheckList= \"anotherReason\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioWithoutNoticeFirstHearingLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"withoutNoticeFirstHearing\"")
                    .publish(false);
        fields.readonly(CaseData::getDioWithoutNoticeApprovedApplicationLabel)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"withoutNoticeFirstHearing\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioWithoutNoticeFirstHearingCheckList)
                    .fieldShowCondition("dioHearingsAndNextStepsList CONTAINS \"withoutNoticeFirstHearing\"")
                    .publish(false).done();
        fields.readonly(CaseData::getDioWithoutNoticeAnotherReasonLabel)
                    .fieldShowCondition("dioWithoutNoticeFirstHearingCheckList= \"anotherReason\"")
                    .publish(false);
        fields.complex(CaseData::getDirectionOnIssue)
                    .mandatory(DirectionOnIssue::getDioWithoutNoticeFirstHearingDetails)
                    .fieldShowCondition("dioWithoutNoticeFirstHearingCheckList = \"anotherReason\"")
                    .publish(false).done();
    }
}
