package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 16} of event {@code manageOrders}.
 */
public final class ManageOrdersPage16 {
    private ManageOrdersPage16() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("16");
        fields.showCondition("createSelectOrderOptions=\"standardDirectionsOrder\" AND manageOrdersOptions!=\"createCustomOrder\"");
        ManageOrdersPage16Fields1.apply(fields);
        ManageOrdersPage16Fields2.apply(fields);
        ManageOrdersPage16Fields3.apply(fields);
    }
}
