package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 24} of event {@code manageOrders}.
 */
public final class ManageOrdersPage24 {
    private ManageOrdersPage24() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("24");
        fields.showCondition("manageOrdersOptions!=\"servedSavedOrders\" AND loggedInUserType!=\"JUDGE\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAmendOrderCheckOrderLabel)
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .mandatory(ManageOrders::getAmendOrderSelectCheckOptions)
                    .publish(false)
                    .mandatory(ManageOrders::getAmendOrderSelectJudgeOrLa)
                    .fieldShowCondition("amendOrderSelectCheckOptions=\"judgeOrLegalAdvisorCheck\"")
                    .publish(false)
                    .mandatory(ManageOrders::getNameOfJudgeAmendOrder)
                    .fieldShowCondition("amendOrderSelectCheckOptions=\"DO_NOT_SHOW\"")
                    .publish(false)
                    .mandatory(ManageOrders::getNameOfLaAmendOrder)
                    .fieldShowCondition("amendOrderSelectCheckOptions=\"DO_NOT_SHOW\"")
                    .publish(false)
                    .mandatory(ManageOrders::getNameOfJudgeToReviewOrder)
                    .fieldShowCondition("amendOrderSelectCheckOptions=\"judgeOrLegalAdvisorCheck\" AND amendOrderSelectJudgeOrLa=\"judge\"")
                    .publish(false)
                    .mandatory(ManageOrders::getNameOfLaToReviewOrder)
                    .fieldShowCondition("amendOrderSelectCheckOptions=\"judgeOrLegalAdvisorCheck\" AND amendOrderSelectJudgeOrLa=\"legalAdvisor\"")
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getManagerCheckAmendOrder)
                    .fieldShowCondition("amendOrderSelectCheckOptions=\"managerCheck\"")
                    .publish(false).done();
    }
}
