package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 9} of event {@code manageOrders}.
 */
public final class ManageOrdersPage9 {
    private ManageOrdersPage9() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("9");
        fields.showCondition("createSelectOrderOptions=\"transferOfCaseToAnotherCourt\" AND manageOrdersOptions!=\"createCustomOrder\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getTransferCase)
                    .publish(false)
                    .mandatory(CaseDataExtra::getCaseTransferOptions)
                    .fieldShowCondition("createSelectOrderOptions=\"transferOfCaseToAnotherCourt\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getCourtName)
                    .fieldShowCondition("createSelectOrderOptions=\"transferOfCaseToAnotherCourt\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .mandatory(CaseDataExtra::getReasonsForTransfer)
                    .fieldShowCondition("createSelectOrderOptions=\"transferOfCaseToAnotherCourt\"")
                    .publish(false).done();
        fields.mandatory(CaseData::getGiveDetails)
                    .fieldShowCondition("createSelectOrderOptions=\"transferOfCaseToAnotherCourt\" AND reasonsForTransfer CONTAINS \"transferReason7\"")
                    .publish(false);
    }
}
