package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.MiamDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 4} of event {@code miam}.
 */
public final class MiamPage4 {
    private MiamPage4() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("4");
        fields.showCondition("claimingExemptionMiam=\"Yes\" AND applicantAttendedMiam=\"No\" AND familyMediatorMiam=\"No\" AND miamExemptionsChecklist  CONTAINS \"urgency\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSubmissionRequiredFieldsInfo4)
                    .readonly(CaseDataExtra::getMiamUrgencyReasonLabel)
                    .readonly(CaseDataExtra::getMiamUrgencyReasonSelectAll).done();
        fields.complex(CaseData::getMiamDetails)
                    .mandatory(MiamDetails::getMiamUrgencyReasonChecklist).done();
    }
}
