package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.MiamDetails;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 7} of event {@code miam}.
 */
public final class MiamPage7 {
    private MiamPage7() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("7");
        fields.showCondition("applicantAttendedMiam=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSubmissionRequiredFieldsInfo7);
        fields.readonly(CaseData::getMiamCertificationPageLabel);
        fields.complex(CaseData::getMiamDetails)
                    .mandatory(MiamDetails::getMediatorRegistrationNumber)
                    .mandatory(MiamDetails::getFamilyMediatorServiceName)
                    .mandatory(MiamDetails::getSoleTraderName).done();
        fields.readonly(CaseData::getMiamCertificationPageMessage);
        fields.complex(CaseData::getMiamDetails)
                    .mandatory(MiamDetails::getMiamCertificationDocumentUpload).done();
    }
}
