package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ProcessUrgentHelpWithFees;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2} of event {@code processUrgentHelpWithFees}.
 */
public final class ProcessUrgentHelpWithFeesPage2 {
    private ProcessUrgentHelpWithFeesPage2() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("2");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getBeforeYouStart)
                    .publish(false)
                    .readonly(CaseDataExtra::getUpdatePayBubble)
                    .publish(false)
                    .readonly(CaseDataExtra::getApproveDeliveryManagerOrSeniorManager)
                    .publish(false)
                    .readonly(CaseDataExtra::getCheckthehelpwithfeesapplication)
                    .publish(false)
                    .readonly(CaseDataExtra::getApplicationHelpwithfeesreferenceApplicantApplication)
                    .publish(false).done();
        fields.complex(CaseData::getProcessUrgentHelpWithFees)
                    .mandatory(ProcessUrgentHelpWithFees::getOutstandingBalance)
                    .publish(false)
                    .mandatory(ProcessUrgentHelpWithFees::getManagerAgreedApplicationBeforePayment)
                    .fieldShowCondition("outstandingBalance=\"Yes\"")
                    .publish(false).done();
    }
}
