package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ProcessUrgentHelpWithFees;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code processUrgentHelpWithFees}.
 */
public final class ProcessUrgentHelpWithFeesPage1 {
    private ProcessUrgentHelpWithFeesPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.complex(CaseData::getProcessUrgentHelpWithFees)
                    .mandatory(ProcessUrgentHelpWithFees::getHwfAppList)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optionalNoSummary(CaseDataExtra::getAdditionalApplicationsBundleId)
                    .fieldShowCondition("hwfAppList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .readonlyNoSummary(CaseDataExtra::getHwfApplicationDynamicData)
                    .fieldShowCondition("hwfAppList=\"DO_NOT_SHOW\"")
                    .publish(false).done();
    }
}
