package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.dto.ccd.closingcases.ClosingCaseOptions;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code recordFinalDecision}.
 */
public final class RecordFinalDecisionPage1 {
    private RecordFinalDecisionPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getRecordChildrenLabel)
                    .readonlyNoSummary(CaseDataExtra::getCloseCaseLabel).done();
        fields.complex(CaseData::getClosingCaseOptions)
                    .mandatory(ClosingCaseOptions::getIsTheDecisionAboutAllChildren)
                    .mandatory(ClosingCaseOptions::getChildOptionsForFinalDecision)
                    .fieldShowCondition("isTheDecisionAboutAllChildren=\"No\"").done();
    }
}
