package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code sendAndReplyToMessages}.
 */
public final class SendAndReplyToMessagesPage1 {
    private SendAndReplyToMessagesPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.mandatoryNoSummary(CaseData::getChooseSendOrReply)
                    .publish(false);
        fields.mandatory(CaseData::getReplyMessageDynamicList)
                    .fieldShowCondition("chooseSendOrReply=\"REPLY\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("chooseSendOrReply=\"DO_NOT_SHOW\"")
                    .retainHiddenValue();
    }
}
