package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ServiceOfApplication;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;
import uk.gov.hmcts.reform.prl.models.serviceofdocuments.ServiceOfDocuments;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1} of event {@code serviceOfDocuments}.
 */
public final class ServiceOfDocumentsNonprodPage1 {
    private ServiceOfDocumentsNonprodPage1() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("1");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSodAdditionalDocumentsLabel)
                    .publish(false).done();
        fields.complex(CaseData::getServiceOfDocuments)
                    .optional(ServiceOfDocuments::getSodAdditionalDocumentsList)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .readonlyNoSummary(CaseDataExtra::getSodSelectDocumentsLabel)
                    .publish(false).done();
        fields.complex(CaseData::getServiceOfDocuments)
                    .optional(ServiceOfDocuments::getSodDocumentsList)
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optionalNoSummary(CaseDataExtra::getMissingAddressWarningText)
                    .fieldShowCondition("sodAdditionalDocumentsList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.optionalNoSummary(CaseData::getCaseTypeOfApplication)
                    .fieldShowCondition("sodAdditionalDocumentsList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getManageOrders)
                    .optionalNoSummary(ManageOrders::getDisplayLegalRepOption)
                    .fieldShowCondition("sodAdditionalDocumentsList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getServiceOfApplication)
                    .optionalNoSummary(ServiceOfApplication::getSoaOtherPeoplePresentInCaseFlag)
                    .fieldShowCondition("sodAdditionalDocumentsList=\"DO_NOT_SHOW\"")
                    .retainHiddenValue()
                    .publish(false).done();
        fields.complex(CaseData::getCaseDataExtra)
                    .optionalNoSummary(CaseDataExtra::getIsC8CheckNeeded)
                    .fieldShowCondition("caseTypeOfApplication=\"DO_NOT_SHOW\"")
                    .retainHiddenValue().done();
    }
}
