package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseDataExtra;
import uk.gov.hmcts.reform.prl.models.dto.ccd.ManageOrders;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 22} of event {@code waManageOrders}.
 */
public final class WaManageOrdersPage22 {
    private WaManageOrdersPage22() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("22");
        fields.showCondition("manageOrdersOptions=\"amendOrderUnderSlipRule\"");
        fields.complex(CaseData::getCaseDataExtra)
                    .readonly(CaseDataExtra::getAmendOrderDownloadOrderLabel)
                    .publish(false)
                    .readonlyNoSummary(CaseDataExtra::getManageOrdersDocumentToAmendLabel)
                    .publish(false).done();
        fields.complex(CaseData::getManageOrders)
                    .readonly(ManageOrders::getManageOrdersDocumentToAmend)
                    .publish(false).done();
    }
}
