package uk.gov.hmcts.reform.prl.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>Wizard page {@code 102} of event {@code waManageOrders}.
 */
public final class WaManageOrdersPage102 {
    private WaManageOrdersPage102() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, State, Event.EventBuilder<CaseData, UserRole, State>> fields) {
        fields.page("102");
        fields.showCondition("manageOrdersOptions=\"createCustomOrder\"");
        fields.readonlyNoSummary(CaseData::getCustomOrderSelectedHearingLabel)
                    .publish(false);
        fields.mandatory(CaseData::getCustomOrderWasApprovedAtHearing)
                    .publish(false);
        fields.mandatory(CaseData::getCustomOrderHearingsType)
                    .fieldShowCondition("customOrderWasApprovedAtHearing=\"Yes\"")
                    .publish(false);
    }
}
