package uk.gov.hmcts.reform.prl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
public class APPLICANTSOLICITORCrudPlus5RolesZisnxkAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.APPLICANTSOLICITOR, Permission.C);
        grants.put(UserRole.APPLICANTSOLICITOR, Permission.R);
        grants.put(UserRole.APPLICANTSOLICITOR, Permission.U);
        grants.put(UserRole.APPLICANTSOLICITOR, Permission.D);
        grants.put(UserRole.CREATOR, Permission.C);
        grants.put(UserRole.CREATOR, Permission.R);
        grants.put(UserRole.CREATOR, Permission.U);
        grants.put(UserRole.CREATOR, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.U);
        grants.put(UserRole.CITIZEN, Permission.C);
        grants.put(UserRole.CITIZEN, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.U);
        grants.put(UserRole.CITIZEN, Permission.D);
        return grants;
    }
}
