package uk.gov.hmcts.reform.prl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
public class APPLICANTSOLICITORRPlus19RolesFvwefjAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.APPLICANTSOLICITOR, Permission.R);
        grants.put(UserRole.C100_RESPONDENTBARRISTER1, Permission.C);
        grants.put(UserRole.C100_RESPONDENTBARRISTER1, Permission.R);
        grants.put(UserRole.C100_RESPONDENTBARRISTER1, Permission.U);
        grants.put(UserRole.C100_RESPONDENTBARRISTER1, Permission.D);
        grants.put(UserRole.C100_RESPONDENTBARRISTER2, Permission.C);
        grants.put(UserRole.C100_RESPONDENTBARRISTER2, Permission.R);
        grants.put(UserRole.C100_RESPONDENTBARRISTER2, Permission.U);
        grants.put(UserRole.C100_RESPONDENTBARRISTER2, Permission.D);
        grants.put(UserRole.C100_RESPONDENTBARRISTER3, Permission.C);
        grants.put(UserRole.C100_RESPONDENTBARRISTER3, Permission.R);
        grants.put(UserRole.C100_RESPONDENTBARRISTER3, Permission.U);
        grants.put(UserRole.C100_RESPONDENTBARRISTER3, Permission.D);
        grants.put(UserRole.C100_RESPONDENTBARRISTER4, Permission.C);
        grants.put(UserRole.C100_RESPONDENTBARRISTER4, Permission.R);
        grants.put(UserRole.C100_RESPONDENTBARRISTER4, Permission.U);
        grants.put(UserRole.C100_RESPONDENTBARRISTER4, Permission.D);
        grants.put(UserRole.C100_RESPONDENTBARRISTER5, Permission.C);
        grants.put(UserRole.C100_RESPONDENTBARRISTER5, Permission.R);
        grants.put(UserRole.C100_RESPONDENTBARRISTER5, Permission.U);
        grants.put(UserRole.C100_RESPONDENTBARRISTER5, Permission.D);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR1, Permission.C);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR1, Permission.R);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR1, Permission.U);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR1, Permission.D);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR2, Permission.C);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR2, Permission.R);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR2, Permission.U);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR2, Permission.D);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR3, Permission.C);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR3, Permission.R);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR3, Permission.U);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR3, Permission.D);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR4, Permission.C);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR4, Permission.R);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR4, Permission.U);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR4, Permission.D);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR5, Permission.C);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR5, Permission.R);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR5, Permission.U);
        grants.put(UserRole.C100_RESPONDENTSOLICITOR5, Permission.D);
        grants.put(UserRole.CREATOR, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_CAFCASS, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_READONLY, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.D);
        grants.put(UserRole.CITIZEN, Permission.C);
        grants.put(UserRole.CITIZEN, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.U);
        grants.put(UserRole.CITIZEN, Permission.D);
        return grants;
    }
}
