package uk.gov.hmcts.reform.prl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
public class CaseworkerPrivatelawCafcassRPlus3RolesWkowzeAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_PRIVATELAW_CAFCASS, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.R);
        return grants;
    }
}
