package uk.gov.hmcts.reform.prl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
public class CaseworkerPrivatelawSolicitorCruPlus2RolesHjbuaiAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.U);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.C);
        grants.put(UserRole.CITIZEN, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.U);
        return grants;
    }
}
