package uk.gov.hmcts.reform.prl.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
public class LASOLICITORRPlus13RolesTxshhlAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.LASOLICITOR, Permission.R);
        grants.put(UserRole.CASEWORKER_APPROVER, Permission.C);
        grants.put(UserRole.CASEWORKER_APPROVER, Permission.R);
        grants.put(UserRole.CASEWORKER_APPROVER, Permission.U);
        grants.put(UserRole.CASEWORKER_APPROVER, Permission.D);
        grants.put(UserRole.CASEWORKER_CAA, Permission.C);
        grants.put(UserRole.CASEWORKER_CAA, Permission.R);
        grants.put(UserRole.CASEWORKER_CAA, Permission.U);
        grants.put(UserRole.CASEWORKER_CAA, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_COURTADMIN, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_JUDGE, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_LA, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_READONLY, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SOLICITOR, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SUPERUSER, Permission.D);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.R);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE, Permission.D);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.C);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.R);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.U);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.D);
        grants.put(UserRole.CITIZEN, Permission.C);
        grants.put(UserRole.CITIZEN, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.U);
        grants.put(UserRole.CITIZEN, Permission.D);
        grants.put(UserRole.COURTNAV, Permission.C);
        grants.put(UserRole.COURTNAV, Permission.R);
        grants.put(UserRole.COURTNAV, Permission.U);
        grants.put(UserRole.COURTNAV, Permission.D);
        return grants;
    }
}
