bundle:
  folders:
    - name: Preliminary Documents
      documents:
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: caseSummary
              category: caseSummary
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: positionStatements
              category: positionStatements
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: fm5Statements
              category: fm5Statements
    - name: Applications and Orders
      documents:
        - type: documentSet
          property: /data/applications
          filters:
            - property: /documentGroup
              value: applicantApplication
              category: applicantApplication
              hasdraft: true
        - type: documentSet
          property: /data/applications
          filters:
            - property: /documentGroup
              value: applicantC1AApplication
              category: applicantC1AApplication
              hasdraft: true
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: applicantC1AResponse
              category: applicantC1AResponse
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: applicantAWPDocuments
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: applicantMiamCertificate
              category: MIAMCertificate
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: applicantPreviousOrdersSubmittedWithApplication
              category: previousOrdersSubmittedWithApplication
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: respondentApplication
              category: respondentApplication
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: respondentC1AApplication
              category: respondentC1AApplication
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: respondentC1AResponse
              category: respondentC1AResponse
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: respondentAWPDocuments
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: respondentPreviousOrdersSubmittedWithApplication
        - type: documentSet
          property: /data/orders
          filters:
            - property: /documentGroup
              value: ordersSubmittedWithApplication
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: transcriptsOfJudgements
              category: transcriptsOfJudgements
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: magistrateFactAndReasons
              category: magistratesFactsAndReasons
    - name: Witness statement and evidence
      documents:
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: applicantWitnessStatements
              category: applicantStatements
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: respondentWitnessStatements
              category: respondentStatements
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: otherWitnessStatements
              category: otherWitnessStatements
    - name: Expert Reports including Guardian (CAFCASS)
      documents:
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: safeguardingLetter
              category: safeguardingLetter
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: section7Report
              category: section7Report
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: childImpactReport1
              category: childImpactReport1
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: childImpactReport2
              category: childImpactReport2
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: cafcassSection37Report
              category: section37Report
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: sixteenARiskAssessment
              category: 16aRiskAssessment
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: guardianReport
              category: guardianReport
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: specialGuardianshipReport
              category: specialGuardianshipReport
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: cafcassOtherDocuments
              category: otherDocs
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: laSection37Report
              category: sec37Report
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: laOtherDocuments
              category: localAuthorityOtherDoc
    - name: Other Documents
      documents:
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: medicalReports
              category: medicalReports
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: dnaReports
              category: DNAReports_expertReport
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: resultsOfHairStrandBloodTests
              category: resultsOfHairStrandBloodTests
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: policeDisclosures
              category: policeDisclosures
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: medicalRecords
              category: medicalRecords
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: reportsForDrugAndAlcoholTest
              category: drugAndAlcoholTest(toxicology)
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: policeReport
              category: policeReport
        - type: documentSet
          property: /data/allOtherDocuments
          filters:
            - property: /documentGroup
              value: anyOtherDocuments
              category: anyOtherDoc
