package uk.gov.hmcts.reform.prl.models.dto.ccd;

import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "addCaseNoteType",
        generate = true
)
public class AddCaseNoteType {
    @CCD(
            label = "Subject",
            searchable = false
    )
    private String subject;

    @CCD(
            label = "Case note",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String caseNote;

    @CCD(
            label = "User",
            searchable = false
    )
    private String user;

    @CCD(
            label = "Date added",
            searchable = false
    )
    private LocalDate dateAdded;

    @CCD(
            label = "Date created",
            showCondition = "dateCreated=\"DO_NOT_SHOW\"",
            searchable = false
    )
    private LocalDateTime dateCreated;
}
