package uk.gov.hmcts.reform.prl.models.dto.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class AllegationsOfHarmRevisedChildAbduction {
    @CCD(
            label = "Why do you believe the child(ren) may be abducted?",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String newChildAbductionReasons;

    @CCD(
            label = "Have there been any previous threats, attempts to abduct or actual  abduction of the child(ren)?",
            searchable = false
    )
    private YesOrNo newPreviousAbductionThreats;

    @CCD(
            label = "Give details",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String newPreviousAbductionThreatsDetails;

    @CCD(
            label = "Where is/are the child(ren) now?",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String newChildrenLocationNow;

    @CCD(
            label = "Has the passport office been notified?",
            searchable = false
    )
    private YesOrNo newAbductionPassportOfficeNotified;

    @CCD(
            label = "Were the police or any other organisation/agency involved in any previous incident of attempted abduction or abduction?",
            searchable = false
    )
    private YesOrNo newAbductionPreviousPoliceInvolvement;

    @CCD(
            label = "Give details",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String newAbductionPreviousPoliceInvolvementDetails;

    @CCD(
            label = "Do any of the children have a passport?",
            searchable = false
    )
    private YesOrNo newAbductionChildHasPassport;

    @CCD(
            label = "Do the children have more than one passport",
            searchable = false
    )
    private YesOrNo newChildHasMultiplePassports;

    @CCD(
            label = "Who has the children's passport(s)",
            searchable = false
    )
    private String newChildPassportPossession;
}
