package uk.gov.hmcts.reform.prl.models.dto.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "applicantFamilyDetailsObject",
        generate = true
)
public class ApplicantFamilyDetailsObject {
    @CCD(
            label = "*Does the applicant have any children, have parental responsibility for any children or need to protect other children with this application?",
            searchable = false
    )
    private YesOrNo doesApplicantHaveChildren;
}
