package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@ComplexType(
        name = "applicantStopFromRespondentDoingToChildEnum",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ApplicantStopFromRespondentDoingToChildEnum2 implements HasLabel {
    APPLICANT_STOP_FROM_RESPONDENT_DOING_TO_CHILD_ENUM_VALUE_1("Being violent or threatening towards their child or children", "applicantStopFromRespondentDoingToChildEnum_Value_1"),

    APPLICANT_STOP_FROM_RESPONDENT_DOING_TO_CHILD_ENUM_VALUE_2("Harassing or intimidating their child or children", "applicantStopFromRespondentDoingToChildEnum_Value_2"),

    APPLICANT_STOP_FROM_RESPONDENT_DOING_TO_CHILD_ENUM_VALUE_3("Posting or publishing anything about their child or children in print or digitally", "applicantStopFromRespondentDoingToChildEnum_Value_3"),

    APPLICANT_STOP_FROM_RESPONDENT_DOING_TO_CHILD_ENUM_VALUE_4("Contacting their child or children directly without the applicant’s consent", "applicantStopFromRespondentDoingToChildEnum_Value_4"),

    APPLICANT_STOP_FROM_RESPONDENT_DOING_TO_CHILD_ENUM_VALUE_5("Going to or near the child or child's school or nursery", "applicantStopFromRespondentDoingToChildEnum_Value_5");

    private final String label;

    @JsonValue
    private final String code;
}
