package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum ChildTypeOfAbuse implements HasLabel {
    PHYSICAL_ABUSE("Physical abuse", "physicalAbuse"),

    PSYCHOLOGICAL_ABUSE("Psychological abuse", "psychologicalAbuse"),

    SEXUAL_ABUSE("Sexual abuse", "sexualAbuse"),

    EMOTIONAL_ABUSE("Emotional abuse", "emotionalAbuse"),

    FINANCIAL_ABUSE("Financial abuse", "financialAbuse");

    private final String label;

    @JsonValue
    private final String code;
}
