package uk.gov.hmcts.reform.prl.models.dto.ccd;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ChildToBeProtected {
    @CCD(
            label = "Child’s full name",
            searchable = false
    )
    private String fullName;

    @CCD(
            label = "Child’s date of birth",
            searchable = false
    )
    private LocalDate dateOfBirth;

    @CCD(
            label = "Applicant’s relationship to child",
            searchable = false
    )
    private String applicantChildRelationship;

    @CCD(
            label = "Do the applicant and the respondent have shared parental responsibility?",
            searchable = false
    )
    private YesOrNo applicantRespondentShareParental;

    @CCD(
            label = "Respondent’s relationship to the child",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String respondentChildRelationship;

    @CCD(
            label = "Resolution Reason",
            searchable = false
    )
    private String finalDecisionResolutionReason;

    @CCD(
            label = "Resolution Date",
            searchable = false
    )
    private String finalDecisionResolutionDate;
}
