package uk.gov.hmcts.reform.prl.models.dto.ccd;
import uk.gov.hmcts.reform.prl.enums.RelationshipsEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class ChildrenAndApplicants {
    @CCD(
            label = "Applicant's full name:"
    )
    private String applicantFullName;

    @CCD(
            label = "Child's name:"
    )
    private String childFullName;

    @CCD(
            label = "What is the applicant's relationship to child?",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "RelationshipsEnum"
    )
    private RelationshipsEnum childAndApplicantRelation;

    @CCD(
            label = "Give details"
    )
    private String childAndApplicantRelationOtherDetails;

    @CCD(
            label = "Does the child live with this person?"
    )
    private YesOrNo childLivesWith;
}
