package uk.gov.hmcts.reform.prl.models.dto.ccd;
import uk.gov.hmcts.reform.prl.enums.ConfidentialityChecksDisclaimerEnum;

import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "confidentialityDisclaimerObject",
        generate = true
)
public class ConfidentialityDisclaimerObject {
    @CCD(
            label = "# Confidentiality Statement",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String confidentialityStatementLabel;

    @CCD(
            label = "## Confidentiality checks",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String confidentialityChecksLabel;

    @CCD(
            label = "Ensure that no private information has been disclosed in the application.\n"
                            + "\n"
                            + "Check:\n"
                            + "\n"
                            + "- any documents you complete now\n"
                            + "- any documents you complete in the future\n"
                            + "- documents received from other people, such as financial statements\n"
                            + "\n"
                            + "The court staff will not be able to make these checks and will not be able to prevent any accidental disclosure of private information.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String confidentialityChecksText;

    @CCD(
            label = "Ensure that no private information has been disclosed in the response.\n"
                            + "\n"
                            + "Check:\n"
                            + "\n"
                            + "- any documents you complete now\n"
                            + "- any documents you complete in the future\n"
                            + "- documents received from other people, such as financial statements\n"
                            + "\n"
                            + "The court staff will not be able to make these checks and will not be able to prevent any accidental disclosure of private information.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String confidentialityChecksTextResponse;

    @CCD(
            label = " ",
            searchable = false
    )
    private Set<ConfidentialityChecksDisclaimerEnum> confidentialityChecksChecked;
}
