package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@ComplexType(
        name = "courtDeclaresEnum4",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CourtDeclaresEnum4 implements HasLabel {
    OTHER1("other", "other1");

    private final String label;

    @JsonValue
    private final String code;
}
