package uk.gov.hmcts.reform.prl.models.dto.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "createBundleTransitionDetailsObject",
        generate = true
)
public class CreateBundleTransitionDetailsObject {
    @CCD(
            label = "Please click Submit button to generate the bundle",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String createBundleSubmitLabel;

    @CCD(
            label = "<div class='govuk-warning-text'><span class='govuk-warning-text__icon'>!</span><strong class='govuk-warning-text__text'>Please wait for sometime to generate the pdf</strong></div>",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String bundleCreationSubmittedWhatHappensNext;

    @CCD(
            label = "<div class='govuk-warning-text'><span class='govuk-warning-text__icon'>!</span><strong class='govuk-warning-text__text'>Please wait for sometime to generate the pdf</strong></div>",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String bundleCreationSubmittedWhatHappensNextLabel;
}
