package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum DioFurtherInstructionsEnum implements HasLabel {
    NEW_DIRECTION("Add a new direction", "newDirection");

    private final String label;

    @JsonValue
    private final String code;
}
