package uk.gov.hmcts.reform.prl.models.dto.ccd;
import uk.gov.hmcts.reform.prl.enums.YesNoDontKnow;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Fl401ProceedingDetails {
    @CCD(
            label = "*Are there previous or ongoing family court proceedings involving the applicant and respondent?",
            searchable = false
    )
    private YesNoDontKnow hasPrevOrOngoingOtherProceeding;

    @CCD(
            label = "Other Proceedings",
            searchable = false
    )
    private List<ListValue<Fl401OtherProceedingsData>> fl401OtherProceedings;
}
