package uk.gov.hmcts.reform.prl.models.dto.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class Fl401OtherProceedingsData {
    @CCD(
            label = "Name of the court",
            searchable = false
    )
    private String nameOfCourt;

    @CCD(
            label = "Case number",
            searchable = false
    )
    private String caseNumber;

    @CCD(
            label = "*Type of case",
            searchable = false
    )
    private String typeOfCase;

    @CCD(
            label = "*Any other details",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String anyOtherDetails;

    @CCD(
            label = "Upload relevant order(s)",
            categoryID = "previousOrdersSubmittedWithApplication",
            searchable = false
    )
    private Document uploadRelevantOrder;

    @CCD(
            label = "## Add new proceeding",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String addNewProceedingLabel;
}
