package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum HumbersideDFJCourts implements HasLabel {
    _478126("Great Grimsby", "478126"),

    _195520("Kingston Upon Hull", "195520");

    private final String label;

    @JsonValue
    private final String code;
}
