package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@ComplexType(
        name = "rejectReasonEnum",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RejectReasonEnum2 implements HasLabel {
    CONSENT_ORDER_NOT_PROVIDED("Consent Order not provided", "consentOrderNotProvided"),

    MIAM_CERTIFICATE_NOT_PROVIDED("MIAM certificate not provided", "miamCertificateNotProvided"),

    INCOMPLETE_EVIDENCE_OF_MIAM_EXAMPTION("Evidence of MIAM exemption incomplete", "incompleteEvidenceOfMiamExamption"),

    CONFIDENTAL_DETAIL_LISTED("Confidential detail listed", "confidentalDetailListed"),

    SECTION9114_ORDER_IN_FORCE("Section 91(14) order in force", "section9114OrderInForce"),

    PERMISSION_IS_NEEDED("Permission is needed to make application", "permissionIsNeeded"),

    PARENTAL_RESPONSIBILITY("Parental responsibility", "parentalResponsibility"),

    APPLICATION_INCOMPLETE("Application incomplete", "applicationIncomplete"),

    CLARIFICATION_NEEDED("Clarification needed", "clarificationNeeded"),

    OTHER_REASON("Other", "otherReason");

    private final String label;

    @JsonValue
    private final String code;
}
