package uk.gov.hmcts.reform.prl.models.dto.ccd;
import uk.gov.hmcts.reform.prl.enums.TypeOfAbuseEnum;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class RespDomesticBehaviours {
    @CCD(
            label = "Type of abuse",
            searchable = false
    )
    private TypeOfAbuseEnum respTypeOfAbuse;

    @CCD(
            label = "Describe the nature of the behaviour, what happened and who was involved.",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String respAbuseNatureDescription;

    @CCD(
            label = "When did the behaviour start and how long did it continue? \n"
                            + "(Does not need to be exact date and indicate if abuse is ongoing).",
            searchable = false
    )
    private String respBehavioursStartDateAndLength;

    @CCD(
            label = "Did the respondent seek help?",
            searchable = false
    )
    private YesOrNo respBehavioursApplicantSoughtHelp;

    @CCD(
            label = "Who did they seek help from, and what they did to help?",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String respBehavioursApplicantHelpSoughtWho;

    @CCD(
            label = "## Add another behaviour",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String addNewRespDomesticBehavioursLabel;
}
