package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@ComplexType(
        name = "respondentNotToDoEnum3",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RespondentNotToDoEnum3 implements HasLabel {
    RESPONDENT_MUST_NOT_TELEPHONE("must not telephone, text, email or otherwise contact or attempt to contact the applicant", "respondentMustNotTelephone");

    private final String label;

    @JsonValue
    private final String code;
}
