package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "schoolDirections&Details",
        generate = true
)
public class SchoolDirectionsDetails {
    @JsonProperty("fl404SchoolDirections&DetailsComplex")
    @CCD(
            label = "Add directions and any further details",
            searchable = false
    )
    private String fl404SchoolDirections_DetailsComplex;
}
