package uk.gov.hmcts.reform.prl.models.dto.ccd;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@ComplexType(
        name = "sendOrReply",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum SendOrReply2 implements HasLabel {
    SEND("Send a message"),

    REPLY("Reply to a message");

    private final String label;
}
