package uk.gov.hmcts.reform.prl.models.dto.ccd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class SolicitorInternationalElement {
    @CCD(
            label = "Do you have any reason to believe that any child, parent or potentially significant adult in the child's life may be habitually resident in another country abroad or in Scotland or Northern Ireland?",
            searchable = false
    )
    private YesOrNo childrenLiveOutsideOfEnWl;

    @CCD(
            label = "*Provide details",
            showCondition = "childrenLiveOutsideOfEnWl=\"Yes\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String childrenLiveOutsideOfEnWlDetails;

    @CCD(
            label = "Do you have any reason to believe that any parent or anyone significant to the child’s life (adult or child) may be habitually resident in another country abroad or in Scotland or Northern Ireland?",
            hint = "For example, this could include a grandparent or another close relative. They may have work, property or school arrangements that are mainly based outside of England and Wales.",
            searchable = false
    )
    private YesOrNo parentsAnyOneLiveOutsideEnWl;

    @CCD(
            label = "*Provide details",
            showCondition = "parentsAnyOneLiveOutsideEnWl=\"Yes\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String parentsAnyOneLiveOutsideEnWlDetails;

    @CCD(
            label = "Do you have any reason to believe that there may be an issue as to jurisdiction, relating to a country abroad or to Scotland or Northern Ireland, in this case?",
            searchable = false
    )
    private YesOrNo anotherPersonOrderOutsideEnWl;

    @CCD(
            label = "*Provide details",
            showCondition = "anotherPersonOrderOutsideEnWl=\"Yes\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String anotherPersonOrderOutsideEnWlDetails;

    @CCD(
            label = "Has a request been made or should a request be made to a Central Authority or other competent authority in a foreign state or a consular authority in England and Wales?",
            searchable = false
    )
    private YesOrNo anotherCountryAskedInformation;

    @CCD(
            label = "*Provide details",
            showCondition = "anotherCountryAskedInformation=\"Yes\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String anotherCountryAskedInformationDetaails;
}
