package uk.gov.hmcts.reform.prl.models.dto.ccd;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 */
@ComplexType(
        name = "theRespondentEnum5",
        generate = true
)
@Getter
@AllArgsConstructor
public enum TheRespondentEnum5 implements HasLabel {
    OBSTRUCT_HARASS_OR_INTERFERE("must not obstruct, harass, or interfere with the applicant's peaceful occupation of the address", "obstructHarassOrInterfere");

    private final String label;

    @JsonValue
    private final String code;
}
