package uk.gov.hmcts.reform.prl.models;

import java.util.Map;

public enum FeeType {
    C100_SUBMISSION_FEE,
    C2_WITH_NOTICE,
    C2_WITHOUT_NOTICE,
    PARENTAL_RESPONSIBILITY;

    public static final Map<String, FeeType> applicationToFeeMap = Map.of(
        "N161_APPELLANT_NOTICE", C2_WITH_NOTICE,
        "C79_ENFORCE_CHILD_ARRANGEMENTS_ORDER", PARENTAL_RESPONSIBILITY,
        "FC600_COMMITTAL_APPLICATION", C2_WITH_NOTICE,
        "C1_APPLY_FOR_CERTAIN_ORDERS_UNDER_THE_CHILDREN_ACT", PARENTAL_RESPONSIBILITY,
        "C3_SEARCH_AND_TAKING_CHARGE_OF_A_CHILD", PARENTAL_RESPONSIBILITY,
        "C4_WHEREABOUTS_OF_A_MISSING_CHILD", PARENTAL_RESPONSIBILITY);
}
