package uk.gov.hmcts.reform.prl.models.citizen;

/**
 * Citizen dashboard notification names.
 */
public enum NotificationNames {
    FM5_REMINDER_APPLICANT_RESPONDENT,
    SOA_PERSONAL_APPLICANT,
    SOA_APPLICANT,
    SOA_RESPONDENT,
    SOA_SOS_CA_CB_APPLICANT,
    VIEW_RESPONDENT_RESP_APPLICANT,
    VIEW_RESPONDENT_C1A_APPL_APPLICANT,
    VIEW_RESPONDENT_C1A_RESP_APPLICANT,
    ORDER_APPLICANT_RESPONDENT,
    ORDER_PERSONAL_APPLICANT,
    ORDER_SOS_CA_CB_APPLICANT
}
