java:
  applicationPort: 4044
  ingressHost: prl-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: prl
  environment:
    PRD_API_BASEURL: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    RUNS_LOCALLY: false
    IDAM_CLIENT_ID: prl-cos-api
    IDAM_CLIENT_REDIRECT_URI: https://prl-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCMOSIS_SERVICE_BASE_URL: https://docmosis.aat.platform.hmcts.net
    CCD_CASE_DOCS_AM_API: http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    REFORM_SERVICE_NAME: prl_cos_api
    AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: prl_cos_api
    AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: 900
    IDAM_S2S_AUTH_MICROSERVICE: prl_cos_api
    PAY_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAY_CALLBACK_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/service-request

  keyVaults:
    prl:
      secrets:
        - prl-cos-idam-client-secret
        - microservicekey-prl-cos-api
        - system-update-user-username
        - system-update-user-password
