java:
  environment:
    PRD_API_BASEURL: http://rd-professional-api-aat.service.core-compute-aat.internal
    LOCATION_REF_API: http://rd-location-ref-api-aat.service.core-compute-{{ .Values.global.environment }}.internal
    RD_PROFESSIONAL_API: http://rd-professional-api-aat.service.core-compute-aat.internal
