package uk.gov.hmcts.reform.prl.ccd;

import java.util.List;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.SearchCriteriaField;
import uk.gov.hmcts.ccd.sdk.api.SearchPartyField;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>The search input/result, search-cases, criteria and parties for {@code PRLAPPS}.
 */
@Component
public class PRLAPPSSearch implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the search input/result, search-cases, criteria and parties for {@code PRLAPPS}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.searchInputFields()
            .field("applicantCaseName", "Case name")
            .field("familymanCaseNumber", "Familyman number")
            .field("[CASE_REFERENCE]", "CCD number")
            .field("caseTypeOfApplication", "Application type");
        builder.searchResultFields()
            .field("applicantCaseName", "Case name")
            .field("selectedCaseTypeID", "Case type")
            .field("[CREATED_DATE]", "Case created date ")
            .field("applicantName", "Applicant name")
            .field("respondentName", "Respondent name")
            .field("childName", "Child name")
            .field("dateSubmitted", "Date submitted");
        builder.searchCasesFields()
            .field("applicantCaseName", "Case name", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases").resultsOrdering("1:ASC"))
            .field("selectedCaseTypeID", "Case type", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases"))
            .field("[CREATED_DATE]", "Case created date ", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases"))
            .field("applicantName", "Applicant name", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases"))
            .field("respondentName", "Respondent name", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases"))
            .field("childName", "Child name", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases"))
            .field("dateSubmitted", "Date submitted", f -> f.role(UserRole.CASEWORKER_CAA).useCase("orgcases"));
        builder.searchCriteria().fields(List.of(SearchCriteriaField.builder().otherCaseReference("familymanCaseNumber").build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("firstName,lastName")
            .searchPartyEmailAddress("email")
            .searchPartyAddressLine1("address.AddressLine1")
            .searchPartyPostCode("address.PostCode")
            .searchPartyDOB("dateOfBirth")
            .searchPartyCollectionFieldName("applicants")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("applicantsFL401.firstName,applicantsFL401.lastName")
            .searchPartyEmailAddress("applicantsFL401.email")
            .searchPartyAddressLine1("applicantsFL401.address.AddressLine1")
            .searchPartyPostCode("applicantsFL401.address.PostCode")
            .searchPartyDOB("applicantsFL401.dateOfBirth")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("firstName,lastName")
            .searchPartyEmailAddress("email")
            .searchPartyAddressLine1("address.AddressLine1")
            .searchPartyPostCode("address.PostCode")
            .searchPartyDOB("dateOfBirth")
            .searchPartyCollectionFieldName("respondents")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("respondentsFL401.firstName,respondentsFL401.lastName")
            .searchPartyEmailAddress("respondentsFL401.email")
            .searchPartyAddressLine1("respondentsFL401.address.AddressLine1")
            .searchPartyPostCode("respondentsFL401.address.PostCode")
            .searchPartyDOB("respondentsFL401.dateOfBirth")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("firstName,lastName")
            .searchPartyDOB("dateOfBirth")
            .searchPartyCollectionFieldName("newChildDetails")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("firstName,lastName")
            .searchPartyDOB("dateOfBirth")
            .searchPartyCollectionFieldName("children")
                    .build()));
        builder.searchParty().fields(List.of(SearchPartyField.builder()
            .searchPartyName("fullName")
            .searchPartyDOB("dateOfBirth")
            .searchPartyCollectionFieldName("applicantChildDetails")
                    .build()));
    }
}
