package uk.gov.hmcts.reform.prl.ccd;

import java.util.Set;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>AuthorisationComplexType grants for {@code PRLAPPS} (part 6).
 */
public final class PRLAPPSComplexTypeGrants06 {
    private PRLAPPSComplexTypeGrants06() {
    }

    /**
     * @param builder the config builder
     */
    static void apply(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Permission.CRU, UserRole.COURTNAV);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Set.of(Permission.R), UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "childOption", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Permission.CRU, UserRole.COURTNAV);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Set.of(Permission.R), UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hasJudgeProvidedHearingDetails", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Permission.CRU, UserRole.COURTNAV);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Set.of(Permission.R), UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "hearingsType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Permission.CRU, UserRole.COURTNAV);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Set.of(Permission.R), UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isOrderCreatedBySolicitor", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Permission.CRU, UserRole.COURTNAV);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Set.of(Permission.R), UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getDraftOrderCollection, "isAutoHearingReqPending", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "isOrderUploaded", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderDocumentNeedSeal", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "orderTypeId", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "orderType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "withdrawnRequestType", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "isWithdrawnRequestApproved", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "typeOfOrder", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_LA);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_SOLICITOR);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRU, UserRole.CASEWORKER_PRIVATELAW_JUDGE);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRU, UserRole.CASEWORKER_WA_TASK_CONFIGURATION);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRU, UserRole.CITIZEN);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_EXTERNALUSER_VIEWONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_CAFCASS);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Set.of(Permission.R), UserRole.CASEWORKER_PRIVATELAW_READONLY);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_COURTADMIN);
        builder.grantComplexType(CaseData::getOrderCollection, "doesOrderClosesCase", Permission.CRUD, UserRole.CASEWORKER_PRIVATELAW_SYSTEMUPDATE);
    }
}
