package uk.gov.hmcts.reform.prl.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.SortOrder;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>The work-basket input and result fields for {@code PRLAPPS}.
 */
@Component
public class PRLAPPSWorkBasket implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the work-basket input and result fields for {@code PRLAPPS}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.workBasketInputFields()
            .field("dfjArea", "DFJ Area")
            .field("swanseaDFJCourt", "Court", f -> f.showCondition("dfjArea = \"SWANSEA\""))
            .field("humbersideDFJCourt", "Court", f -> f.showCondition("dfjArea = \"HUMBERSIDE\""))
            .field("essexAndSuffolkDFJCourt", "Court", f -> f.showCondition("dfjArea = \"ESSEX_AND_SUFFOLK\""))
            .field("wolverhamptonDFJCourt", "Court", f -> f.showCondition("dfjArea = \"WOLVERHAMPTON\""))
            .field("applicantCaseName", "Case name")
            .field("familymanCaseNumber", "Familyman number")
            .field("[CASE_REFERENCE]", "CCD number")
            .field("caseTypeOfApplication", "Application type")
            .field("dateSubmitted", "Date Submitted");
        builder.workBasketResultFields()
            .field("applicantCaseName", "Case")
            .field("familymanCaseNumber", "Familyman number")
            .field("selectedCaseTypeID", "Case type")
            .field("[STATE]", "State")
            .field("applicantName", "Applicant name")
            .field("respondentName", "Respondent name")
            .field("caseSubmittedTimeStamp", "Submitted date and time", f -> f.resultsOrdering(SortOrder.FIRST.DESCENDING));
    }
}
