package uk.gov.hmcts.reform.prl.ccd;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.prl.enums.State;
import uk.gov.hmcts.reform.prl.models.dto.ccd.CaseData;
import uk.gov.hmcts.reform.prl.models.dto.ccd.UserRole;

/**
 * Generated by ccd-definition-converter from PRLAPPS on migration; owned by this service team.
 *
 * <p>The Notice of Change challenge questions for {@code PRLAPPS}.
 */
@Component
public class PRLAPPSNoticeOfChange implements CCDConfig<CaseData, State, UserRole> {
    /**
     * Configures the Notice of Change challenge questions for {@code PRLAPPS}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, State, UserRole> builder) {
        builder.noticeOfChange()
            .challenge("NoCChallenge")
                .question("NoCChallengeQ1", "Your client's first name")
                .displayOrder(1)
                .answerFieldType("Text")
                .answer(UserRole.C100_APPLICANTSOLICITOR1)
                    .field("caApplicant1.firstName")
                .answer(UserRole.C100_APPLICANTSOLICITOR2)
                    .field("caApplicant2.firstName")
                .answer(UserRole.C100_APPLICANTSOLICITOR3)
                    .field("caApplicant3.firstName")
                .answer(UserRole.C100_APPLICANTSOLICITOR4)
                    .field("caApplicant4.firstName")
                .answer(UserRole.C100_APPLICANTSOLICITOR5)
                    .field("caApplicant5.firstName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR1)
                    .field("caRespondent1.firstName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR2)
                    .field("caRespondent2.firstName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR3)
                    .field("caRespondent3.firstName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR4)
                    .field("caRespondent4.firstName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR5)
                    .field("caRespondent5.firstName")
                .answer(UserRole.APPLICANTSOLICITOR)
                    .field("daApplicant.firstName")
                .answer(UserRole.FL401_RESPONDENTSOLICITOR)
                    .field("daRespondent.firstName")
                .done()
                .question("NoCChallengeQ2", "Your client's last name")
                .displayOrder(2)
                .answerFieldType("Text")
                .answer(UserRole.C100_APPLICANTSOLICITOR1)
                    .field("caApplicant1.lastName")
                .answer(UserRole.C100_APPLICANTSOLICITOR2)
                    .field("caApplicant2.lastName")
                .answer(UserRole.C100_APPLICANTSOLICITOR3)
                    .field("caApplicant3.lastName")
                .answer(UserRole.C100_APPLICANTSOLICITOR4)
                    .field("caApplicant4.lastName")
                .answer(UserRole.C100_APPLICANTSOLICITOR5)
                    .field("caApplicant5.lastName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR1)
                    .field("caRespondent1.lastName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR2)
                    .field("caRespondent2.lastName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR3)
                    .field("caRespondent3.lastName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR4)
                    .field("caRespondent4.lastName")
                .answer(UserRole.C100_RESPONDENTSOLICITOR5)
                    .field("caRespondent5.lastName")
                .answer(UserRole.APPLICANTSOLICITOR)
                    .field("daApplicant.lastName")
                .answer(UserRole.FL401_RESPONDENTSOLICITOR)
                    .field("daRespondent.lastName")
                .done();
    }
}
